dubzzz/fast-check

README.md, src/check/arbitrary/LoremArbitrary.ts
=> Add shrinker for LoremArbitrary

README.md, documentation/Runners.md, documentation/Tips.md, src/check/precondition/Pre.ts, src/check/precondition/PreconditionFailure.ts, src/check/property/AsyncProperty.generic.ts, src/check/property/IProperty.ts, src/check/property/Property.generic.ts, src/check/property/TimeoutProperty.ts, src/check/property/UnbiasedProperty.ts, src/check/runner/Runner.ts, src/check/runner/configuration/Parameters.ts, src/check/runner/configuration/QualifiedParameters.ts, src/check/runner/reporter/RunDetails.ts, src/check/runner/reporter/RunExecution.ts, src/check/runner/utils/utils.ts, src/fast-check-default.ts, test/e2e/PreConditionChecks.spec.ts, test/unit/check/precondition/Pre.spec.ts, test/unit/check/property/AsyncProperty.spec.ts, test/unit/check/property/Property.spec.ts, test/unit/check/runner/Runner.spec.ts, test/unit/check/runner/reporter/RunExecution.spec.ts
=> Enable preconditions in predicate

src/check/runner/utils/utils.ts, test/e2e/Shadows.spec.ts, test/unit/check/runner/Runner.spec.ts
This PR changes the error message on a failed test slightly. It looks like this:
```
Property failed after 1 tests
{ seed: 1530466923032, path: "1:1:0:0:0:0:0:0:1:1:3:8:8:9:11:16:20:19:19:19:19:19:22:23" }
Counterexample: [[32,32738,34]]
Shrunk 0 time(s)
```
The major change is that the `seed` and the `path` is now printed so that they can be easily copy-pasted into one's code as an argument to `assert`. Additionally, the counterexample is prefixed with the text "Counterexample" to make it easier to understand and distinguish.
=> Make seed and path copy pasteable

src/check/arbitrary/CharacterArbitrary.ts
Fixes #171 - Do not rely on a custom implementation of CharacterArbitrary for fullUnicode
=> Clean: fullUnicode relies on CharacterArbitrary

test/rollup/rollup.config.js
Basically IIFE and ESM are the two recommended build formats for web applications.
Both of them need to be supported correctly.
=> Rollup should build iife module first

src/check/arbitrary/CharacterArbitrary.ts
=> Characters must be biased by default

.gitignore, package-lock.json, package.json, src/random/generator/Random.ts, src/stream/StreamHelpers.ts
=> Fix some deopt detected using --trace-deopt

src/check/arbitrary/ArrayArbitrary.ts, src/check/model/ModelRunner.ts, src/check/model/commands/CommandWrapper.ts, src/check/model/commands/CommandsArbitrary.ts, src/check/model/commands/CommandsIterable.ts, test/e2e/model/CommandsArbitrary.spec.ts, test/unit/check/model/commands/CommandWrapper.spec.ts, test/unit/check/model/commands/CommandsArbitrary.spec.ts
Fixes #192
Before this development `fc.commands` was relying on `fc.array` to build and shrink commands correctly.
Unfortunately, with this setup it was not possible to benefit from assumptions we can make on commands while shrinking them:
- the last started command should always be kept because it is the one causing the failure (or none of the commands caused the failure)
- string representation was featuring dash (`-`) for non executed commands
- string representation was not reliable when commands were used along with other shrinkable arbitraries
=> Commands generator should not rely on arrays generator

src/check/model/ModelRunner.ts, src/check/model/commands/CommandsArbitrary.ts, src/check/model/commands/CommandsIterable.ts, test/unit/check/model/commands/CommandsArbitrary.spec.ts, test/unit/check/model/commands/CommandsIterable.spec.ts
=> Better handling of commands

src/check/runner/configuration/QualifiedParameters.ts
=> Default seed must use Math.random in addition of time

test/e2e/arbitraries/ArrayArbitrary.spec.ts
The test `Should be biased by default and suggest small entries [bigint]` was quite unstable on Travis.
The commit replaces the usage of fc.bigInt(), which is equivalent to fc.bigIntN(256), by fc.bigIntN(64).
It should highly reduce the size of generated values and thus increase the probality of collision.
=> More stability for e2e checking bias of bigint

src/check/model/commands/CommandsArbitrary.ts
The impact of the change has been measured against
a connect four implementation relying on model-based
approach - https://github.com/dubzzz/connect-four-react.
It confirmed what was observed in other tests based
on fast-check model-based approach.
In general, we observed a reduction in:
- the number of tests executed
- the depth of the shrink tree
Fixes #279
=> Better shrinker for commands

src/check/model/commands/CommandsArbitrary.ts, test/e2e/model/CommandsArbitrary.spec.ts
Before this PR, `fc.commands` was only able to shrink the last command.
In the attached commit I updated the test _Should shrink up to the shortest failing commands list_ so that `inc` and `dec` can increase more than ones per command execution. With the current implementation it resulted in a poorly shrunk counterexample:
```
Should shrink up to the shortest failing commands list
Expected value to equal:
"inc[1],check[1]"
Received:
"inc[1350995096],check[1]"
```
=> BUG: Not shrinking commands themselves

documentation/Arbitraries.md, documentation/Tips.md, src/check/model/ReplayPath.ts, src/check/model/commands/CommandsArbitrary.ts, src/check/model/commands/CommandsIterable.ts, src/check/model/commands/CommandsSettings.ts, test/e2e/ReplayCommands.spec.ts, test/e2e/model/CommandsArbitrary.spec.ts, test/unit/check/model/ReplayPath.spec.ts, test/unit/check/model/commands/CommandsArbitrary.spec.ts, test/unit/check/model/commands/CommandsIterable.spec.ts
Replaying previously executed runs is a must have feature for property based testing frameworks.
Because of the specificities of commands, commands were not eligible to replay.
This commit adds the replay capabilities to commands by specifying an extra parameter when defining them (replayPath).
Related to #251
=> Add replay ability for commands

src/utils/stringify.ts, test/unit/utils/stringify.spec.ts
=> Stringify have to handle boxed values and Set/Map

.travis.yml
Node 11 is not a LTS version of node so it will be removed from the list as soon as node 12 becomes available.
=> Build against node 11

package-lock.json, package.json, src/check/arbitrary/LoremArbitrary.ts, test/unit/check/arbitrary/LoremArbitrary.spec.ts
Fixes #335
The choices has been to removed the dependency towards lorem-ipsum package because:
- Version 2 of the package is not compatible with legacy versions of node
- Package size skyrocketed with the latest major
- https://arve0.github.io/npm-download-size/#lorem-ipsum@2.0.0-alpha.2 - 42.8KiB for a total size of 93.9KiB
- https://arve0.github.io/npm-download-size/#lorem-ipsum@1.0.6 - 4.9KiB for a total size of 12.4KiB
- Up to version 1, the code was doing a simple random on words: relying on built-ins of fast-check to compute the lorem will provide better shrinking capabilities
=> Remove lorem-ipsum dependency

CONTRIBUTORS.md, src/check/arbitrary/IntegerArbitrary.ts, test/unit/check/arbitrary/IntegerArbitrary.spec.ts
Fixes #293 
@dubzzz I noticed that BigInt and Float arbitraries have the same issue. If this solution is valid for you, I can take care of those cases in this PR as well.
=> Add minimum and maximum validation to integer and nat

.prettierignore, documentation/1-Guides/Arbitraries.md, src/check/arbitrary/LetRecArbitrary.ts, src/fast-check-default.ts, test/e2e/NoRegression.spec.ts, test/e2e/__snapshots__/NoRegression.spec.ts.snap, test/e2e/arbitraries/LetRecArbitrary.spec.ts, test/unit/check/arbitrary/LetRecArbitrary.spec.ts, test/unit/check/arbitrary/__snapshots__/LetRecArbitrary.spec.ts.snap
=> Mutually recursive arbitrary builder

CONTRIBUTORS.md, src/check/model/ModelRunner.ts
Example of bug:
```
interface Model {
foo: string;
bar: number;
}
type Real = number;
class Command implements fc.Command<Model, Real> {
check(m: Model) {
return true;
}
run(m: Model, r: Real) {}
toString() {
return "";
}
}
it("should fail typecheck", () => {
return fc.assert(
fc.property(fc.commands([fc.constant(new Command())]), cmds => {
const c = 5;
return fc.modelRun(
() => ({ model: { foo: "what about bar?" }, real: c }),
cmds
);
})
);
});
```
This should ideally not type-check, because `{foo: "what about bar?"}` does not meet the requirement s for the `Model` interface. The generic type parameters for `modelRun` are inferred to be `<{foo: string}, number>` and conveniently `Command<Model, number>` structurally matches `Command<{foo: string", number>` which is why the typescript …
=> Fix type inferrence bug in modelRun

documentation/1-Guides/Arbitraries.md, test/e2e/arbitraries/LetRecArbitrary.spec.ts, test/e2e/arbitraries/MemoArbitrary.spec.ts, test/legacy/main.js
Reduce the flakyness of one of the end-to-end tests on `fc.letrec`.
The test generated trees with a probability to generate a node instance of 1/3.
This probability was too small to ensure that we can find trees of depth >=5 with a high certainty (it failed 1 run every 104 runs).
We increased the probability of generating a node to 45 %.
It provides a very high stability of the test that will theoretically fail every 18.087.934 runs.
None
=> Reduce flakyness of letrec e2e tests

src/check/arbitrary/WebArbitrary.ts
Fixes #407
This change will have an impact on the values generated by:
- `webAuthority` if `withPort` flag is set to true
- `webUrl` if `withPort` flag is set to true
Meanwhile it solves a real bug in the values generated by those generators.
=> Web authority should not produce port outside 0-65535

CONTRIBUTING.md
Adding a new arbitrary within fast-check was not so easy for people outside of the project because it required to use some very specific helpers to assess the arbitrary is ok.
The contributing file has been updated to help people understand what to edit in case they want to contribute and add arbitraries.
None.
=> Document how to add new arbitraries into fast-check

documentation/1-Guides/HandsOnPropertyBased.md
Uses `diff` syntax highlighting in a code example. It looks like this is what you were going for with the `---`/`+++`. Note that only 1 line is changed (the github UI highlights the 2 lines below but that's actually the preview :P
❌ New feature
❌ Fix an issue
None.
=> Docs: Use diff format in shrinking example

src/check/runner/Runner.ts, test/unit/check/runner/Runner.spec.ts
Fixes #415
❌ New feature
None.
=> Infinite loop when path is one level deep and run succeeds

src/check/property/SkipAfterProperty.ts, test/e2e/SkipAllAfterTime.spec.ts, test/unit/check/property/SkipAfterProperty.spec.ts
Related to #423
❌ New feature
✔️/❌ Other: *please explain*
- Run execution
Here are the possible scenarii:
- the code was never reaching the timeout: no change expected
- the code was reaching a timeout during generation phase: it still throws but this time it throws and tell the user that it has not succeeded to generate enough values to conclude (before it was a crash of fast-check)
- the code was reaching a timeout during shrinking phase: it still throws but this time it throws a classical fast-check error with a shrink that has been stopped at the middle (before it was a crash of …
=> skipAllAfterTimeLimit throws an error instead of skipping tests

src/check/arbitrary/OptionArbitrary.ts
Current implementation of `fc.option` does not allow the user to produce something else than `null`. 
By using some tricks we can make it produce other values: `fc.option(arb).map(v => v === null ? otherValueForNull : v)`.
This PR updates `fc.option` so that it can receives an extra parameter to specify the null value we want it to produce: `fc.option(arb, { nil: undefined })`.
_Incomplete PR, need to update UTests and document the change_
Nothing.
=> Add ability to customize the null of fc.option

test/unit/check/arbitrary/LetRecArbitrary.spec.ts, test/unit/check/arbitrary/MemoArbitrary.spec.ts, test/unit/check/arbitrary/TupleArbitrary.generic.spec.ts, test/unit/check/runner/Sampler.spec.ts
The preview version of TypeScript in https://github.com/microsoft/TypeScript/pull/33401 requires some code changes to be done in the unit-tests of fast-check.
No other breaking changes detected.
See https://github.com/dubzzz/fast-check/tree/ts3.7-pr33401
❌ New feature
None.
=> Prepare for TypeScript 3.7 and PR 33401

documentation/1-Guides/Arbitraries.md, src/check/arbitrary/ObjectArbitrary.ts, test/e2e/GenerateAllValues.spec.ts, test/unit/check/arbitrary/ObjectArbitrary.spec.ts
The current implementation of `fc.object`/`fc.anything` was rarely able to generate strings looking as string representations of real objects. As this kind of objects is a known source of issues in computer science, I wanted to add an easy way to generate some of those instances.
By settings `withObjectString` to `true` on your `fc.object` arbitraries you'll be able to get strings looking as objects more often (as values but also as keys).
No impact expected as the feature has been added as a flag.
We might find ways to put such flag as the default in the future.
=> Generate string representations of JS objects in fc.object/fc.anything

CONTRIBUTORS.md, src/check/arbitrary/ObjectArbitrary.ts, test/unit/check/arbitrary/ObjectArbitrary.spec.ts, test/unit/utils/stringify.spec.ts
closes #435 
I only changed the exported definitions signatures in `object` arbitrary to use `unknown` instead of `any`. I believe there might be other instances where this change could be done (I didn't check yet), this could be a first step
❌ New feature
Typings impact
This might be breaking for some users, but for the better 😎
=> any -> unknown in exported signatures for object/anything arbitraries

package.json
This flag can be used by webpack to enable tree-shaking on the module.
See https://webpack.js.org/guides/tree-shaking/
✔️ New feature
❌ Fix an issue
None.
=> Set "sideEffects" to `false` into package.json

.eslintrc.js, src/check/arbitrary/LetRecArbitrary.ts, src/check/arbitrary/MemoArbitrary.ts, src/check/arbitrary/OptionArbitrary.ts, src/check/runner/Sampler.ts, test/unit/check/arbitrary/RecordArbitrary.spec.ts
Replace `obj.hasOwnProperty(propertyName)`by `Object.prototype.hasOwnProperty.call(obj, propertyName)` in order to fix errors raised by [eslint no-prototype-builtins](https://eslint.org/docs/rules/no-prototype-builtins)
❌ New feature
None.
=> 🚨 Fix eslint errors related to no-prototype-builtins

test/unit/check/arbitrary/DateArbitrary.utest.spec.ts, test/unit/check/arbitrary/MixedCaseArbitrary.utest.spec.ts, test/unit/check/arbitrary/UuidArbitrary.utest.spec.ts, test/unit/check/arbitrary/generic/MockedModule.ts
Use ts-jest/utils mocked instead of our own.
❌ New feature
❌ Fix an issue
✔️ Other: Test
None.
=> :white_check_mark: Use ts-jest/utils mocked instead of our own

src/check/arbitrary/ObjectArbitrary.ts, test/unit/check/arbitrary/ObjectArbitrary.spec.ts
Fixes wrongly defined typings for `fc.object`
Fixes #458
Regression introduced by #436 
❌ New feature
Typings on `fc.object`
=> :ambulance: Fix typing regression on object introduced by #436

.travis.yml, example/async-property/test.ts, example/binary-trees/arbitraries/BinarySearchTreeArbitrary.ts, example/binary-trees/arbitraries/BinaryTreeArbitrary.ts, example/binary-trees/arbitraries/FullBinaryTreeArbitrary.ts, example/binary-trees/arbitraries/PerfectBinaryTreeArbitrary.ts, example/binary-trees/test.ts, example/model-based-testing/test.ts, example/package.json, example/run.sh, example/yarn.lock
In order to make it possible to run tests defined within example/ directory directly in codesandbox, we first have to make them use a published version of fast-check and change it during our tests to test the code against the on-going version.
❌ New feature
❌ Fix an issue
✔️ Other: *tests within example/*
None.
=> ✅  By default tests within example/ run against published fast-check 

src/check/property/AsyncProperty.generic.ts, src/check/property/AsyncProperty.ts, src/check/property/IProperty.ts, src/check/property/IRawProperty.ts, src/check/property/Property.generic.ts, src/check/property/Property.ts, src/check/property/SkipAfterProperty.ts, src/check/property/TimeoutProperty.ts, src/check/property/UnbiasedProperty.ts, src/check/runner/DecorateProperty.ts, src/check/runner/Runner.ts, src/check/runner/Sampler.ts, src/check/runner/Tosser.ts, src/fast-check-default.ts, test/unit/check/property/SkipAfterProperty.spec.ts, test/unit/check/property/TimeoutProperty.utest.spec.ts, test/unit/check/property/UnbiasedProperty.spec.ts, test/unit/check/runner/DecorateProperty.spec.ts, test/unit/check/runner/Runner.spec.ts, test/unit/check/runner/Tosser.spec.ts
Adapt and expose `IRawProperty`, `IProperty` and `IAsyncProperty` types.
Related to #461
✔️ New feature
No impact expected *BUT* internal changes:
- `fc.assert` and `fc.check` have been adapted to rely on `IRawProperty`, `IProperty` and `IAsyncProperty` instead of `Property`* or `AsyncProperty`* to guess its signature BUT no impact is expected
- `IProperty<Ts>`* has been renamed and updated `IRawProperty<Ts, IsAsync>`
- Two new interfaces for properties `IProperty` and `IAsyncProperty` - simple syntaxic sugar over `IRawProperty`
\* `Property` internal implementation for `fc.property` - implements newly created `IProperty`
\* `AsyncProperty` internal implementation for `fc.asyncProperty` - implements …
=> 🏷️ Adapt and expose IRawProperty, IProperty and IAsyncProperty types

test/e2e/SkipAllAfterTime.spec.ts, test/unit/check/arbitrary/ArrayArbitrary.spec.ts, test/unit/check/arbitrary/DateArbitrary.utest.spec.ts, test/unit/check/arbitrary/LetRecArbitrary.spec.ts, test/unit/check/arbitrary/MixedCaseArbitrary.utest.spec.ts, test/unit/check/arbitrary/ObjectArbitrary.spec.ts, test/unit/check/arbitrary/OneOfArbitrary.spec.ts, test/unit/check/arbitrary/OptionArbitrary.spec.ts, test/unit/check/arbitrary/UuidArbitrary.utest.spec.ts, test/unit/check/arbitrary/definition/Arbitrary.spec.ts, test/unit/check/arbitrary/definition/ArbitraryWithShrink.spec.ts, test/unit/check/arbitrary/generic/GenericArbitraryHelper.ts, test/unit/check/model/ModelRunner.spec.ts, test/unit/check/model/commands/CommandWrapper.spec.ts, test/unit/check/model/commands/CommandsIterable.spec.ts, test/unit/check/property/AsyncProperty.spec.ts, test/unit/check/property/Property.spec.ts, test/unit/check/property/TimeoutProperty.utest.spec.ts, test/unit/check/runner/Runner.spec.ts, test/unit/check/runner/Sampler.spec.ts, test/unit/stream/Stream.spec.ts, test/unit/stubs/arbitraries.ts
Related #448
❌ New feature
❌ Fix an issue
✔️ Other: *cleaning*
None.
=> 🚨 Clean unused variables in units

example/003-misc/roman/src/roman.ts
CodeSandbox is using an older version of TypeScript that does not allow to use `as const`
❌ New feature
None.
=> Fix example/003-misc/roman for CodeSandbox

.npmignore
📦 Remove all *.tsbuildinfo files from the bundle
❌ New feature
❌ Fix an issue
✔️ Other: *decrease bundle size*
None.
=> 📦 Remove all *.tsbuildinfo files from the bundle

.travis.yml
Run the CI STEP=HEAD against the latest node
❌ New feature
❌ Fix an issue
✔️ Other: *run the CI STEP=HEAD against the latest node*
None.
=> 👷 Use the latest version of node for STEP=HEAD

src/check/property/AsyncProperty.generic.ts, src/check/property/Property.generic.ts, test/type/main.ts
Closes #480
✔️ New feature
Should be a non-breaking change, since the type is looser than it was before.
=> Allow looser return types for AsyncProperty beforeEach and afterEach

README.md
Fixes #502
❌ New feature
❌ Fix an issue
N/A
=> Include note about using expect or assert

test/e2e/NoStackOverflowOnShrink.spec.ts
Related to #499
This commit confirms that a well-defined shrinker should never run into stack overflows during shrinking process. Meanwhile some shrinking algorithms like the one for arrays seem to be broken and will need some updates.
❌ New feature
❌ Fix an issue
None.
=> Check no stack overflow on shrink

src/check/arbitrary/LetRecArbitrary.ts, test/unit/check/arbitrary/LetRecArbitrary.spec.ts
Fixes #483
❌ New feature
None.
=> 🐛 Cache used in `letrec` does not come empty

src/check/arbitrary/LetRecArbitrary.ts
Fixes bug introduced in #509
❌ New feature
None.
=> 🐛 Fix letrec bug when __proto__ set to null

README.md
Better example of bug discovered by fast-check
❌ New feature
❌ Fix an issue
None.
=> ✏️ Add Jest example directly on the README

.eslintignore, .npmignore
Add missing references to lib-old in .*ignore configs
Directory lib-old was not ignored from some configurations.
❌ New feature
❌ Fix an issue
✔️ Other: *build config*
None.
=> 🔧 Add missing references to lib-old in .*ignore configs

documentation/1-Guides/Arbitraries.md
"Combinors" => "Combinators"
Drop "of arbitraries" - these are arbitrary combinators in the Arbitraries docs, so just "Combinators"
❌ New feature
❌ Fix an issue
✔️Documentation improvement
=> ✏️ Tweak & fix typo in Arbitraries.md

test/unit/check/arbitrary/generic/GenericArbitraryHelper.ts
Enhance isValidArbitrary helper
❌ New feature
❌ Fix an issue
None.
=> ✅ Enhance isValidArbitrary helper

src/check/arbitrary/HostArbitrary.ts, src/check/arbitrary/WebArbitrary.ts, test/e2e/arbitraries/WebArbitrary.spec.ts, test/unit/check/arbitrary/WebArbitrary.spec.ts
Another way to fix #532 
Previous way was #536 but it seems better to have not internationalized domains by default for the moment. If one day, we add the support for internationalized domains we might want to also add badly internationalized ones.
❌ New feature
Generated values impact might rarely be impacted.
The probability to generate one of the filtered values is:
(1 / 36) * (4 / 5) * (1 / 37) * (1 / 37) * (1 / 37) = 0.00004387 %
=> ✨ Do not generate internationalized domains

src/check/model/commands/CommandsArbitrary.ts, test/e2e/NoStackOverflowOnShrink.spec.ts
Shrink of large arrays of commands was causing crashes of fast-check.
As we did for `array` and `shuffledSubarray` in #505, we fixed the shrinker of `commands` so that it can be executed on large arrays of commands without running into stack overflows or other crashes.
Related to #499
Fixes #508
❌ New feature
None.
Shrinker keeps shrinking towards the same values. We just tend to limit the stack size required to do it, and limit as much as possible every unneeded computations.
=> 🐛 Stack overflows while shrinking large arrays of commands

test/unit/check/arbitrary/LetRecArbitrary.spec.ts
Clean unit test
❌ New feature
❌ Fix an issue
✔️ Other: *clean unit test*
None
=> ✅ NIT Clean typos in letrec unit tests

src/utils/stringify.ts, test/unit/utils/stringify.spec.ts
Fixes #507
✔️ New feature
❌ Fix an issue
Might impact the value produced by `fc.stringify`, helper used internally to get stringified value of any object
=> ✨ Stringify should distinguish `{}` from `Object.create(null)`

example/005-race/counter/main.spec.ts, example/005-race/counter/src/CasCounter.ts, example/005-race/counter/src/Counter.ts, example/005-race/counter/src/DbConnection.ts, example/005-race/counter/src/SynchronizedCounter.ts, example/README.md, example/yarn.lock
Adding an example for race conditions in the documentation.
❌ New feature
❌ Fix an issue
None.
=> 📝 Add an example on atomic Counter for race conditions feature

src/check/arbitrary/OptionArbitrary.ts, src/check/arbitrary/definition/Arbitrary.ts, src/check/arbitrary/definition/Shrinkable.ts, src/stream/Stream.ts, src/stream/StreamHelpers.ts, test/type/index.test-d.ts, test/unit/check/runner/Runner.spec.ts
Support type guards while filtering
Fixes #545
✔️ New feature
❌ Fix an issue
None expecting. We need to confirm it will not break any existing typings.
=> ✨ Support type guards while filtering

documentation/1-Guides/Arbitraries.md
Better document how race conditions can be detected
Fixes #563
Fixes #564
❌ New feature
❌ Fix an issue
None.
=> ✏️ Better document how race conditions can be detected

src/check/arbitrary/ObjectArbitrary.ts
The code of `fc.object()` was trying to spread an `Arbitrary`, which is a totally illegal operation. Transpilation may have covered the bug...
❌ New feature
None. Fixes a potential bug :)
=> 🐛 Fix `fc.object()` with withNullPrototype

documentation/1-Guides/AdvancedArbitraries.md, documentation/1-Guides/Tips.md
A few of the links in the documentation to example custom arbitraries were broken by ffa7dac. This PR updates those links to the new location of the examples.
❌ New feature
❌ Fix an issue
No potential negative impacts are foreseen.
=> Fix broken links in documentation

src/check/arbitrary/RecordArbitrary.ts
Remove support for previously depreciated parameter in fc.record.
❌ New feature
❌ Fix an issue
✔️ Other: *remove depreciated feature*
Remove depreciated feature.
All references to `with_deleted_keys` should changed into `withDeletedKeys`.
=> 💥 Remove support for `with_deleted_keys` on `fc.record`

package.json, test/esm/node-with-import/main.js, test/esm/node-with-require/main.js, test/esm/rollup-with-import/main.js, test/esm/rollup-with-require/main.js, test/esm/webpack-with-import/main.js, test/esm/webpack-with-require/main.js, yarn.lock
Current checks on cjs+esm build do not confirm that fats-check can be used properly.
They only confirm that the resulting bundle can be opened and that basic metadata exposed by fast-check are accessible.
The current PR adds checks to confirm that user can run basic properties. It mostly checks that fast-check uses correct dependencies (compatible with the settings of the user).
It may actually require to bump pure-rand. So that can be considered as 'fix an issue'.
❌ New feature
None.
=> ✅ Check that fast-check's users can run properties with cjs+esm build

package.json
Bundlers such as rollup or webpack are often preferred nowadays.
Otherwise some services offer mirrors with the bundles ready for use in browsers:
- pika
- bundle.run
❌ New feature
❌ Fix an issue
✔️ Other: *remove browser version*
No more browser version
=> 💥 Remove pre-packaged version for browser

example/001-simple/fibonacci/main.spec.ts, example/001-simple/fibonacci/src/fibonacci.ts, example/README.md, example/tsconfig.json
Add an example based on Fibonacci
❌ New feature
❌ Fix an issue
None
=> 📝 Add an example based on Fibonacci

example/005-race/debounced-autocomplete/main.spec.tsx, example/005-race/debounced-autocomplete/src/Api.ts, example/005-race/debounced-autocomplete/src/DebouncedAutocomplete.tsx, example/README.md, example/package.json, example/yarn.lock
Add an example showing how to test race conditions with timers
❌ New feature
❌ Fix an issue
None
=> 📝 Add an example showing how to test race conditions with timers

src/check/arbitrary/ConstantArbitrary.ts, src/check/arbitrary/helpers/ArrayHelper.ts, test/unit/check/arbitrary/helpers/ArrayHelper.spec.ts
This allows us to avoid using Array.prototype.find,
which is not available on Internet Explorer 11.
Addresses issue #582
❌ New feature
✔️/❌ Fix an issue
Slightly larger code size, slightly longer testing time.
=> Add findOrUndefined function.

test/esm/node-extension-cjs/package.json, test/esm/node-extension-mjs/package.json, test/esm/node-with-import/package.json, test/esm/node-with-require/package.json, test/esm/rollup-with-import/package.json, test/esm/rollup-with-require/package.json, test/esm/webpack-with-import/package.json, test/esm/webpack-with-require/package.json
Add missing `"private": true` on package.json used for tests
❌ New feature
❌ Fix an issue
✔️ Other: *package.json with private:true*
None.
=> 🔧 Add missing `"private": true` on package.json used for tests

example/005-race/autocomplete/main.spec.tsx, example/005-race/autocomplete/src/AutocompleteField.tsx, example/005-race/autocomplete/src/AutocompleteFieldMostRecentQuery.tsx, example/005-race/autocomplete/src/AutocompleteFieldSimple.tsx, example/005-race/debounced-autocomplete/src/DebouncedAutocomplete.tsx
Clean examples based on getByRole
❌ New feature
❌ Fix an issue
None
=> ✅ Clean examples based on getByRole

.travis.yml, test/esm/run.sh
Now that node 12 has been unflagged and support ES Modules out-of-the-box, we need to ensure it will work correctly with fast-check.
For holder releases (<12.18) and new ones (>=12.18)
❌ New feature
❌ Fix an issue
✔️ Other: *CI for CommonJS and ESM checks*
None
=> 💚 Check compatibility with node 12.x and >= 12.18

documentation/1-Guides/Arbitraries.md, src/check/arbitrary/AsyncSchedulerArbitrary.ts, src/fast-check-default.ts, test/unit/check/model/commands/ScheduledCommand.spec.ts
Introduce a report method on the scheduler
✔️ New feature
❌ Fix an issue
Nothing expected. Changes in the typings of the scheduler should be backward compatible.
Output for `toString` on a Scheduler should be unchanged.
=> ✨ Introduce a report method on the scheduler

src/check/arbitrary/DictionaryArbitrary.ts, src/check/arbitrary/ObjectArbitrary.ts
Better typings for `fc.object` and `fc.dictionnary`
❌ New feature
- Typings impact: risk minor - no regression expected neither for object nor for dictionary
=> 🏷️ Better typings for `fc.object` and `fc.dictionnary`

documentation/1-Guides/Tips.md
A section was treated as a code block due to a duplicate closing marker.
This PR fixes a simple markdown problem.
❌ New feature
❌ Fix an issue
Suitably rendered documentation ;)
=> Fix markdown section

src/check/arbitrary/EmailArbitrary.ts, src/check/arbitrary/HostArbitrary.ts, src/check/arbitrary/WebArbitrary.ts
The errors were reported by @typescript-eslint/explicit-module-boundary-types as warnings. Unfortunately enabling them would ask to add several missing typings that may not be really needed.
The rule could be added only for the real source code by adding the following into `.eslintrc.cjs` file:
```
overrides: [
{
files: ['src/**/*.ts'],
rules: {
'@typescript-eslint/explicit-module-boundary-types': ['error', { allowArgumentsExplicitlyTypedAsAny: true }],
},
},
],
```
❌ New feature
❌ Fix an issue
✔️ Other: *fix build issue*
None.
=> 💚 Generated typings where causing the doc generation to crash

documentation/1-Guides/Runners.md, src/check/runner/Runner.ts, src/check/runner/configuration/QualifiedParameters.ts, src/check/runner/reporter/RunDetails.ts, src/check/runner/reporter/RunExecution.ts, test/unit/check/runner/reporter/RunExecution.spec.ts
Report the configuration, that has been used, in RunDetails
✔️ New feature
❌ Fix an issue
None.
=> ✨ Report the configuration, that has been used, in RunDetails

src/check/arbitrary/AsyncSchedulerArbitrary.ts, test/unit/check/arbitrary/AsyncSchedulerArbitrary.spec.ts
FIX Scheduler forgets to pass the metadata when calling report.
❌ New feature
None.
=> 🐛 FIX Scheduler forgets to pass the metadata when calling report

test/e2e/AsyncScheduler.spec.ts
The E2E tests written for `AsyncScheduler` were relying on changing data. They failed as soon as we updated the targeted versions of node, ts... (see [branch next-1_25_1](https://github.com/dubzzz/fast-check/tree/next-1_25_1))
See:
```
Received: 1
at propertyValidator (C:\dev\fast-check\test\e2e\AsyncScheduler.spec.ts:152:21)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at AsyncProperty.run (C:\dev\fast-check\src\check\property\AsyncProperty.generic.ts:31:22)
at asyncRunIt (C:\dev\fast-check\src\check\runner\Runner.ts:44:17)
-     at Object.<anonymous> (C:\dev\fast-check\test\e2e\AsyncScheduler.spec.ts:155:17)
+     at Object.<anonymous> (C:\dev\fast-check\test\e2e\AsyncScheduler.spec.ts:169:22)
```
❌ New feature
❌ Other: …
=> ✅ E2E for AsyncScheduler were relying on changing data

documentation/1-Guides/Arbitraries.md, src/check/arbitrary/FalsyArbitrary.ts, src/fast-check-default.ts, test/unit/check/arbitrary/FalsyArbitrary.spec.ts
Adding a `falsy` arbitrary as per #624 
✔️ New feature
NA
=> feat(falsy arbitrary): add arbitrary, tests, and docs

test/unit/check/runner/configuration/QualifiedParameters.spec.ts
Add missing parameters in QualifiedParameters tests.
❌ New feature
❌ Fix an issue
None.
=> ✅ Add missing parameters in QualifiedParameters tests

package.json, yarn.lock
Issue #626 
This script, defined in the root package.json, makes use of mkdir -p which is not working on Windows. We should replace it by the npm package mkdirp
https://github.com/dubzzz/fast-check/issues/626
❌ New feature
=> Update script to an nmp package for compatibility on with windows: mkdir -p --> mkdirp (#626).

src/check/arbitrary/ConstantArbitrary.ts, test/type/index.test-d.ts
**WARNING**
It introduces a breaking change in the typings:
`fc.constantFrom<T>` should be updated into `fc.constantFrom<T[]>`
✔️ New feature
Typings impact
=> 💥✨ Improve typings for `fc.constantFrom`

documentation/1-Guides/AdvancedArbitraries.md
I think linking to the comment will be good for future readers if they care for more details
fix #650
=> Add note on chain shrink issues

test/esm/rollup-with-import/buildRollupConfig.js, test/esm/rollup-with-import/dry-import.js, test/esm/rollup-with-import/dry.js, test/esm/rollup-with-import/package.json, test/esm/rollup-with-import/yarn.lock, test/esm/rollup-with-require/buildRollupConfig.js, test/esm/rollup-with-require/dry-import.js, test/esm/rollup-with-require/dry.js, test/esm/rollup-with-require/package.json, test/esm/rollup-with-require/yarn.lock, test/esm/webpack-with-import/yarn.lock, test/esm/webpack-with-require/yarn.lock
Following alerts opened by Dependabot
- run: yarn upgrade
- remove unused dependencies
It should fix:
```
GitHub found 3 vulnerabilities on dubzzz/fast-check's default branch (1 high, 2 moderate). To find out more, visit:
https://github.com/dubzzz/fast-check/network/alerts
```
❌ New feature
❌ Fix an issue
✔️ Other: *bump*
None
=> ⬆️ Bump some dependencies in test/esm

.travis.yml
HEAD was initially responsible to check for future regressions introduced by libraries.
Now that dependabot bumps libraries for us, this is needed anymore.
The only thing we will lose if that it was also checking that fast-check will still work with latest revisions of node. Actually it should not be a real issue...
❌ New feature
❌ Fix an issue
✔️ Other: *ci*
None
=> 👷 Remove useless CI stage (HEAD)

documentation/1-Guides/Arbitraries.md, src/check/arbitrary/ObjectArbitrary.ts, test/e2e/GenerateAllValues.spec.ts, test/unit/check/arbitrary/ObjectArbitrary.spec.ts, test/unit/utils/stringify.spec.ts
Fixes #629
✔️ New feature
❌ Fix an issue
None
=> ✨ Add `withBigInt` constraint on `fc.anything`

.travis.yml
Add `--frozen-lockfile` when calling `yarn`
❌ New feature
❌ Fix an issue
✔️ Other: *CI*
None
=> 💚 Add `--frozen-lockfile` when calling `yarn`

src/check/arbitrary/RecordArbitrary.ts
**Merge of PR #570 to master**
---
Remove support for previously depreciated parameter in fc.record.
❌ New feature
❌ Fix an issue
✔️ Other: *remove depreciated feature*
Remove depreciated feature.
All references to `with_deleted_keys` should changed into `withDeletedKeys`.
=> 💥 Remove support for with_deleted_keys on fc.record

package.json, yarn.lock
Bumping pure-rand to its latest major. This major is compatible with both commonjs and es modules.
❌ New feature
❌ Fix an issue
✔️ Other: *dependencies*
Starting at version 3.0.0, pure-rand publishes an hybrid version of the package that should be compatible with both commonjs and es module. Nonetheless as the change might have unseen side-effects, it can still be considered as potentially dangerous.
=> (💥)⬆️ Bump pure-rand to its latest major version

.eslintrc.cjs, src/check/arbitrary/ObjectArbitrary.ts, test/unit/check/arbitrary/ObjectArbitrary.spec.ts
**Merge of PR #631 to master**
---
Update `ObjectConstraints`
❌ New feature
Typings impact
=> 💥 Get rid of old namespace syntax for ObjectArbitrary

.travis.yml, package.json, test/legacy/main.js, yarn.lock
Bump jest to version 26.1
❌ New feature
❌ Fix an issue
✔️ Other: *dependencies*
None
=> ⬆️ Bump jest to version 26.1

MIGRATION_1.X_TO_2.X.md
It fixes small typos in v2 migration guide
❌ New feature
❌ Fix an issue
=> Fix typos in migration guide

test/unit/check/arbitrary/ObjectArbitrary.spec.ts
Coverage reported by the CI was flaky due to one line of code that was not always covered*
*Our test suite is using PBT as a consequence tests may vary from one run to another. But ideally we should still cover the same set of lines.
❌ New feature
❌ Fix an issue
✔️ Other: *CI builds were flaky*
None
=> 💚 Reduce flakiness of tests regarding coverage

src/check/arbitrary/ObjectArbitrary.ts
❌ New feature
❌ Fix an issue
✔️ Other: *code cleaning*
None.
=> 🚨 Remove usages of `!` operator in ObjectArbitrary

src/check/arbitrary/FunctionArbitrary.ts, src/check/arbitrary/helpers/TextEscaper.ts, test/e2e/__snapshots__/NoRegression.spec.ts.snap, test/e2e/arbitraries/FunctionArbitrary.spec.ts, test/unit/check/arbitrary/FunctionArbitrary.spec.ts, test/unit/check/arbitrary/helpers/TextEscaper.spec.ts
✔️ New feature
❌ Fix an issue
Error reported by `func`, `compareFunc` and `compareBooleanFunc` has been updated. Code relying on the output of `toString` for one of those arbitraries has to be updated
=> ✨ Report a valid `function` on `func` and `compareFunc`

.github/dependabot.yml, example/yarn.lock, test/esm/node-extension-cjs/yarn.lock, test/esm/node-extension-mjs/yarn.lock, test/esm/node-with-import/yarn.lock, test/esm/node-with-require/yarn.lock, test/esm/rollup-with-import/yarn.lock, test/esm/rollup-with-require/yarn.lock, test/esm/webpack-with-import/yarn.lock, test/esm/webpack-with-require/yarn.lock, test/legacy/typescript-3.2/yarn.lock, test/type/yarn.lock
Each time we published a new version of fast-check, dependabot was opening 9 PRs.
Most of them were unneeded as they target internal tests that always link against a local build of fast-check.
❌ New feature
❌ Fix an issue
✔️ Other: *dependabot*
None
=> 👷 Ignore fast-check bumps for some directories

test/unit/check/model/ReplayPath.spec.ts
Fix #849
❌ New feature
❌ Fix an issue
✔️ Other: *coverage flaky*
None
=> 💚 Reduce coverage flakiness on `ReplayPath.ts`

.github/dependabot.yml
Slow down dependabot frequency.
Dependabot was opening several commits per day related to changes occuring in react-testing-library most of the time (or rollup). As it create unnecessary changes, I prefer stacking those changes once a month for the example/ directory and once a week for all the projects defined in test/.
❌ New feature
❌ Fix an issue
✔️ Other: *ci*
None
=> 👷 Slow down dependabot frequency

.travis.yml
Remove unneeded before_install step on .travis.yml
❌ New feature
❌ Fix an issue
✔️ Other: *ci*
None
=> 👷 Remove unneeded before_install step on .travis.yml

src/fast-check-default.ts
Publish missing constraints types (option, scheduler)
❌ New feature
❌ Fix an issue
✔️ Other: *types*
None
=> 🏷️ Publish missing constraints types (option, scheduler)

prebuild/property.cjs, src/check/property/AsyncProperty.generic.ts, src/check/property/AsyncProperty.ts, src/check/property/Property.generic.ts, src/check/property/Property.ts, src/fast-check-default.ts
Add an interface to better type (Async)Property
❌ New feature
❌ Fix an issue
✔️ Other: *types*
No real breaking change or problem expected. `fc.property` now returns (typing) a `IPropertyWithHooks` while it used to return a `Property` (this is and was an internal class not supposed to be imported by users).
=> 🏷️ Add an interface to better type (Async)Property

package.json
```sh
yarn docs
yarn docs:serve  # <-- new script that makes devs able to check the generated doc locally
```
❌ New feature
❌ Fix an issue
✔️ Other: *add script*
None
=> 🔨 Add script to serve the generated documentation locally

src/check/runner/Runner.ts, test/unit/check/runner/Runner.spec.ts
A typo introduced into the codebase made users unable to to use the `asyncReporter` with asynchronous properties... but not with synchronous ones.
❌ New feature
If users set an `asyncReporter` onto a synchronous properties the code will fails now (but actually, not failing was a mistake).
=> 🐛 Asynchrorous properties should be able to use `asyncReporter`

src/check/arbitrary/AsyncSchedulerArbitrary.ts, src/check/arbitrary/ContextArbitrary.ts, src/check/arbitrary/MemoArbitrary.ts, src/check/arbitrary/ObjectArbitrary.ts, src/check/model/ModelRunner.ts, src/check/precondition/Pre.ts, src/check/runner/configuration/GlobalParameters.ts, src/check/runner/reporter/RunDetails.ts, src/fast-check-default.ts
In the context of the documentation extracted by api-extractor, it is better to have:
```ts
interface MyType {
/** What does my attribute */
attribute: any;
}
```
Over:
```ts
type MyType = {
/** What does my attribute */
attribute: any;
};
```
As the documentation related to the attribute will be ignored.
Same for functions versus variables.
Declaring a function as follow:
```ts
function abc() {}
```
Will produce a better extracted api than this one:
```ts
const abc = () => {}
```
❌ New feature
❌ Fix an issue
None
=> 📝 Prefer interfaces and functions for exported entities

src/check/arbitrary/AsyncSchedulerArbitrary.ts, src/check/runner/configuration/GlobalParameters.ts
Fix examples leaking in to functions table
Some examples weren't marked as such and were leaking in to the table of functions in the documentation.
❌ New feature
=> Fix examples leaking in to functions table

src/check/arbitrary/HostArbitrary.ts, test/unit/check/arbitrary/HostArbitrary.spec.ts
Fixes #857
❌ New feature
❌ Fix an issue
None
=> 💚 Reduce coverage flakiness on `HostArbitrary.ts`

src/check/arbitrary/DateArbitrary.ts
Quick fix where using `fc.date({ max: new Date('asdf') })` would hang.
Side question: why does it hang? Should `fc.integer()` check if the bounds are `NaN` and error accordingly?
❌ New feature
=> Fix NaN passed to max in fc.date()

README.md
❌ New feature
❌ Fix an issue
None
=> ✏️ Mark TypeScript as an optional requirement in the README

package.json, src/utils/stringify.ts, test/unit/utils/stringify.spec.ts, yarn.lock
Fixes #910
✔️ New feature
❌ Fix an issue
None
=> ✨ Stringify typed arrays and buffers

codemods/2.4.0_explicit-min-max-length/README.md, codemods/2.4.0_explicit-min-max-length/snippet-3.js, codemods/2.4.0_explicit-min-max-length/snippet-4.ts, codemods/2.4.0_explicit-min-max-length/transform.cjs
Add some additional options onto the codemod used to migrate away from `fc.array(arb, maxLength)` and `fc.array(arb, minLength, maxLength)`.
It now provides two custom flags not to put `minLength` and/or `maxLength` if they do not make sense (in other words, if the value is 0 for min or 10 for max).
`fc.array(arb, 10)` -> `fc.array(arb)` when toggling that option (instead of `fc.array(arb, {maxLength: 10})`)
`fc.array(arb, 0, 10)` -> `fc.array(arb)` when toggling that option (instead of `fc.array(arb, {minLength: 0, maxLength: 10})`)
✔️ New feature
❌ Fix an issue
None
=> ✨ Automatically simplify min and max in codemod for arrays

.prettierignore
❌ New feature
❌ Fix an issue
✔️ Other: *configuration file*
None
=> 🔧 Fix .prettierignore not ignoring files correctly

codemods/2.4.0_explicit-min-max-length/README.md, documentation/Arbitraries.md, src/check/arbitrary/ArrayArbitrary.ts, src/check/arbitrary/SetArbitrary.ts
For the moment, instead of explicitely depreciating the overloads for `fc.array`, `fc.set` and more to come. We only mark them as non-recommended.
Two subjects still need to be discussed before going for depreciated flag, see #992 for more details.
❌ New feature
None, not released yet
=> ⏪ Do not depreciate overloads for array-like (yet)

codemods/2.4.0_explicit-min-max-length/snippet-5.js, codemods/2.4.0_explicit-min-max-length/snippet-6.js, codemods/2.4.0_explicit-min-max-length/transform.cjs, documentation/Arbitraries.md, src/check/arbitrary/SubarrayArbitrary.ts, src/fast-check-default.ts, test/unit/check/arbitrary/SubarrayArbitrary.spec.ts
Add support for the unified new signatures of arbitraries on subarray-based arbitraries.
Related to #89 and #992
✔️ New feature
❌ Fix an issue
None.
=> ✨ Move to explicit `minLength`/`maxLength` constraints on `subarray`

test/e2e/documentation/Docs.md.spec.ts
❌ New feature
❌ Fix an issue
None
=> 🐛 Script update:examples should not fail on updates

codemods/unify-signatures/snippet-5.js, codemods/unify-signatures/transform.cjs, documentation/Arbitraries.md, src/check/arbitrary/ObjectArbitrary.ts, src/fast-check-default.ts
Unify signatures on arbitraries: fc.json, fc.jsonObject, fc.unicodeJson, fc.unicodeJsonObject (see [#992](https://github.com/dubzzz/fast-check/issues/992))
✔️ New feature
❌ Fix an issue
None
=> ✨ Add constraints-based signature for json/jsonObject

src/check/arbitrary/EmailArbitrary.ts, test/unit/check/arbitrary/EmailArbitrary.spec.ts
Safer email generation: we now ensures by using a filter that the size will never be outside of the authorized range.
The previous implementation was already safe we just make it even safer in case we refactor it in the future.
Fixes #1008
❌ New feature
❌ Fix an issue
None
=> 🎨 Stricter limits on email arbitrary

src/check/arbitrary/DateArbitrary.ts
Related to #1109
It might not fix the problem reported by the issue but the approach to apply constraints will be safer. 
❌ New feature
None
=> 🐛 Constraints on `fc.date` might be wrongly applied

documentation/HandsOnPropertyBased.md, jest.config.cjs
```txt
ts-jest[config] (WARN) The option `tsConfig` is deprecated and will be removed in ts-jest 27, use `tsconfig` instead
```
❌ New feature
❌ Fix an issue
✔️ Other: *config*
None
=> 🔧 Clean warnings related to ts-jest

src/check/arbitrary/RecordArbitrary.ts, test/type/index.test-d.ts
Fixes #1141
❌ New feature
Typings impact on `fc.record`
=> 🐛🏷️ Fix wrongly typed fc.record(recordModel)

.github/workflows/build-status.yml, package.json, postbuild/main.cjs, src/fast-check-default.ts
Commit hash related to the package can be accessed with: `fc.__commitHash`
✔️ New feature
❌ Fix an issue
None
=> ✨ Add commit hash into the generated package

src/check/arbitrary/BigIntArbitrary.ts, src/check/arbitrary/IntegerArbitrary.ts, src/check/arbitrary/helpers/BiasNumeric.ts, test/unit/check/arbitrary/helpers/BiasNumeric.spec.ts
❌ New feature
❌ Fix an issue
None
=> ✅ Add tests for biasNumeric

test/unit/check/arbitrary/generic/GenericArbitraryHelper.ts
❌ New feature
❌ Fix an issue
✔️ Other: *better tests helpers*
None
=> ✅ Pass the original `seed` to callbacks of `isValidArbitrary`

test/unit/check/arbitrary/FloatNextArbitrary.spec.ts, test/unit/check/arbitrary/generic/GenericArbitraryHelper.ts
❌ New feature
❌ Fix an issue
✔️ Other: *wrong test*
None
=> 💚 FIX Wrongly defined `isStrictlySmallerValue` for `floatNext`

src/check/arbitrary/FloatNextArbitrary.ts, test/unit/check/arbitrary/FloatNextArbitrary.spec.ts
Before that change shrinking a value generated by floatNext could have produced NaN.
In reality NaN should be considered as one of the extreme values (after the max or after the min but never the closer from zero).
It is more an enhancement than a new feature.
✔️ New feature
❌ Fix an issue
None, the feature has not been released yet.
=> ✨ Move NaN as an extreme value for floatNext

test/unit/check/arbitrary/FloatNextArbitrary.spec.ts
In previous test when ct.max === 0 we were doing:
> Number.isNaN(fa) && !Number.isNaN(fb)
In such configuration we expect:
[NaN, 0] with index=-1 for NaN and index=0 for 0
Actually NaN should always be considered greater than others no matter the passed constraints. The only additional check we could do is: check that the value of fa has the right sign or is +0 but it does not bring lots of value.
❌ New feature
❌ Fix an issue
✔️ Other: *badly written test*
None
=> 💚 FIX Wrongly expressed isStrictlySmallerValue in floatNext

test/unit/check/arbitrary/FloatNextArbitrary.spec.ts
Fixes #1198
❌ New feature
❌ Fix an issue
✔️ Other: *green ci*
None
=> 💚 Spec. for `fc.float(Next)` was not doing the right checks to compare zeros

src/check/arbitrary/FloatNextArbitrary.ts, test/unit/check/arbitrary/FloatNextArbitrary.itest.spec.ts, test/unit/check/arbitrary/FloatNextArbitrary.utest.spec.ts, test/unit/check/arbitrary/generic/FloatingPointHelpers.ts
❌ New feature
❌ Fix an issue
✔️ Other: *coverage*
None
=> ✅ More stable coverage for floatNext

test/unit/check/arbitrary/ObjectArbitrary.spec.ts
❌ New feature
❌ Fix an issue
✔️ Other: *fix ci build*
None
=> 💚 FIX Wrongly defined test: Should box any number

test/e2e/arbitraries/WebArbitrary.spec.ts
Fixes #1235
❌ New feature
❌ Fix an issue
✔️ Other: *wrong test*
None
=> 💚 Safer URL validation in our web urls e2e tests

src/check/arbitrary/definition/Arbitrary.ts
❌ New feature
❌ Fix an issue
✔️ Other: *performance*
Arbitraries in general.
=> ⚡️ Extract inlined-classes outside of Arbitrary base-class

src/check/arbitrary/RecordArbitrary.ts
> The Object.keys() method returns an array of a given object's own enumerable properties, in the same order as that provided by a for...in loop (the difference being that a for-in loop enumerates properties in the prototype chain as well).
_From https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/keys_
Very slight improvement expected as it will do less allocations. Measurements detected no major change.
❌ New feature
❌ Fix an issue
✔️ Other: *performance records*
Record
=> ⚡️ Switch from Object.keys to for..in in record

documentation/AdvancedArbitraries.md
=> typo `responsable` -> `responsible`

test/e2e/arbitraries/ArrayArbitrary.spec.ts
Increasing the number of runs from 5k to 10k is supposed to reduce the number of red runs. Actually the red runs are quite rare but as we run e2e 6 times per PR, it is better to have it greener. 
❌ New feature
❌ Fix an issue
=> 💚 Reduce flakiness of array e2e

.github/workflows/build-status.yml, package.json
Reports provided by coveralls are difficult to diagnose when some paths are randomly executed. They are said to be red while when we open the detailed view of the job everything appear to be green.
❌ New feature
❌ Fix an issue
✔️ Other: *coverage tooling*
None
=> 👷 Basic setup for codecov

.github/workflows/build-status.yml
For the moment, we don't use flags so much. So we limit them to the name of the job. We might add them back in the future of needed.
❌ New feature
❌ Fix an issue
✔️ Other: *code coverage*
None
=> 👷 Remove unused flags in coverage

src/check/precondition/PreconditionFailure.ts, src/check/runner/configuration/GlobalParameters.ts, src/check/symbols.ts, test/unit/check/precondition/Pre.spec.ts, test/unit/check/runner/configuration/GlobalParameters.spec.ts, test/unit/check/symbols.spec.ts
❌ New feature
❌ Fix an issue
✔️ Other: *refactoring*
Symbols changed but no problem expected except if you users are importing different versions of fast-check at the same time. In that case, symbols will differ between the versions.
=> 💬 Prefer unique symbols over `Symbol.for`

src/check/arbitrary/RecordArbitrary.ts, test/type/main.ts, test/unit/check/arbitrary/RecordArbitrary.spec.ts
Fixes #240
✔️ New feature
❌ Fix an issue
No real impact expected except that record will now accept models containing symbols as keys.
=> ✨ Add support for Symbol keys in record

documentation/Arbitraries.md, src/utils/stringify.ts, test/unit/utils/stringify.spec.ts
✔️ New feature
❌ Fix an issue
None
=> ✨ Properly handle objects with symbols as keys in `fc.stringify`

src/check/arbitrary/FloatingPointArbitrary.ts
Fixes #1341
❌ New feature
Generated values for legacy versions of float/double may change under very very rare circumstances (barely impossible).
=> 🐛 Legacy float/double should never reach the max specified value

src/check/arbitrary/definition/ArbitraryWithContextualShrink.ts, src/fast-check-default.ts
Why?
ArbitraryWithShrink do not provide enough details to the shrinker. Thus it leads to slow shrink scenarios as the only useful information we got on shrinker side is whether or not we already shrunk one.
The problem is that knowing whether we already shrunk or not is useful, but not enough to shrink in an efficient way. Thus we will introduce a new generation of shrinkers based on this more powerful helper.
✔️ New feature
❌ Fix an issue
None
=> ✨ Introduce new helper ArbitraryWithContextualShrink

src/check/arbitrary/definition/Arbitrary.ts
`Arbitrary.filter` can harm the performance of generations of values, and this is shown in [the advanced doc](https://github.com/dubzzz/fast-check/blob/master/documentation/AdvancedArbitraries.md#filter-values) but not in the code doc.
This is a very important and fundamental issue when use property based testing libraries so should be written in the code doc explicitly.
The doc content is borrowed from the advanced doc description.
❌ New feature
❌ Fix an issue
=> doc about filter performance

src/check/arbitrary/definition/ArbitraryWithContextualShrink.ts, test/unit/check/arbitrary/IntegerArbitrary.spec.ts
This potential regression has been introduced by #1355.
For the moment, we want to limit the impact on user still relying on legacy version of the shrinkers.
❌ New feature
✔️ Fix an issue: introduced by #1355 and not yet released
Avoid a potential regression for users relying on `shrinkableFor`.
=> 🐛 Calling `shrinkableFor` should never apply contextual shrinker

test/e2e/ComplexShrink.spec.ts
We want to ensure that our upcoming changes on shrinker side will not alter the quality of the shrinker offered by fast-check.
Those tests can be seen as non regression tests as they make sure that things we are able to shrink today will still be shrinkable in the future.
❌ New feature
❌ Fix an issue
None
=> ✅ Add non-regression tests on shrinking quality

src/check/arbitrary/ArrayArbitrary.ts, test/e2e/__snapshots__/NoRegression.spec.ts.snap
❌ New feature
❌ Fix an issue
✔️ Other: *faster shrinker*
Impacts on the shrinker of array and any derived arbitrary (including strings).
=> ⚡️ Re-use the context of integer during the shrink of an array

test/type/main.ts
Related to https://github.com/dubzzz/ava-fast-check/issues/14
❌ New feature
❌ Fix an issue
✔️ Other: *typings test*
None
=> ✅ Add test on typings for constantFrom and chain

src/utils/globalThis.ts, yarn.lock
The current implementation of getGlobal is not compatible with CSP (due to its use of `Function('return this')`).
=> Avoid using unsafe-eval in implementation of getGlobal

documentation/Arbitraries.md, src/check/arbitrary/ObjectArbitrary.ts, test/e2e/GenerateAllValues.spec.ts, test/unit/check/arbitrary/ObjectArbitrary.spec.ts, test/unit/utils/stringify.spec.ts
✔️ New feature
❌ Fix an issue
None
=> ✨ Add support for sparse arrays in `fc.object`

documentation/Arbitraries.md, src/check/arbitrary/ObjectArbitrary.ts
❌ New feature
Values generated by `fc.object` and `fc.anything` might change if you toggled `withTypedArray`
=> 🐛 Reduce bias towards typed arrays in `fc.object`

src/check/arbitrary/SparseArrayArbitrary.ts, test/unit/check/arbitrary/SparseArrayArbitrary.utest.spec.ts
When asked for:
- noTrailingHole: true
- maxNumElements: 0
- maxLength > 0
sparse arrays was producing an array of size 0 but requested it through a complex workflow passing through the generation of an empty set (sometimes and sometimes not).
We just factorize the two paths into a single one to avoid an unneeded special case.
❌ New feature
None
=> ♻️ No special case for sparse arrays without trailing holes and no elements

.github/workflows/build-status.yml, README.md
For the moment the support for flags is not perfect and lead to red builds first, then green as soon as unit-tests come back.
Additionally badge does not report the right coverage when filtered on flags.
❌ New feature
❌ Fix an issue
✔️ Other: *ci*
None
=> 👷 Stop sending e2e coverage into codecov

test/e2e/arbitraries/Arbitrary.spec.ts
❌ New feature
❌ Fix an issue
✔️ Other: *flaky ci*
None
=> 💚 Increase numRuns for bias e2e to limit flakiness

src/check/arbitrary/helpers/ArrayInt64.ts, test/unit/check/arbitrary/helpers/ArrayInt64.spec.ts
Fixes #1491
No visible impact/fix from an user point of view (internal API whose bug never surfaces). We are just ensuring that internals do what they say to do.
❌ New feature
None
=> 🐛 `add64` is not supposed to produce negative zeros

documentation/Arbitraries.md, documentation/Tips.md, example/005-race/autocomplete/main.spec.tsx, example/005-race/userProfile/main.spec.tsx, perf/tasks.js, src/check/arbitrary/ArrayArbitrary.ts, test/unit/check/arbitrary/ArrayArbitrary.spec.ts
❌ New feature
❌ Fix an issue
Remove deprecated signatures of `fc.array`.
=> 💥 Remove deprecated signatures of `fc.array`

example/005-race/debounced-autocomplete/main.spec.tsx, example/005-race/todolist/main.spec.tsx, src/check/arbitrary/StringArbitrary.ts, test/unit/check/arbitrary/StringArbitrary.spec.ts
❌ New feature
❌ Fix an issue
Remove deprecated signatures of `fc.*string*`.
=> 💥 Remove deprecated signatures of `fc.string`

documentation/Arbitraries.md, src/check/arbitrary/SubarrayArbitrary.ts, test/unit/check/arbitrary/SubarrayArbitrary.spec.ts
❌ New feature
❌ Fix an issue
Remove deprecated signatures of `fc.*subarray`.
=> 💥 Remove deprecated signatures of `fc.*subarray`

documentation/Arbitraries.md, documentation/Tips.md, src/check/model/commands/CommandsArbitrary.ts
❌ New feature
❌ Fix an issue
Remove deprecated signatures of `fc.commands`.
=> 💥 Remove deprecated signatures of `fc.commands`

documentation/Arbitraries.md, src/check/arbitrary/OptionArbitrary.ts
❌ New feature
❌ Fix an issue
Remove deprecated signatures of `fc.option`.
=> 💥 Remove deprecated signatures of `fc.option`

documentation/Arbitraries.md, src/check/arbitrary/ObjectArbitrary.ts
❌ New feature
❌ Fix an issue
Remove deprecated signatures of `fc.*json*`.
=> 💥 Remove deprecated signatures of `fc.json`

documentation/Arbitraries.md, example/005-race/autocomplete/main.spec.tsx, example/005-race/todolist/main.spec.tsx, src/check/arbitrary/ObjectArbitrary.ts, src/check/arbitrary/SetArbitrary.ts, test/unit/check/arbitrary/SetArbitrary.spec.ts, test/unit/check/arbitrary/SparseArrayArbitrary.utest.spec.ts
❌ New feature
❌ Fix an issue
Remove deprecated signatures of `fc.set`.
=> 💥 Remove deprecated signatures of `fc.set`

documentation/Arbitraries.md, src/check/arbitrary/IntegerArbitrary.ts, test/unit/check/arbitrary/IntegerArbitrary.spec.ts
❌ New feature
❌ Fix an issue
Remove deprecated signatures of `fc.integer`.
=> 💥 Remove deprecated signatures of `fc.integer`

.github/workflows/build-status.yml, README.md, test/type/main.ts
Related to #1492
Officially dropping support for TypeScript 3.2.
The new minimal requirement will be 4.0.
❌ New feature
❌ Fix an issue
✔️ Other: *doc*
Typings impact
=> 💥 Drop support for TypeScript 3.2 (min ≥4.0)

.github/workflows/build-status.yml, README.md
Related to #1492
Required for #1519
The new minimal requirement will be 4.1.
❌ New feature
❌ Fix an issue
✔️ Other: *doc*
Typings impact
=> 💥 Drop support for TypeScript 4.0 (min ≥4.1)

.github/workflows/build-status.yml, jest.setup.js
Checking for the env variable CI, makes running in vscode impossible.
We relax the check and use something else to check we want a seed to be defined.
❌ New feature
❌ Fix an issue
None
=> 👷 Relax check ensuring default seed defined in CI

src/check/arbitrary/FrequencyArbitrary.ts, test/unit/check/arbitrary/FrequencyArbitrary.spec.ts
✔️ New feature
❌ Fix an issue
`fc.frequency` may reject invalid inputs earlier
=> ✨ Reject invalid weights on `fc.frequency`

documentation/Runners.md, src/check/property/IgnoreEqualValuesProperty.ts, src/check/runner/DecorateProperty.ts, src/check/runner/configuration/Parameters.ts, src/check/runner/configuration/QualifiedParameters.ts, test/e2e/IgnoreEqualValues.spec.ts, test/unit/check/property/IgnoreEqualValuesProperty.spec.ts, test/unit/check/runner/DecorateProperty.spec.ts
For some tests possible cases count is very small, and we don't need to repeat them again and again. This feature will allow detecting repetitions and skip them. Resolves #1576
✔️ New feature
❌ Fix an issue
Performance impact due to a decrease of the property check runs.
=> Add a way to ignore already covered cases in property check

src/check/arbitrary/FrequencyArbitrary.ts, test/unit/check/arbitrary/FrequencyArbitrary.utest.spec.ts
✔️ New feature
❌ Fix an issue
Can eventually break some invalid calls to `fc.frequency`. Actually those calls should result in runtime failures on generate or infinite loops.
=> ✨ Stricter checks on args of `fc.frequency`

documentation/Arbitraries.md, src/check/arbitrary/FrequencyArbitrary.ts, test/e2e/RecursiveStructures.spec.ts, test/unit/check/arbitrary/FrequencyArbitrary.itest.spec.ts, test/unit/check/arbitrary/FrequencyArbitrary.utest.spec.ts
✔️ New feature
❌ Fix an issue
None
=> ✨ Add `depthFactor` constraint on `fc.frequency`

src/check/arbitrary/FrequencyArbitrary.ts, src/check/arbitrary/OneOfArbitrary.ts, test/unit/check/arbitrary/FrequencyArbitrary.itest.spec.ts
❌ New feature
❌ Fix an issue
✔️ Other: *refactor: oneof is just a special case of frequency*
No impact expected
=> ♻️ Re-use `fc.frequency` for `fc.oneof`

src/check/arbitrary/OptionArbitrary.ts, test/e2e/__snapshots__/NoRegression.spec.ts.snap
❌ New feature
❌ Fix an issue
✔️ Other: *refactor: option is just a special case of frequency*
Shrinker differ:
In the past `fc.option` used to shrink the value first then try at the end with nil.
Now, we try nil first, then try with smaller values.
As `fc.option` is used by many others, changes in shrinkers could be expected in:
- `fc.record` (with deleted keys)
- `fc.domain`
- `fc.emailAddress`
- `fc.webAuthority`
- `fc.webUrl`
=> ♻️ Re-use `fc.frequency` for `fc.option`

documentation/Arbitraries.md
❌ New feature
❌ Fix an issue
None
=> 📝 Better documentation for `fc.letrec`

documentation/Arbitraries.md, src/check/arbitrary/TupleArbitrary.ts
❌ New feature
❌ Fix an issue
✔️ Other: *depreciation notice*
None
=> 🗑 Mark `fc.genericTuple` as deprecated

src/check/arbitrary/BigIntArbitrary.ts, src/check/arbitrary/IntegerArbitrary.ts, src/check/arbitrary/helpers/ArrayInt64Arbitrary.ts, src/check/arbitrary/helpers/BiasNumeric.ts, src/check/arbitrary/helpers/ShrinkBigInt.ts, src/check/arbitrary/helpers/ShrinkInteger.ts, test/unit/check/arbitrary/generic/RandomHelpers.ts, test/unit/check/arbitrary/helpers/ArrayInt64Arbitrary.utest.spec.ts, test/unit/check/arbitrary/helpers/BiasNumeric.spec.ts
❌ New feature
❌ Fix an issue
✔️ Other: *refactor*
None expected but if any on integer/double/bigint and by transition any arbitrary offered by fast-check on:
- Shrink values impact
=> ♻️ Migrate integer/bigint/double to NextArbitrary

src/arbitrary/_internals/helpers/ShrinkInteger.ts
❌ New feature
Shrink values impact for integers declaring a range larger than MAX_SAFE_INTEGER.
=> 🐛 Shrinker on integers was possibly generating out-of-range values

src/arbitrary/_internals/IntegerArbitrary.ts
=> 🩹 `canGenerate` method on integer should reject `-0`

src/arbitrary/_internals/FrequencyArbitrary.ts
❌ New feature
Not released yet
=> 🩹 `canGenerate` of `FrequencyArbitrary` was not using depth properly

src/arbitrary/option.ts
❌ New feature
Generated values impact: option(arb, 0) will not take 0 as freq. Previously it was translated into 5.
=> 🐛 `freq` of `0` not considered the same way in constraints-based and simple arg

prebuild/property.cjs, src/arbitrary/_internals/TupleArbitrary.ts, src/arbitrary/genericTuple.ts, src/arbitrary/tuple.ts, src/check/arbitrary/DictionaryArbitrary.ts, src/check/arbitrary/EmailArbitrary.ts, src/check/arbitrary/FloatingPointArbitrary.ts, src/check/arbitrary/FunctionArbitrary.ts, src/check/arbitrary/HostArbitrary.ts, src/check/arbitrary/IpArbitrary.ts, src/check/arbitrary/ObjectArbitrary.ts, src/check/arbitrary/RecordArbitrary.ts, src/check/arbitrary/SparseArrayArbitrary.ts, src/check/arbitrary/UuidArbitrary.ts, src/check/arbitrary/WebArbitrary.ts, src/fast-check-default.ts, test/unit/arbitrary/_internals/TupleArbitrary.itest.spec.ts, test/unit/arbitrary/_internals/TupleArbitrary.utest.spec.ts, test/unit/check/arbitrary/SparseArrayArbitrary.utest.spec.ts, test/unit/check/arbitrary/UuidArbitrary.utest.spec.ts, test/unit/check/arbitrary/definition/Arbitrary.itest.spec.ts, test/unit/check/model/commands/CommandsArbitrary.spec.ts
❌ New feature
❌ Fix an issue
✔️ Other: *moving code*
No impact is expected as IDE fail to import the right paths with auto-imports different from root.
Non-root import changed for tuple, genericTuple
=> 🚚 Move tuple arbitraries into /arbitrary

documentation/Arbitraries.md, src/check/arbitrary/StreamArbitrary.ts, test/e2e/__snapshots__/NoRegression.spec.ts.snap, test/unit/check/arbitrary/StreamArbitrary.spec.ts
❌ New feature
- Generated values impact: values will always be properly cloned
- ToString impact: now we print the accessed values (not the top 10)
=> 🐛 `infiniteStream` was not properly cloning cloneable instances

src/check/arbitrary/StreamArbitrary.ts
❌ New feature
❌ Fix an issue
✔️ Other: *rewrite*
No impact expected. But if any: `infiniteStream`
=> ♻️ Migrate `infiniteStream` to `NextArbitrary`

src/arbitrary/_internals/ConstantArbitrary.ts, test/unit/arbitrary/_internals/ConstantArbitrary.spec.ts
❌ New feature
Shrink values impact: very very rare, only for NaN or -0, 0.
=> 🐛 `ConstantArbitrary` must not shrink towards the first if it is already the first

src/arbitrary/_internals/StreamArbitrary.ts, test/e2e/__snapshots__/NoRegression.spec.ts.snap, test/unit/arbitrary/StreamArbitrary.spec.ts
`StreamArbitrary` was missing the last accessed value in `toString`.
❌ New feature
None
=> 🐛 `StreamArbitrary` should print any value that have been pulled

src/check/arbitrary/definition/NextArbitrary.ts, test/unit/check/arbitrary/definition/NextArbitrary.utest.spec.ts
Up-to-now the next generation of arbitraries built using `map` were unable to offer capabilities like `canGenerate` and `shrink` of user-defined values. With this PR it becomes possible for users of `.map` to generate a way to `unmap` values.
Please note that normal shrinking process on `.map` will not use this `unmap`. It has been added only for the shrinking process of user-defined values that have not been generated by using `generate` or are missing the context.
✔️ New feature
❌ Fix an issue
None
=> ✨ Support `canGenerate` and `shrink` of user-defined values on `map`

src/check/arbitrary/definition/NextArbitrary.ts, test/unit/check/arbitrary/definition/NextArbitrary.utest.spec.ts
❌ New feature
None - Not release
=> 🐛 `.map` should check `canGenerate` on source before calling `shrink`

src/arbitrary/date.ts, src/check/arbitrary/ObjectArbitrary.ts, src/fast-check-default.ts, test/unit/arbitrary/DateArbitrary.itest.spec.ts, test/unit/arbitrary/DateArbitrary.utest.spec.ts
❌ New feature
❌ Fix an issue
Moving code
=> 🚚 Move date arbitrary into /arbitrary

src/arbitrary/lorem.ts, test/unit/arbitrary/LoremArbitrary.spec.ts
=> 🐛 `maxCount` of `0` was overriden to `5` in `lorem` instead of being rejected

test/unit/arbitrary/date.spec.ts
Fixes  #1880
❌ New feature
❌ Fix an issue
None
=> 💚 Adapt inputs for wrongly defined property on `date`

src/arbitrary/_internals/FrequencyArbitrary.ts, src/arbitrary/option.ts, test/unit/arbitrary/_internals/FrequencyArbitrary.spec.ts, test/unit/arbitrary/option.spec.ts
=> 🐛 `option` can now properly shrink without any context (incl. to nil)

test/unit/arbitrary/_internals/IntegerArbitrary.spec.ts
Spec has been wrongly updated thus we tried to run: `integer().canShrinkWithoutContext(-0)` and were expecting `true` while `-0` is not an integer.
=> 💚 Integer spec was asking if `integer` can produce `-0`

src/arbitrary/_internals/ConstantArbitrary.ts
Improve performance of the generate method on constants arbitraries. The custom get value of `NextValue` constructor was adding an extra cost to the generate cost.
From my measurements, improvements are significants:
```ts
Property(fc.constant('a')) on fast-check@2.14.0 x 6,653 ops/sec ±0.60% (91 runs sampled)
Property(fc.constant('a')) on fast-check@2.15.0 x 2,290 ops/sec ±3.02% (80 runs sampled)
Property(fc.constant('a')) on fast-check@99.99.99 x 3,374 ops/sec ±3.76% (82 runs sampled)
```
_99.99.99 is master + the change_
=> ⚡️ Faster `generate` for `constant` and `constantFrom`

src/check/arbitrary/definition/ConverterFromNext.ts, src/check/arbitrary/definition/ConverterToNext.ts
Improve performance the conversions from and to NextValue.
From my measurements, improvements are significant:
```ts
Property(fc.constant('a')) on fast-check@2.14.0 x 6,614 ops/sec ±0.82% (90 runs sampled)
Property(fc.constant('a')) on fast-check@2.15.0 x 2,453 ops/sec ±3.65% (85 runs sampled)
Property(fc.constant('a')) on fast-check@99.99.99 x 5,937 ops/sec ±0.48% (94 runs sampled)
```
_99.99.99 is master + #1945 + the change_
=>  ⚡️ Speed-up conversions from/to `NextValue`

example/005-race/debounced-autocomplete/main.spec.tsx
We forgot to properly escaped the strings passed to `userEvent.type`.
For the moment let's use the regex suggested by https://github.com/testing-library/user-event/issues/586.
=> 💚 Escape strings passed to `userEvent.type` in examples

src/check/arbitrary/definition/NextValue.ts, src/check/arbitrary/definition/Shrinkable.ts
Let's try performance a step further by optimizing the normal case of non-cloneable values in `NextValue` and `Shrinkable`.
=> ⚡️ More performant non-cloneable values in `NextValue`

.gitignore, src/arbitrary/constantFrom.ts
Add constantFrom variant.
Now we can only create an arb that produces values like this.
```typescript
type Color = "white" | "black"
const arb = constantFrom<Color[]>("white", "black") // Arbitrary<Color>
```
But type parameter `Color[]` is not intuitive.
With this PR feature we can create an arb from simple type annotation.
```typescript
type Color = "white" | "black"
const arb = constantFrom<Color>("white", "black") // Arbitrary<Color>
```
> NOTE:
You cannot create union type of literal type arbs without a type annotation.
> ```typescript
> type Color = "white" | "black"
> 
> const arb = constantFrom("white", "black") // Arbitrary<string>
> ```
=> 🚀 create overload constantFrom

src/check/runner/utils/RunDetailsFormatter.ts
The default formatter used within fast-check was performing side-effects onto the execution summary. Hopefully most of the time users are either relying on `fc.check` and manually format the error on their own or rely on `fc.assert` which uses the default formatter but never re-uses the execution summary afterwards.
In the case of a manual formatter, users might rely on the default formatter so could probably be impacted.
Very limited impact expected as most of the users rely on `fc.assert` or fully custom handling.
=> 🐛 Default reporter performed side-effects on the output

src/arbitrary/sparseArray.ts, src/check/arbitrary/ObjectArbitrary.ts, src/fast-check-default.ts, test/unit/arbitrary/SparseArrayArbitrary.itest.spec.ts, test/unit/arbitrary/SparseArrayArbitrary.utest.spec.ts
=> 🚚 Move `sparseArray` arbitrary into /arbitrary

src/random/generator/PureRandom.ts
=> ✏️ Invalid HTML element in `PureRand.ts`

src/arbitrary/_internals/builders/AnyArbitraryBuilder.ts, src/arbitrary/_internals/builders/BoxedArbitraryBuilder.ts, src/arbitrary/_internals/mappers/ArrayToMap.ts, src/arbitrary/_internals/mappers/ArrayToSet.ts, src/arbitrary/_internals/mappers/ObjectToPrototypeLess.ts, src/arbitrary/_internals/mappers/UnboxedToBoxed.ts, test/unit/arbitrary/_internals/mappers/ArrayToMap.spec.ts, test/unit/arbitrary/_internals/mappers/ArrayToSet.spec.ts, test/unit/arbitrary/_internals/mappers/ObjectToPrototypeLess.spec.ts, test/unit/arbitrary/_internals/mappers/UnboxedToBoxed.spec.ts
Partial support requires float and double to be compatible
Full support requires sparse arrays and typed arrays to be compatible
=> ✨ Add built-in unmapper support onto object arbitraries

test/unit/arbitrary/_internals/ConstantArbitrary.spec.ts, test/unit/arbitrary/_internals/FrequencyArbitrary.spec.ts
=> ✏️ Remove unused arbitraries from properties in unit-tests

src/arbitrary/_internals/builders/TypedIntArrayArbitraryBuilder.ts, src/arbitrary/float32Array.ts, src/arbitrary/float64Array.ts, test/unit/arbitrary/_internals/builders/TypedIntArrayArbitraryBuilder.spec.ts, test/unit/arbitrary/float32Array.spec.ts, test/unit/arbitrary/float64Array.spec.ts
=> ✨ Add built-in unmapper support onto typed-arrays

documentation/Arbitraries.md
Thank you for documenting this tip about mapping -0 to +0!
This commit reverses the order of the Bilbo Baggins transformation so
the parse occurs after the stringify.
=> 📝 stringify then parse in code example

src/arbitrary/_internals/helpers/MaxLengthFromMinLength.ts
The maxLength automatically computed when only minLength specified was wrongly computed. It may have triggered unwanted crashes.
=> 🐛 Cap auto-maxLength of `array` to `2**31-1`

src/arbitrary/_internals/builders/AnyArbitraryBuilder.ts
The sparse arrays generated by `anything` or `object` were not following the constraint `maxKeys` while it was follwoed by normal arrays. We just aligned the behaviours.
=> 🐛 To many keys in the sparse arrays of `anything`

test/unit/check/property/IgnoreEqualValuesProperty.spec.ts
`it.each` was printing red **Error** tags whenever we asked it to stringify an instance of error. We just avoid doing that so that our logs will be cleaner.
=> ✅ Avoid Error tags in reports caused by some tests

src/arbitrary/integer.ts
Follow-up of https://github.com/dubzzz/fast-check/issues/992: let's stop supporting this kind of signature, they make the API harder to use as some (this one) would offer many signatures to do the same thing while others don't.
=> 🗑️ Mark `integer(min, max)` as deprecated

src/arbitrary/_internals/helpers/JsonConstraintsBuilder.ts, src/arbitrary/jsonObject.ts, src/arbitrary/unicodeJsonObject.ts, src/fast-check-default.ts
As suggested by #2135, let's offer a better typing on `jsonObject` and related. So far, I still have one `as` to keep but I hope to remove it once we get simpler inputs for the builder of arbitraries of "type any".
Fixes #2135
=> 🏷️ More precise typing for `jsonObject` and related

src/arbitrary/integer.ts, src/arbitrary/nat.ts, test/unit/arbitrary/integer.spec.ts, test/unit/arbitrary/nat.spec.ts
Let's adopt something better than what we have today. As said in comment https://github.com/dubzzz/fast-check/issues/2038#issuecomment-918885358, there is no fully bulletproof way to check that the values will able to work. Values outside of the safe range can fail but can also work.
Fixes #2038
=> 🔊 Warn users earlier for wrong params on `integer`

documentation/Arbitraries.md
`fc.oneof` function does not take weighted arbitraries as the documentation states, so I proposed a correction.
Should have no impact beyond an updated documentation
=> ✏️ Documentation fix for `fc.oneof`

documentation/Arbitraries.md, src/arbitrary/_internals/builders/AnyArbitraryBuilder.ts, src/arbitrary/_internals/helpers/JsonConstraintsBuilder.ts, src/arbitrary/_internals/helpers/QualifiedObjectConstraints.ts, test/unit/arbitrary/_internals/builders/AnyArbitraryBuilder.spec.ts, test/unit/arbitrary/jsonObject.spec.ts, test/unit/arbitrary/unicodeJsonObject.spec.ts
For the moment, arbitraries on objects have not provided any way to alter the depth factor defined its internal `oneof`. The only way to control their depth was to request an explicit (and most of the time arbitrary) maximal depth. This PR adds the ability to provide a depth factor on any arbitrary on objects. In the future, depth factor will certainly be preset with something like 0.1 and maximal depth will just be a fully optional setting only specified if the user really want to limit the depth.
This PR is a prerequisite for https://github.com/dubzzz/fast-check/pull/2464
=> ✨ `depthFactor` on arbitraries for objects

src/arbitrary/_internals/helpers/StrictlyEqualSet.ts, src/arbitrary/set.ts, test/unit/arbitrary/_internals/helpers/StrictlyEqualSet.spec.ts
Only applies for instances of `set` not overriding the default comparator. Any override of the compator will lead to degradated performances. The performance gap will mostly be visible with large arrays.
=> ⚡️ Improve performance of `set`

src/arbitrary/_internals/builders/AnyArbitraryBuilder.ts
=> ⚡️ Use relevant comparator to build `anything`

src/arbitrary/_internals/ArrayArbitrary.ts, src/arbitrary/array.ts, src/arbitrary/set.ts, test/unit/arbitrary/array.spec.ts, test/unit/arbitrary/set.spec.ts
Prepare the code for #2648 by adding this new capability. So far we don't really use it as maxGeneratedLength and maxLength have always the same values. But things will change in the upcoming PRs.
=> ♻️ Split maxLength into two facets inside the internal for arrays

src/arbitrary/sparseArray.ts
When `fc.sparseArray` has been passed the constraint `noTrailingHole` it should refuse to shrink arrays ending with a hole.
=> 🐛 Don't shrink array with trailing hole when not supporting it

package.json
When trying to use `fast-check` with TypeScript where  `moduleResolution` is set to `Node12` or `NodeNext` we get the following error:
> Could not find a declaration file for module 'fast-check'. '.../node_modules/fast-check/lib/esm/fast-check.js' implicitly has an 'any' type.
> Try `npm i --save-dev @types/fast-check` if it exists or add a new declaration (.d.ts) file containing `declare module 'fast-check';`ts(7016)
This change fixes the issue.
I think this might be related: https://github.com/microsoft/TypeScript/issues/46334
- [] 🏷️ Add or update types
=> 🐛🔧 Add `"types"` to `"exports"`

package.json, yarn.lock
=> 🐛 Bump `pure-rand` for `moduleResolution` fix

.github/workflows/build-status.yml
Let's try to cover #2803 with dedicated tests.
=> ✅ Run fast-check against `--moduleResolution nodenext`

documentation/Arbitraries.md
In #2616 when `uniqueArray` was added the signatures in the documentation were not updated. Looks like a copy/paste error 🙂 
=> Corrected uniqueArray signatures

documentation/Arbitraries.md, src/arbitrary/_internals/ArrayArbitrary.ts, src/arbitrary/_internals/FrequencyArbitrary.ts, src/arbitrary/_internals/helpers/DepthContext.ts, src/arbitrary/array.ts, src/arbitrary/frequency.ts, src/arbitrary/oneof.ts, src/arbitrary/option.ts, src/arbitrary/set.ts, src/arbitrary/sparseArray.ts, src/arbitrary/uniqueArray.ts, src/fast-check-default.ts, test/e2e/RecursiveStructures.spec.ts
Up-to-now building depth identifier was possible by passing a string that can be shared across many instances that want to benefit from the same depth. But there was no way to come with a fully unique identifier that will have no chance to collide with existing ones (except by randomly generating a unique string).
With that PR we create a new helper that makes it possible for our users to create fully unique instances of depth identifiers they may or may not share with others. It as an extra benefit compared to the string version: it does not rely on a cache (never cleaned) and handled by fast-check internally.
=> ✨ Simpler way to create unique identifier for depths

documentation/Arbitraries.md, src/arbitrary/_internals/helpers/QualifiedObjectConstraints.ts
Such defaulting would avoid breaking existing code with the next minor. Indeed in the current work in progress heading to be the next minor, we' have highly increased the probably to generate deep objects. As a consequence, if not depth factor is added, users will probably see the size of the generated objects explodes a bit.
The previous version was really unlikely to produce deep objects even when passed a max depth larger than the default (being 2). The new one can reach it, and by reach it it means create "max depth" levels, each with many items. In other words, very large structures with lots of items while it was barely impossible in the past.
=> ✨ Default depth factor of objects to `=` when not set

documentation/Arbitraries.md, src/arbitrary/lorem.ts
Drop any legacy signatures of `fc.lorem` as planned in #992.
Any signature marked as deprecated on `fc.lorem` will be dropped by this PR.
Originally merged as #1504 for alpha versions.
Dropped signatures:
- `function lorem(maxWordsCount: number): Arbitrary<string>`
- `function lorem(maxWordsCount: number, sentencesMode: boolean): Arbitrary<string>`
=> 💥 Remove deprecated signatures of `fc.lorem`

.github/workflows/build-status.yml, README.md, test/type/main.ts
Officially dropping support for TypeScript <4.1 for next major aka 3.x.
In version 2.x of fast-check, we used to support any version of TypeScript ≥3.2. It will not be the case anymore starting at 3.x.
In version 3.x, we will support any version of TypeScript ≥4.1, so we dropped part of the supported range.
This PR is a rework of #1517 and #1520 for the target 3.x major of fast-check.
=> 💥 Drop support for TypeScript 3.2 (min ≥4.1)

documentation/Arbitraries.md, src/arbitrary/_internals/helpers/MaxLengthFromMinLength.ts, src/arbitrary/_internals/helpers/QualifiedObjectConstraints.ts, test/e2e/RecursiveStructures.spec.ts, test/e2e/arbitraries/LetRecArbitrary.spec.ts, test/unit/arbitrary/_internals/implementations/SchedulerImplem.spec.ts
For backward compatibility reasons, this behaviour has only be applied on some existing structures for v2. Indeed, applying it to `oneof` or `frequency` would potentially have introduced breaking changes for the end-user. As an example of such issue, the test "_Should be usable to build deep tree instances_" had to be adapted to prevent geenrating too many nodes (nodes being the fallback when the tree goes deep in the legacy code).
For the end-user, the change has one impact: the first arbitrary specified in `frequency` or `oneof` must be the terminal case. In other words, not one triggering another recursion.
=> 💥 No `depthFactor` specified means: use defaulted configuration

src/arbitrary/_internals/helpers/MaxLengthFromMinLength.ts, test/e2e/arbitraries/LetRecArbitrary.spec.ts, test/unit/arbitrary/_internals/helpers/MaxLengthFromMinLength.spec.ts
Up-to-now the size of 'max' has been reserved to length-related sizes. We want to extend its support to depth-related sizes too.
This PR adds the ability to set the depth factor as 'max'. Setting it as max is fully equivalent to setting it as 0 (we have potential plans to change this 0 into a +infinity so that max means the highest value and not the smallest one as it is the case for the moment).
=> ✨ Add the ability to define use max as depth factor

src/check/property/AsyncProperty.generic.ts, src/check/property/IRawProperty.ts, src/check/property/Property.generic.ts, src/check/property/TimeoutProperty.ts, src/check/runner/Runner.ts, src/check/runner/RunnerIterator.ts, src/fast-check-default.ts, test/unit/check/property/AsyncProperty.spec.ts, test/unit/check/property/Property.spec.ts, test/unit/check/property/TimeoutProperty.spec.ts, test/unit/check/runner/Runner.spec.ts, test/unit/check/runner/Tosser.spec.ts
Up-to-now any Error intercepted by fast-check got intercepted by Property and translated immediately to strings. Unfortunately it means that we lose all the details linked to the original error.
While not really required for fast-check itself, those details converning the original thrown Error can be pretty useful for reporting tools like WallabyJS (see #660) and probably many others.
This PR introduces abreaking change in the existing API of property that will unlock the ability to enrich the Error produced by fast-check with details coming from the original Error whenever needed or requested. It would potentially unlock things like adding back attributes as expected or actual onto the Error or just put it as the cause of the Error produced by fast-check.
**_Potential …
=> 💥 Change the output of `Property::run` to return the original error

test/e2e/Sampler.spec.ts
The move from fast-check old engine to its new version in v2 broke `fc.sample` when called on properties. While it has been fixed for v3, we still want such regression from occuring again in the future.
This test will avoid such bug from being unseen for so long. Error has been reported by #2736
=> ✅ Ensure `fc.sample` can run against properties and arbitraries

src/check/runner/RunnerIterator.ts, src/check/runner/reporter/RunDetails.ts, src/check/runner/reporter/RunExecution.ts, test/unit/check/runner/reporter/RunExecution.spec.ts
Passing the original instance of `Error` into `RunDetails` can make users wanting to read from the original error to compute their error message able to do that.
On fast-check's side it will unlock the ability to add more details onto the error produced by the framework.
=> ✨ Forward the original `Error` into `RunDetails`

src/check/property/AsyncProperty.generic.ts, src/check/property/Property.generic.ts, test/unit/check/property/AsyncProperty.spec.ts, test/unit/check/property/Property.spec.ts
The previous implementation would have crashed if user threw a Symbol. While the case is rare and can even be considered fully unexpected, we want to prevent the crash as much as possible just in case.
But we explicitely do not handle the case of an object being thrown with a custom toString.
=> 🐛 Allow property to intercept thrown symbols

src/arbitrary/letrec.ts, src/fast-check-default.ts, test/type/main.ts
As suggested in issue #1164 and then in the PR #1572, typings of `letrec` could have been improved a lot. And this is basically the idea of this PR that was highly inspired by #1572 and fixed the few last remaining issues.
=> 🏷️ Better typings for `letrec`

documentation/Arbitraries.md, example/002-recursive/isSearchTree/arbitraries/BinaryTreeArbitrary.ts, src/arbitrary/_internals/FrequencyArbitrary.ts, src/arbitrary/_internals/builders/AnyArbitraryBuilder.ts, src/arbitrary/_internals/helpers/JsonConstraintsBuilder.ts, src/arbitrary/_internals/helpers/MaxLengthFromMinLength.ts, src/arbitrary/_internals/helpers/QualifiedObjectConstraints.ts, src/arbitrary/array.ts, src/arbitrary/letrec.ts, src/arbitrary/oneof.ts, src/arbitrary/option.ts, src/arbitrary/sparseArray.ts, src/arbitrary/uniqueArray.ts, src/fast-check-default.ts, test/e2e/NoRegression.spec.ts, test/e2e/RecursiveStructures.spec.ts, test/e2e/__snapshots__/NoRegression.spec.ts.snap, test/e2e/arbitraries/LetRecArbitrary.spec.ts, test/legacy/node-8/main.js, test/unit/arbitrary/_internals/ArrayArbitrary.spec.ts, test/unit/arbitrary/_internals/FrequencyArbitrary.spec.ts, test/unit/arbitrary/_internals/builders/AnyArbitraryBuilder.spec.ts, test/unit/arbitrary/_internals/helpers/MaxLengthFromMinLength.spec.ts, test/unit/arbitrary/jsonValue.spec.ts, test/unit/arbitrary/oneof.spec.ts, test/unit/arbitrary/option.spec.ts, test/unit/arbitrary/unicodeJsonValue.spec.ts
Rename `depthFactor` into `depthSize` for one main reason: the current attribute was used for both size (small means not deep and large means deep) and numeric values (0 means deep and +infinity means not deep) but has non-aligned meanings. As a consequence we wanted to align the logic so that small or 0 always means no deep and large or +infinity always means deep.
As this change could have been misleading for an end-user reading the documentation of v2 or v3, we decided to use another name to make it clearer that `depthFactor` and `depthSize` are not exactly the same and that an adaptation might be needed to go from one to the other.
Related to #2969
=> 💥 Rename `depthFactor` into `depthSize` and invert numeric

.github/workflows/build-status.yml, .github/workflows/please-actions.yml, CONTRIBUTING.md
Simplify the build workflow by using `yarn workspace *` instead of `cd packages/*` whenever possible.
=> 👷 Switch to `yarn workspace *` instead of `cd packages/*`

.github/workflows/build-status.yml, .yarn/versions/ebf9fefd.yml
Up-to-now the jobs dealing with the specs of fast-check has to first build the package and then run the tests. As we already build the package via a dedicated job, let's leverage this job in all the jobs requesting to build the package.
=> 👷 Make fast-check's tests rely on its own build

.yarn/versions/2aeef278.yml, packages/fast-check/src/arbitrary/_internals/ArrayArbitrary.ts, packages/fast-check/src/arbitrary/_internals/helpers/BuildSlicedGenerator.ts, packages/fast-check/src/arbitrary/_internals/implementations/NoopSlicedGenerator.ts, packages/fast-check/src/arbitrary/_internals/implementations/SlicedBasedGenerator.ts, packages/fast-check/src/arbitrary/_internals/interfaces/SlicedGenerator.ts, packages/fast-check/test/unit/arbitrary/_internals/implementations/SlicedBasedGenerator.spec.ts
Sliced based generators will make it possible to implement features like the long awaited one: "Helper to deal with dangerous strings" #484. Indeed they will make arrays able to generate pre-defined values so that some barely impossible to generate values like `['_','_','p','r','o','t','o','_','_']` will be more likely for strings.
The current PR mostly adds the internals to make it possible within arrays. But there is for the moment nothing to connect it, neither externally for fast-check's users nor internally for our strings. Here we mostly pave the way for it without really making it real.
So from an external point of view, this PR mostly deals with refactoring internals. From our point of view, it adds an important feature, not yet visible but things introduced by the PR will be game …
=> ♻️ Implement sliced based generator for arrays

.yarn/versions/c3a09b7f.yml, packages/fast-check/src/arbitrary/_internals/ArrayArbitrary.ts, packages/fast-check/src/arbitrary/array.ts, packages/fast-check/src/arbitrary/uniqueArray.ts, packages/fast-check/test/unit/arbitrary/_internals/ArrayArbitrary.spec.ts, packages/fast-check/test/unit/arbitrary/array.spec.ts, packages/fast-check/test/unit/arbitrary/uniqueArray.spec.ts
This new constraint not officially exposed to fast-check's users (in other words, name might change in patch, minor... without any precise warning), should unlock the feature "Helper to deal with dangerous strings" https://github.com/dubzzz/fast-check/issues/484 by making it feasible.
So far, it only provides an extra constraint on the API of `array` but it will soon be leveraged for arbitraries on strings.
=> ✨ Add experimental "custom slices" constraint on array

.yarn/versions/27dffeb9.yml, packages/fast-check/src/arbitrary/_internals/mappers/KeyValuePairsToObject.ts, packages/fast-check/test/unit/arbitrary/_internals/mappers/KeyValuePairsToObject.spec.ts
Up-to-now the instances of `dictionary` were unable to generate key "__proto__" even if they were asked to. This is now not anymore the case and they can easily create them too.
=> 🐛 Allow strange keys as keys of dictionary

packages/fast-check/src/check/runner/Sampler.ts
Existing rounding strategy was implementation dependant as toFixed does not really comes with an explicit rounding rule.
=> 🐛 Better rounding in `statistics`

.yarn/versions/4c7660a4.yml, packages/fast-check/src/arbitrary/_internals/mappers/ValuesAndSeparateKeysToObject.ts, packages/fast-check/test/unit/arbitrary/_internals/mappers/ValuesAndSeparateKeysToObject.spec.ts
The current implementation of `record` was not properly supporting `__proto__` as a possible key. It is now the case, `__proto__` will be handled like any other key whenever specified by the users.
Fixes #3065
=> 🐛 Support `__proto__` as key in `record`

packages/fast-check/test/e2e/Poisoning.spec.ts
fast-check has to be able to run even if the running environment is in a very bad shape. In other words, it should be able to run well even when the main prototypes of native JavaScript have been altered in a very distruptive way.
=> ✅ Add some poisoning e2e for fast-check

.yarn/versions/29271184.yml, packages/fast-check/src/arbitrary/_internals/IntegerArbitrary.ts, packages/fast-check/src/arbitrary/_internals/helpers/BiasNumericRange.ts, packages/fast-check/src/arbitrary/_internals/helpers/ShrinkInteger.ts, packages/fast-check/src/check/property/IRawProperty.ts, packages/fast-check/src/check/runner/DecorateProperty.ts, packages/fast-check/src/check/runner/configuration/QualifiedParameters.ts, packages/fast-check/test/e2e/Poisoning.spec.ts
Up-to-now calling `fc.assert` from a broken environment was exploding at execution time because of missing `Math.*` or `Date.*`. Those built-ins were required by fast-check to make some internal computations, but could have been broken by a nasty test fully breaking the environment. As fast-check has to be as good as possible to run without them when they appear broken, we try to make it more reliable in such contexts.
=> 🐛 Protect `assert` from poisoned `Math` or `Date`

.yarn/versions/87062abc.yml, packages/fast-check/src/check/runner/Runner.ts, packages/fast-check/src/utils/apply.ts, packages/fast-check/src/utils/globals.ts, packages/fast-check/src/utils/stringify.ts, packages/fast-check/test/e2e/Poisoning.spec.ts, packages/fast-check/test/unit/utils/apply.spec.ts
This PR makes sure the basic code of `fc.assert` can resist to poisoning occuring on `Object` and `Object.prototype`.
While not covering everything (not all arbitraries), it make sure the bare minimal stuff is working. Arbitraries will be tackled in later changes as soon as basic path fully works without issues for any kind of poisoning.
=> 🐛 Resist to poisoning of `Object`

.yarn/versions/d849592c.yml, packages/fast-check/src/arbitrary/_internals/StreamArbitrary.ts, packages/fast-check/src/arbitrary/_internals/TupleArbitrary.ts, packages/fast-check/src/check/property/AsyncProperty.ts, packages/fast-check/src/check/property/Property.ts, packages/fast-check/src/check/runner/Runner.ts, packages/fast-check/src/check/runner/Tosser.ts, packages/fast-check/src/check/runner/reporter/RunExecution.ts, packages/fast-check/src/check/runner/utils/RunDetailsFormatter.ts, packages/fast-check/src/utils/globals.ts, packages/fast-check/src/utils/stringify.ts, packages/fast-check/test/e2e/Poisoning.spec.ts
Follow-up of #3086
This time we make sure that `fc.assert` will be as bulletproof as possible in case of poisoning.
Follwoing that change, we more or less made sure that a normal property running against the Noop arbitrary will be able to run and shrink up to the end whatever the poisoning occuring on the shared environment. Now many things needs to be done in order to extend that to all our built-in arbitraries.
=> 🐛 Resist to poisoning of `Function`/`Array`/`String`

.github/actions/deploy-netlify/package.json, .yarnrc.yml, examples/package.json, package.json, packages/test-ava-bundle-cjs/package.json, packages/test-ava-bundle-esm/package.json, packages/test-bundle-esbuild-with-import/package.json, packages/test-bundle-esbuild-with-require/package.json, packages/test-bundle-node-extension-cjs/package.json, packages/test-bundle-node-extension-mjs/package.json, packages/test-bundle-node-with-import/package.json, packages/test-bundle-node-with-require/package.json, packages/test-bundle-rollup-with-import/package.json, packages/test-bundle-rollup-with-require/package.json, packages/test-bundle-webpack-with-import/package.json, packages/test-bundle-webpack-with-require/package.json, packages/test-jest-bundle-cjs/package.json, packages/test-jest-bundle-esm/package.json, packages/test-minimal-support/package.json, packages/test-types/package.json
As seen within the code of berry, it seems that not providing any version to a package make it ignored by the version bump plugin. As a consequence let's try that.
Reference: https://github.com/yarnpkg/berry/blob/a66e528506168f7bfaa4fa9fc02b8edb226e47d4/packages/plugin-version/sources/versionUtils.ts#L247-L248
=> 👷 Do not suggest private packages during version bumps

.yarn/versions/33387874.yml, packages/fast-check/src/utils/apply.ts, packages/fast-check/test/unit/utils/apply.spec.ts
Existing version of the code was wrong as it was expecting `apply` to be directly defined on the called function while in theory it comes from the `Function.prototype`.
Given benchmarks we did on https://github.com/dubzzz/fast-check-benchmarks/blob/main/benchmark-poisoning-results.txt, we expect some performance uplift from this change:
- before: from 8,572.147 to 8,823.322 ops/sec
- after: from 15,083.692 to 15,573.392 ops/sec
Measurements on fast-check itself will be carried out before merging the fix to make sure of the performance boost.
=> 🐛 Fix `safeApply` never calling original `apply`

.yarn/versions/2eb7f70f.yml, packages/fast-check/src/utils/apply.ts
Benchmark measurements made at https://github.com/dubzzz/fast-check-benchmarks/blob/main/benchmark-poisoning.js proved that the code for `safeApply` can be speed-up by huge factors if rewritten in a try/catch maner.
We measured:
- before: from 15,083.692 to 15,573.392 ops/sec
- after: from 59,929.287 to 61,058.436 ops/sec
On this benchmark. Figures need to be confirmed on fast-check's code but figures looks promising.
=> ⚡️ Faster implementation for `safeApply`

.yarn/versions/d77a1d6e.yml, packages/fast-check/src/utils/apply.ts, packages/fast-check/src/utils/globals.ts, packages/fast-check/test/unit/utils/apply.spec.ts
=> ♻️ Extract and share code computing safe versions for built-ins

.yarn/versions/4c781230.yml, packages/fast-check/src/arbitrary/_internals/implementations/SlicedBasedGenerator.ts
The risk of being impacted by a poisoning was pretty low as it could only happen for strings when we try to generate an exact value coming from a dicitionary of known dangerous values. While rare, it can still happen and drive developpers crazy if the crash occur in fast-check while the real issue comes from their own code.
=> 🐛 Protect string generators against poisoning

.yarn/versions/6f6f0ebe.yml, packages/fast-check/src/arbitrary/_internals/CloneArbitrary.ts, packages/fast-check/src/arbitrary/_internals/FrequencyArbitrary.ts, packages/fast-check/src/arbitrary/maxSafeInteger.ts, packages/fast-check/src/arbitrary/maxSafeNat.ts, packages/fast-check/src/stream/Stream.ts, packages/fast-check/src/utils/stringify.ts
By global properties we mean things like `Number.MAX_VALUE` or more generally any property (like `MAX_VALUE`) accessible from a globally available type (like `Number`).
=> 🐛 Fix some remaining accesses to global properties

.yarn/versions/8d0cae16.yml, packages/poisoning/src/internals/CaptureAllGlobals.ts
Globals starting with a `_` are generally used for private stuffs such as: measuring coverage with nyc, gathering buffer related metas before dropping it to the console...
As we want poisoning to be easily pluggable without any extensive configuration, we prefer not tracking the content of such entity and just limit ourselves to check in their pointer changed or not but not deeply checking them.
=> ✨(poisoning) Do not track private globals

packages/test-types/main.ts
While ideally writing `oneof()` should be prevented having a version accepting `oneof(...arrayOfArbs)` but rejecting `oneof()` was not straightforward to come up with.
The current output for `oneof()` seems already to be already a good trade-off. So I believe we can close #546 for now.
Fixes #546
=> ✅ Add some more type related tests for oneof

.yarn/versions/e4c620f3.yml, packages/poisoning/src/internals/CaptureAllGlobals.ts, packages/poisoning/src/internals/types/AllGlobals.ts, packages/poisoning/test/internals/TrackDiffsOnGlobal.spec.ts
It will be leveraged later to be able to filter out some globals the user does not want to monitor. But for now, it's only an internal refactoring.
=> ♻️ Attach a `depth` onto globals internally

.yarn/versions/ae0bb4e3.yml, packages/poisoning/src/internals/CaptureAllGlobals.ts, packages/poisoning/src/internals/PoisoningFreeArray.ts, packages/poisoning/src/internals/PoisoningFreeMap.ts, packages/poisoning/src/internals/TrackDiffsOnGlobal.ts, packages/poisoning/test/internals/PoisoningFreeArray.spec.ts, packages/poisoning/test/internals/PoisoningFreeMap.spec.ts, packages/poisoning/test/internals/TrackDiffsOnGlobal.spec.ts
Just adding some more resiliency against poisoning attacks in poisoning package itself. Now dropping String, Array or Map, should not be that harmful for poisoning to run.
=> 🐛(poisoning) Even more resiliency against poisoning

.yarn/versions/439b8b25.yml, packages/jest/README.md, packages/jest/src/jest-fast-check.ts, packages/jest/test.sh, packages/jest/test/itProp.spec.ts, packages/jest/test/testProp.spec.ts
Jest comes with many ways to combine all the `it`, `test` with `skip`, `failing` and others altogether. While so far we decided not to support `each`, we added support for all the other ones.
So you'll now be able to run any of those:
```ts
itProp(...)
itProp.only(...)
itProp.only.failing(...)
itProp.failing(...)
itProp.skip(...)
itProp.skip.failing(...)
itProp.todo(...)
itProp.concurrent(...)
itProp.concurrent.only(...)
itProp.concurrent.only.failing(...)
itProp.concurrent.failing(...)
itProp.concurrent.skip(...)
itProp.concurrent.skip.failing(...)
testProp(...)
testProp.only(...)
testProp.only.failing(...)
testProp.failing(...)
testProp.skip(...)
testProp.skip.failing(...)
testProp.todo(...)
testProp.concurrent(...)
testProp.concurrent.only(...)
testProp.concurrent.only.failing(...) …
```
=> ✨(jest) Add `it.failing` and `it.concurrent` and combinations

.yarn/versions/cc9a3bc5.yml, packages/worker/src/internals/MainThreadRunner.ts, packages/worker/src/internals/SharedTypes.ts, packages/worker/src/internals/WorkerRunner.ts, packages/worker/src/internals/worker-pool/BasicPool.ts, packages/worker/src/internals/worker-pool/WorkerPool.ts, packages/worker/src/main.ts, packages/worker/test/internals/worker-pool/BasicPool.spec.ts, packages/worker/test/main.spec.ts
For better performances, we now share workers accross distinct runs of the predicate (as soon as the worker can be re-used safely). It highly increase the performance of the worker mode in nominal cases while letting the one of timeout code a bit as-is.
=> ⚡️(worker) Share workers across runs of the predicate

.yarn/versions/547133ef.yml, packages/worker/src/internals/worker-pool/BasicPool.ts, packages/worker/test/internals/worker-pool/BasicPool.spec.ts
`messageerror` is an important pipe to get back messages related to errors happening when deserializing a message. They might be really important in a worker context to get a better understanding for what went wrong (is it the communication with the worker? or the execution with the worker?).
=> 🐛(worker) Watch messages emitted on `messageerror`

.yarn/versions/d4e02435.yml, packages/fast-check/src/check/property/AsyncProperty.generic.ts, packages/fast-check/src/check/property/Property.generic.ts, packages/fast-check/src/check/property/TimeoutProperty.ts, packages/fast-check/test/unit/check/property/TimeoutProperty.spec.ts
Up-to-now when a property failed because it returned `false` or reached a time-out, we basically returned an error message but without any error backing it.
We now alos attach an instance of Error next to it, so that users wanting to format their reports in a different way can use it. It will be also leveraged by the error with cause feature which will be able to use it as a cause while it used not to put any cause in such case.
=> ✨ Attach real errors to internal failures

.yarn/versions/ce9dc069.yml, packages/jest/src/jest-fast-check.ts, packages/jest/test/jest-fast-check.spec.ts
=> ✨(jest) Take seed coming from Jest whenever provided

.yarn/versions/4ac099e8.yml, packages/jest/src/jest-fast-check.ts, packages/jest/test/types.ts
This typing issue has been detected thanks to the PR https://github.com/facebook/jest/pull/13493. It showed a mismatch behaviour between fast-check and @fast-check/jest. With this PR we patch the issue and make sure it will not happen again by adding dedicated tests on it.
=> 🏷️(jest) Wrongly typed `itProp` when receiving `examples`

.github/workflows/build-status.yml
No need to check if versions have been properly marked as bumped on publish. If publish task has been triggered then everything is ok.
The only case that was problematic today was when trying to publish from non main branches (backport case).
=> 👷 Ignore version bump checks on publish

.yarn/versions/35cf9aa6.yml, packages/jest/package.json
Fix `@fast-check/jest` types not being properly exported for ESM. See the [TypeScript documentation](https://www.typescriptlang.org/docs/handbook/esm-node.html#:~:text=If%20it%20finds%20them%2C%20it%20will%20look%20for%20a%20colocated%20declaration%20file.%20If%20you%20need%20to%20point%20to%20a%20different%20location%20for%20your%20type%20declarations%2C%20you%20can%20add%20a%20%22types%22%20import%20condition.).
=> 🐛(jest) Fix types not being properly exported for ESM

.yarn/versions/dbf7e0b4.yml, packages/poisoning/src/internals/TrackDiffsOnGlobal.ts
It seems that `Object.getOwnPropertyDescriptors` is not as reliable as `Object.getOwnPropertyDescriptor` in Node 18 when called on `globalThis`.
=> 🐛(poisoning) Switch from descriptors to descriptor for Node 18

.yarn/versions/2ae83f1c.yml, packages/fast-check/src/arbitrary/_internals/TupleArbitrary.ts, packages/fast-check/test/e2e/NoStackOverflowOnShrink.spec.ts, packages/fast-check/test/unit/check/property/AsyncProperty.spec.ts, packages/fast-check/test/unit/check/property/Property.spec.ts
=> 🐛 Avoid stack overflow during shrinking of tuples

.yarn/versions/d036f217.yml, packages/fast-check/src/check/property/AsyncProperty.generic.ts, packages/fast-check/src/check/property/IRawProperty.ts, packages/fast-check/src/check/property/IgnoreEqualValuesProperty.ts, packages/fast-check/src/check/property/Property.generic.ts, packages/fast-check/src/check/property/SkipAfterProperty.ts, packages/fast-check/src/check/property/TimeoutProperty.ts, packages/fast-check/src/check/property/UnbiasedProperty.ts, packages/fast-check/src/check/runner/Runner.ts, packages/fast-check/test/e2e/Timeout.spec.ts, packages/fast-check/test/unit/check/property/AsyncProperty.spec.ts, packages/fast-check/test/unit/check/property/IgnoreEqualValuesProperty.spec.ts, packages/fast-check/test/unit/check/property/Property.spec.ts, packages/fast-check/test/unit/check/property/SkipAfterProperty.spec.ts, packages/fast-check/test/unit/check/property/TimeoutProperty.spec.ts, packages/fast-check/test/unit/check/property/__test-helpers__/PropertyHelpers.ts
Timeout must only focus on the code under tests, in other words the predicate. It should not be triggered because of a beforeEach being too long, or a afterEach being too long.
beforeEach and afterEach must always be run, no matter if the property timeout or not. We want to get closer to the behaviour followed by existing test runners such as jest, see:
```js
beforeAll(() => console.log("before all"));
beforeEach(() => console.log("before each"));
afterEach(() => console.log("after each"));
afterAll(() => console.log("after all"));
test("timeouting...", async () => {
console.log("start");
await new Promise(() => {});
console.log("end");
}, 100);
```
Which prints:
```txt
before all
before each
start
after each
after all
```
And still runs the code after the timeout as it cannot stops it …
=> ✨ No timeout for beforeEach or afterEach

.yarn/versions/93eb2223.yml, packages/fast-check/documentation/Tips.md
This PR addresses the issue raised [here](https://github.com/dubzzz/fast-check/issues/3459). I would prefer a proper fix in the library itself, but this at least gives the users the tools to circumvent the bug themselves!
I have added the suggested piece of code and short explanation to both parts of the docs so that they're easy to find. The idea is that users shouldn't have to stumble over this and have to dig through old issues to potentially find a fix, and can ideally be warned early enough that they circumvent the issue all together.
Please feel free to suggest better, friendlier, or clearer wording, or other places I should add this as well! 
=> 📝 Document how to use `context` in `examples`

.yarn/versions/cb9adede.yml, packages/fast-check/src/check/property/SkipAfterProperty.ts, packages/fast-check/src/check/runner/reporter/RunExecution.ts, packages/fast-check/test/unit/check/property/SkipAfterProperty.spec.ts
In the context of #3084, we want to have a way built-in in fast-check to make sure that tests do not run for too long and can abide by certain timeouts constraints requested by the users.
While today we do have a timeout, it only scopes the interruption to one run of the predicate but does not consider "the runs" as a whole contrary to `interruptAfterTimeLimit`.
On the other hand, `interruptAfterTimeLimit` does have a timeout like behaviour but once started the predicate is never interrupted. Now it could be interrupted in-between, if running it until the end would cause a timeout given the time constraint passed to `interruptAfterTimeLimit`.
With such new feature in place, we will probably have to consider properties not having run at least once as failure, otherwise a buggy async …
=> ✨ Interrupt predicates when `interruptAfterTimeLimit`

.yarn/versions/c0bada4f.yml, packages/fast-check/documentation/Runners.md, packages/fast-check/src/check/runner/configuration/Parameters.ts, packages/fast-check/src/check/runner/reporter/RunExecution.ts, packages/fast-check/test/e2e/SkipAllAfterTime.spec.ts
=> ✨ Mark interrupted runs without any success as failures

.yarn/versions/450c22cf.yml, packages/jest/src/internals/TestWithPropRunnerBuilder.ts, packages/jest/src/internals/types.ts, packages/jest/src/jest-fast-check-worker.ts, packages/jest/test/jest-fast-check.spec.ts
Up-to-now fast-check and jest had their own and separate mechanisms to handle timeouts of running tests.
On one side fast-check defined interruptAfterTimeLimit, on the other Jest defined timeout.
Trick has been to define interruptAfterTimeLimit = 0.9 * timeout, so that fast-check timeouts before jest does (0.ç just being one possible value among others, but it does not mean it will always be fast-check before jest).
This trick will not be needed anymore as when relying on `@fast-check/jest`, timeouts of jest will be redirected to fast-check so that fast-check will be responsible for any timeout related to pbt tests.
Fixes #3084
=> ✨(jest) Let fast-check guide timeouts

.yarn/versions/0eda474b.yml, packages/jest/src/internals/TestWithPropRunnerBuilder.ts, packages/jest/test/jest-fast-check.spec.ts
The current code performs a work-around required as soon as the the user runs Jest with node 18.2.0 or above (whatever the version of Jest). As the bug does not seem to be inherent to the way fast-check plugs itself into Jest configuration (while it's hacky), we for the moment deactivate the new "timeout handled by fast-check itsefl" in these cases.
By the way, it's important to note that bug can also exist if the user does not use default runners, so until we find a more reliable way to access the timeout, we will have kill-switch caces like this one. Hopefully less frequent than the node 18.2.0 one that I hope will be fixed.
Related to ticket https://github.com/facebook/jest/issues/13338
=> 🐛(jest) Support failure to get timeout out of Jest

.yarn/versions/6c0852d7.yml, packages/jest/package.json, packages/jest/src/internals/TestWithPropRunnerBuilder.ts, packages/jest/test/jest-fast-check.spec.ts, yarn.lock
While jasmine runner is not anymore the default runner, it used to be the default one for a while (and for version we officially support). As a consequence not supporting it today is not possible, so this PR fixes this issue.
=> ✨(jest) Add support for jasmine runner

.yarn/versions/aecf7c7e.yml, packages/fast-check/src/stream/Stream.ts
The previous implementation of `Stream::drop` was causing adding an unneeded wrapping level when asking to drop 0 items, while it could just have returned itself.
This PR attempts to drop this extra wrapping in order to check how impactful such removal could be.
=> ⚡️ Do not wrap stream when dropping 0 items

.yarn/versions/62fa1399.yml, packages/fast-check/src/arbitrary/_internals/TupleArbitrary.ts, packages/fast-check/src/check/runner/Tosser.ts
The following optim mostly address performance issues related to toss in the case of no examples. While examples can be a legit usage, we have not covered it i this optimization (yield* not being optimized a lot as it triggers bailout).
=> ⚡️ Drop bailout linked to toss

.yarn/versions/4995b9a8.yml, packages/vitest/src/internals/TestBuilder.ts, packages/vitest/test/vitest-fast-check.spec.ts
Support for `it.fails` and others.
=> 🐛(vitest) Add support for deeper runners

.github/workflows/build-status.yml, packages/jest/test/jest-fast-check.spec.ts
It would prevent regressions linked to latest releases of node from surfacing only when the version starts to be an LTS.
=> 👷 Always build against latest node

.yarn/versions/66290b37.yml, packages/vitest/package.json, packages/vitest/src/vitest-fast-check.ts, packages/vitest/test-bundle/basic.mjs
In other words: Import TestBuilder.js with extension.
Not importing it via an explicit extension caused #3657. Indeed in modern js imports, any import have to specify an extension or more precisely to refer to the file with its full path (relative or absolute).
In theory, we have a dedicated test suite to cover this case, but it seems it was not able to fall into it. I'll probably check back later where it failed and why it did so.
Fixes #3657
=> 🐛(vitest) Fix vitest import failing due to TestBuilder

.yarn/versions/5db59271.yml, packages/fast-check/package.json
It seems to work with it not being first but as linters explicitely tells it's a bad practice let's avoid any problem with it and move it as first field in exports so that we reduce the risks of issues related to bad definition of the package.
=> 🐛 Declare types field first in exports

.github/workflows/build-status.yml, package.json, packages/vitest/package.json, yarn.lock
Make sure our packages will be properly published by checking them against publint.
Related to #3718
=> 🔨 Ensure proper package definition

.github/workflows/build-status.yml
Switch to native `actions/deploy-pages`. Plan being to drop the unneeded and heavy gh-pages branch we used to rely on in the past.
=> 🔧 Change gh-pages deploy process

package.json
Building the website for the documentation has already a dedicated step in the workflow. No need to build it twice. Additionally it's one of the most costly package to build so worth dropping it from fast paths.
=> 🔧 Drop website build on `build:all`

website/package.json
It would avoid having to declare it as noop bump anytime we change a file within it.
=> 🔧 Drop version from website

.github/workflows/build-status.yml
Typings declared within parse5 are not compatible with TS4.4. For now, as tis dependency is not needed for fast-check at all we simplify drop it from the node_modules to let TypeScript happy.
=> 💚 Remove parse5 when checking types

website/docs/introduction/track-record.md
=> 📝 List some bugs found thanks to fast-check

packages/fast-check/test/unit/arbitrary/jsonValue.spec.ts, packages/fast-check/test/unit/arbitrary/unicodeJsonValue.spec.ts
THe current implementation of the test suffered from the fact that `fc.stringify` was producing valid JS values while `JSON.parse` was expecting valid JSON values. As the two specs are not fully aligned being a valid JS value does not imply being a valid JSON one.
Fixes #3478
=> 💚 Stabilize tests on `jsonValue`

.yarn/versions/afdd03c6.yml, packages/fast-check/src/check/model/ModelRunner.ts
Not scheduling models until their end led `scheduledModelRun` never to resolve.As we were waiting for the model while we were not scheduling anything more for it.
=> 🐛 Always schedule models until the end

.yarn/versions/9fbd0c94.yml, packages/fast-check/src/arbitrary/_internals/helpers/TokenizeRegex.ts, packages/fast-check/src/arbitrary/stringMatching.ts, packages/fast-check/test/unit/arbitrary/_internals/helpers/TokenizeRegex.spec.ts, packages/fast-check/test/unit/arbitrary/stringMatching.spec.ts
Up-to-now our `stringMatching` arbitrary was unable to deal properly with `[^a-z]` or `[^abc]`. With that PR, it will be able to deal with them.
=> ✨ Add support for negate regex

.yarn/versions/8ce44fac.yml, packages/fast-check/src/arbitrary/stringMatching.ts
Many flags on regexes are not supported by `stringMatching` at the moment. Instead of letting users detect the issues, we reject before generating anything to make it clear. Support for some of them will come as we enrich this feature.
=> ✨ Explicit ban of unsupported regex flags in `stringMatching`

.yarn/versions/bad5dc1c.yml, packages/fast-check/src/arbitrary/_internals/helpers/TokenizeRegex.ts, packages/fast-check/src/arbitrary/stringMatching.ts, packages/fast-check/test/unit/arbitrary/_internals/helpers/TokenizeRegex.spec.ts, packages/fast-check/test/unit/arbitrary/stringMatching.spec.ts
Supporting regex patterns such as `a|b|c` is key if we want to release `stringMatching` at some point. Adding such support is the aim of this PR.
=> ✨ Add support for disjunctions in regexes

.yarn/versions/feb84070.yml, packages/fast-check/src/arbitrary/_internals/helpers/TokenizeRegex.ts, packages/fast-check/src/arbitrary/stringMatching.ts, packages/fast-check/test/unit/arbitrary/_internals/helpers/TokenizeRegex.spec.ts, packages/fast-check/test/unit/arbitrary/stringMatching.spec.ts
The current tokenizer parsing the regexes passed to `stringMatching` was unable to correctly parse ^ and $. It now correctly does.
We still not really interpret the non-existance of them as a possible escape to create more data before or after the pattern but we will attempt to do so in the upcoming PRs.
=> ✨ Correctly parse ^ and $ in regex

.yarn/versions/6bfcbed8.yml, packages/fast-check/src/arbitrary/_internals/helpers/SanitizeRegexAst.ts, packages/fast-check/src/arbitrary/stringMatching.ts, packages/fast-check/test/unit/arbitrary/_internals/helpers/SanitizeRegexAst.spec.ts, website/docs/core-blocks/arbitraries/combiners/string.md
Up-to-now generating strings out of regexes not defining ^ and $ was equivalent to having them. It now differs!
=> ✨ Support generation of strings not constrained by ^ or $

.yarn/versions/35c176bc.yml, packages/fast-check/src/arbitrary/stringMatching.ts, packages/fast-check/test/unit/arbitrary/stringMatching.spec.ts
The flags i, u and y are still not supported yet.
=> ✨ Support regex flags: d, m and s

.yarn/versions/be583bed.yml, packages/fast-check/src/arbitrary/_internals/helpers/ReadRegex.ts, packages/fast-check/src/arbitrary/stringMatching.ts, packages/fast-check/test/unit/arbitrary/_internals/helpers/ReadRegex.spec.ts, packages/fast-check/test/unit/arbitrary/_internals/helpers/TokenizeRegex.spec.ts, packages/fast-check/test/unit/arbitrary/stringMatching.spec.ts
Regexes could be flagged as unicode ones by adding a small 'u' on them. When defined that way their behaviour defer a bit on some behaviours.
The most important change being that regexes start reading not byte by byte but code point by code point.
We just add support for them.
=> ✨ Support unicode regexes

.github/workflows/codeql-analysis.yml
=> 🔧 Fix configuration of CodeQL

.yarn/versions/ef87c51d.yml, packages/worker/src/internals/MainThreadRunner.ts, packages/worker/src/internals/SharedTypes.ts, packages/worker/src/internals/worker-pool/BasicPool.ts, packages/worker/src/internals/worker-pool/IWorkerPool.ts, packages/worker/src/internals/worker-pool/OneTimePool.ts, packages/worker/src/internals/worker-runner/NoWorkerRunner.ts, packages/worker/src/internals/worker-runner/WorkerRunner.ts, packages/worker/src/main.ts, packages/worker/test/internals/worker-pool/BasicPool.spec.ts, packages/worker/test/main.spec.ts
Up to now, one worker was always linked to a single predicate. With this PR it's now feasible to have the same worker able to run many predicates.
=> ♻️(worker) Allow support for multiple predicates per worker

.yarn/versions/69718570.yml, packages/worker/README.md, packages/worker/src/internals/MainThreadRunner.ts, packages/worker/src/internals/worker-pool/GlobalPool.ts, packages/worker/src/main.ts, packages/worker/test/main.properties.cjs, packages/worker/test/main.spec.ts
"file" isolation level will make `@fast-check/worker` able to re-use the same worker cross-properties. By doing so, we reduce the cost of running properties through workers as instead of requesting to spawn dedicated workers for the property we just use the ones already there is any.
=> ✨(worker) Add "file" isolation level

.yarn/versions/d43d3539.yml, packages/jest/README.md, packages/jest/package.json, packages/jest/src/jest-fast-check-worker.ts, yarn.lock
The package `@fast-check/jest` propose an experimental support for `@fast-check/worker`. We enriched this support to add the ability for the users to pass extra configuration options to `@fast-check/worker` at initialization time such as the isolationLevel and possibly others that might come in next iterations.
=> ✨(jest) Support passing options to worker

.yarn/versions/422c0d99.yml, packages/worker/README.md, website/docs/ecosystem.md
A typo reached the README file of `@fast-check/worker`. We patch it.
=> 📝(worker) Fix API error in README

.github/workflows/build-status.yml
In order to publish our package we need a version of npm supporting the `--provenance` flag. Unfortunately version 9.5 coming with node 18 does not, so we moved to node 20 as it comes with 9.6 and supports it without the manual global install of npm (it was a security isue for scorecard).
=> 🔒️ Drop raw install of npm

.yarn/versions/bccaa5bb.yml, packages/fast-check/src/arbitrary/_internals/mappers/UintToBase32String.ts, packages/fast-check/src/arbitrary/ulid.ts, packages/fast-check/src/fast-check-default.ts, packages/fast-check/test/e2e/NoRegression.spec.ts, packages/fast-check/test/e2e/__snapshots__/NoRegression.spec.ts.snap, packages/fast-check/test/unit/arbitrary/_internals/mappers/UintToBase32String.spec.ts, packages/fast-check/test/unit/arbitrary/ulid.spec.ts, website/docs/core-blocks/arbitraries/fake-data/identifier.md
Implements #4009
Adds arbitrary for `ulid`, according to the [ulid spec](https://github.com/ulid/spec).
=> ✨ Implement arbitrary for ulid

.yarn/versions/e40445ea.yml, CONTRIBUTING.md, packages/fast-check/src/arbitrary/_internals/helpers/DoubleHelpers.ts, packages/fast-check/src/arbitrary/_internals/helpers/FloatHelpers.ts, packages/fast-check/src/arbitrary/double.ts, packages/fast-check/src/arbitrary/float.ts
This replaces the (creative) loop-based implementation with a constant-time one. The number 1.234 is about 1100x faster and 1e30 is about 2300x faster.
If you're okay with this change I can do the same thing for double.
=> ⚡ Faster `decomposeFloat/Double`

.yarn/versions/54a4cdd6.yml, packages/fast-check/src/arbitrary/_internals/mappers/UintToBase32String.ts, packages/fast-check/src/arbitrary/ulid.ts
The current implementation of `ulid` was relying on many unneeded intermediate arrays to construct and deconstruct ulids. We just make it faster by relying on less intermediate arrays.
The change should reduce the memory footprint of ulids.
More to come with a partial revamp of some parts of the logic.
=> ⚡️ Drop some unneeded allocs in `ulid`

.yarn/versions/04697a61.yml, packages/fast-check/src/arbitrary/_internals/mappers/UintToBase32String.ts
=> ⚡️ Faster unmap for `ulid`

.yarn/versions/c8458015.yml, packages/fast-check/src/arbitrary/_internals/mappers/UintToBase32String.ts
Being able to unwrap and deconstruct data that could never be created by one arbitrary can lead to wrong shrinker from being selected and thus strange issues (edge cases but let's avoid them).
=> 🐛 Stop unwrapping `ulid` we cannot build

.yarn/versions/35875d1a.yml, packages/fast-check/src/arbitrary/_internals/mappers/UintToBase32String.ts, packages/fast-check/src/arbitrary/ulid.ts, packages/fast-check/test/unit/arbitrary/_internals/mappers/UintToBase32String.spec.ts
Here are some stats extracted from a benchmark:
```txt
┌─────────┬────────┬──────────────────────┬─────────────────────┬─────────────────────┐
│ (index) │  name  │         mean         │         p99         │        p999         │
├─────────┼────────┼──────────────────────┼─────────────────────┼─────────────────────┤
│    0    │ 'old'  │ 0.036524547798902726 │ 0.06470000091940165 │ 0.24509999994188547 │
│    1    │ 'new'  │ 0.02174825419917982  │ 0.04059999994933605 │ 0.24960000067949295 │
│    2    │ 'old2' │ 0.03769995739969145  │ 0.06599999964237213 │ 0.3251000000163913  │
│    3    │ 'new2' │ 0.022186629200091585 │ 0.04079999960958958 │ 0.29510000068694353 │
└─────────┴────────┴──────────────────────┴─────────────────────┴─────────────────────┘
```
Benchmark have been done using: …
=> ⚡️ Faster `ulid` mapper function

.yarn/versions/de5677c4.yml, packages/fast-check/src/arbitrary/double.ts, packages/fast-check/test/unit/arbitrary/__test-helpers__/FloatingPointHelpers.ts, packages/fast-check/test/unit/arbitrary/double.spec.ts, website/docs/core-blocks/arbitraries/primitives/number.md
Up-to-now, it was not possible to ask for double between min and max with either min or max or both not in the range.
Following the request #4046, we thought about it and started to offer ways to do so.
=> ✨ Support excluded min/max in `double`

.yarn/versions/9cf55ded.yml, packages/fast-check/src/arbitrary/float.ts, packages/fast-check/test/unit/arbitrary/float.spec.ts, website/docs/core-blocks/arbitraries/primitives/number.md
Up-to-now, it was not possible to ask for float  between min and max with either min or max or both not in the range.
Following the request #4046, we thought about it and started to offer ways to do so.
=> ✨ Support excluded min/max in `float`

packages/fast-check/test/unit/arbitrary/double.spec.ts, packages/fast-check/test/unit/arbitrary/float.spec.ts
=> ✅ Stabilize test related to NaN in exclusive mode

.yarn/versions/a60cfd09.yml, packages/fast-check/src/arbitrary/_internals/mappers/TimeToDate.ts, packages/fast-check/src/arbitrary/date.ts, packages/fast-check/test/unit/arbitrary/_internals/mappers/TimeToDate.spec.ts, packages/fast-check/test/unit/arbitrary/date.spec.ts, website/docs/core-blocks/arbitraries/primitives/date.md
Up-to-now, the arbitrary called `date()` was unable to generate "Invalid Date". Following this PR, it will be able to do so, if you provide it with the flag `noInvalidDate: false`.
In the next major version of fast-check, this flag will default to false (while today it defaults to true not to break existing clients).
Fixes #1064
=> ✨ Add support for "Invalid Date" in `date`

.yarn/versions/967d1489.yml, packages/fast-check/src/arbitrary/_internals/builders/AnyArbitraryBuilder.ts, packages/fast-check/src/arbitrary/_internals/mappers/KeyValuePairsToObject.ts, packages/fast-check/src/arbitrary/dictionary.ts, packages/fast-check/test/unit/arbitrary/_internals/mappers/KeyValuePairsToObject.spec.ts, packages/fast-check/test/unit/arbitrary/dictionary.spec.ts, website/docs/core-blocks/arbitraries/composites/object.md
For now, users will have to explicitly ask for it. But in the next major, the null-prototype will be the default.
=> ✨ Support null-proto in `dictionary`

.yarn/versions/97d78019.yml, packages/fast-check/src/arbitrary/_internals/builders/PartialRecordArbitraryBuilder.ts, packages/fast-check/src/arbitrary/_internals/mappers/ValuesAndSeparateKeysToObject.ts, packages/fast-check/src/arbitrary/record.ts, packages/fast-check/test/unit/arbitrary/_internals/builders/PartialRecordArbitraryBuilder.spec.ts, packages/fast-check/test/unit/arbitrary/_internals/mappers/ValuesAndSeparateKeysToObject.spec.ts, packages/fast-check/test/unit/arbitrary/record.spec.ts, website/docs/core-blocks/arbitraries/composites/object.md
For now, users will have to explicitly ask for it. But in the next major, the null-prototype will be the default.
=> ✨ Support null-proto in `record`

packages/fast-check/test/unit/arbitrary/date.spec.ts
=> 💚 Rework broken test on `date` (retry)

.yarn/versions/fdc3fd4c.yml, packages/fast-check/postbuild/main.cjs
=> 🐛 Fix typings for node native esm

.yarn/versions/3a6c6eb7.yml, packages/packaged/README.md, packages/packaged/package.json, packages/packaged/src/packaged.ts, packages/packaged/tsconfig.json, packages/packaged/tsconfig.publish.json, packages/packaged/tsconfig.publish.types.json, yarn.lock
Previous implementation was relying on building a tar-ball, then reading it in order to know which files are required for the package.
This new implementation is way lighter and only checks the files on the fly wihtout needing any intermediate tarball to be created and read.
=> ⚡️(packaged) No intermediate tarball

.github/workflows/build-status.yml
Our current final job "All checks passed" as considered as OK when skipped. We defined that job to easily capture the fact that all our required jobs passed. Unfortunately GitHub considers that skipped or success are OK statuses for required jobs.
As a consequence, we adopted another pattern made of two jobs. One that should aggregate the status of the required ones into a: success or skipped. And one translating the skip into a failed.
=> 👷 Mark final check as failed and not skipped

package.json
CI is currently failing on main branch only. PRs themselves pass well but once they reach main nothing passes anymore.
They start to fail when untaring the generated packages.
This PR tries to do something to avoid the issue. But as it cannot be reproduced except on main, let's see how it will do.
=> 💚 Attempt to patch untar step

packages/jest/package.json, packages/poisoning/package.json, packages/vitest/package.json, packages/worker/package.json, website/package.json, yarn.lock
When passing Yarn in PnP mode, we got reported several issues in the way we were declaring some dependencies. More preciselly we supposed they were there while we never explicitely pulled them for the project.
This PR makes sure we don't miss any and always explicitely declare them. It will reduce the amount of changes needed for the PnP switch.
Satellite PR for #4368
=> 💚 Add missing but directly called dependencies

packages/jest/test/jest-fast-check.spec.ts
Up-to-now when changing the test runner used internally by Jest, we were passing it the full path to the runner and its entry point. This approach proved fragile when we attempted to switch to Yarn in PnP mode.
This PR change the way we declare the runner: we stop passing the path to the entry point and just pass its name.
Satellite PR for #4368
=> ✅(jest) Declare jest-jasmine2 by name not path

.yarn/versions/fa1f000f.yml, packages/packaged/src/packaged.ts, packages/packaged/test/packaged.spec.ts
Up-to-now, in order to delete a directory we were scanning the whole directory item by item. With this new version, as long as the directory is known not to include any published files, we delete it with its content without having to scan it (rm recursively deletes it for us).
It changed the content returned by removed. Now it may inlcude names of parent directories without listing any of the child files in it.
=> ⚡️(packaged) Bulk delete directory and content

.github/workflows/build-status.yml
Parallel "git" command executions suddenly started to fail in CI. As it does not seem to be something really supported, let's run the commands one after the other to avoid flaky executions in CI.
=> 💚 No parallel "git" command

.yarn/versions/ea83dec9.yml, packages/jest/src/jest-fast-check-worker.ts, packages/jest/test/jest-fast-check.spec.ts
=> 🏷️(jest) Prefer "import type" over raw "import"

.yarn/versions/9d986e7d.yml, packages/ava/src/ava-fast-check.ts
=> 🏷️(ava) Prefer "import type" over raw "import"

.yarn/versions/0009b7e2.yml, packages/expect-type/src/main.d.ts, packages/expect-type/test/internals.spec.ts
=> 🏷️(expect-type) Prefer "import type" over raw "import"

.yarn/versions/e3d4b33a.yml, packages/poisoning/src/internals/CaptureAllGlobals.ts, packages/poisoning/src/internals/FilterNonEligibleDiffs.ts, packages/poisoning/src/internals/TrackDiffsOnGlobal.ts, packages/poisoning/src/internals/types/AllGlobals.ts, packages/poisoning/test/internals/CaptureAllGlobals.spec.ts, packages/poisoning/test/internals/FilterNonEligibleDiffs.spec.ts, packages/poisoning/test/internals/TrackDiffsOnGlobal.spec.ts
=> 🏷️(poisoning) Prefer "import type" over raw "import"

.yarn/versions/7b36cbca.yml, packages/jest/package.json, packages/worker/src/internals/MainThreadRunner.ts, packages/worker/src/internals/NoopWorkerProperty.ts, packages/worker/src/internals/SharedTypes.ts, packages/worker/src/internals/worker-pool/GlobalPool.ts, packages/worker/src/internals/worker-pool/OneTimePool.ts, packages/worker/src/internals/worker-runner/NoWorkerRunner.ts, packages/worker/src/internals/worker-runner/WorkerRunner.ts, packages/worker/src/main.ts, packages/worker/test/e2e/blockEventLoop.spec.ts, packages/worker/test/e2e/concurrentAssert.spec.ts, packages/worker/test/e2e/failing.spec.ts, packages/worker/test/e2e/passing.spec.ts, packages/worker/test/e2e/predicateIsolation.spec.ts, packages/worker/test/e2e/propertyIsolation.spec.ts, packages/worker/test/e2e/unregistered.spec.ts, packages/worker/test/internals/lock/Lock.spec.ts, packages/worker/test/internals/worker-pool/BasicPool.spec.ts, yarn.lock
=> 🏷️(worker) Prefer "import type" over raw "import"

.yarn/versions/6b043ab6.yml, packages/ava/package.json, packages/ava/test.sh, packages/ava/test/testProp.js, yarn.lock
Following the issue #4432, I wanted to sela a bit more the behaviour expected our not by `@fast-check/ava`.
Some behviours such as:
- not returning nor asserting anything
- returning true without asserting anyhing
- returninfg false
- returning an observable value
Were improperly covered by tests.
We also leveraged this PR to make our tests on ava safer, easier to evolve...
=> ✅(ava) Extend test coverage to no-assertions cases and observables

.yarn/versions/faafb800.yml, packages/ava/src/ava-fast-check.ts, packages/ava/test.sh, packages/ava/test/testProp.js
Our current implementation for ava was suffering for a bad support of `fc.pre`. It considers them as real issues and ignored their "skip meaning".
With that PR we fix that long term bug and makes `fc.pre` behave as it does in usual fast-check.
Fixes #4432
=> 🐛(ava) Properly support `fc.pre`, allow unsuccessful plans on unmatched preconditions

.yarn/versions/ad471922.yml, packages/ava/README.md
The package has some distinctions with bare-metal fast-check. We document them futher in this PR to make users aware that some specific behaviours might adopt a different behaviour when executed manually or via the ava glueing of fast-check.
Related to #4432
=> 📝(ava) Document distinctions with raw fast-check

.yarn/versions/850a3476.yml, packages/fast-check/README.md
=> 📝 Prefer import notation over require for README

.yarn/versions/c752060b.yml, packages/worker/src/internals/NoopWorkerProperty.ts
Starting at the version 4 of fast-check, properties will have to define `runBeforeEach` and `runAfterEach` (related PR #4208). We just adapted an internal of the worker package to be compatible with that. It's mostly a typing stuff as not doing so would result in the same behaviour at runtime (aka not implemented vs not a function).
=> ♻️(worker) Prepare worker's internals to Property type of fast-check 4

.yarn/versions/1fb65208.yml, packages/fast-check/test/e2e/NoRegressionStack.spec.ts, packages/fast-check/test/e2e/__snapshots__/NoRegressionStack.spec.ts.snap
We now ignore lines in the snapshots captured in the E2E ensuring we can capture some stacks.
=> ✅ More stable snapshot tests on stack traces

.yarn/versions/784a780f.yml, packages/fast-check/src/arbitrary/record.ts, packages/fast-check/test-types/main.ts, packages/fast-check/test/e2e/NoRegression.spec.ts, packages/fast-check/test/e2e/arbitraries/RecordArbitrary.spec.ts, packages/fast-check/test/unit/arbitrary/__test-helpers__/FloatingPointHelpers.ts, packages/fast-check/test/unit/arbitrary/_internals/builders/TypedIntArrayArbitraryBuilder.spec.ts, packages/fast-check/test/unit/arbitrary/double.spec.ts, packages/fast-check/test/unit/arbitrary/float.spec.ts, packages/fast-check/test/unit/arbitrary/record.spec.ts, website/docs/core-blocks/arbitraries/composites/object.md
**:boom: Breaking change**
Initially `record` came with `withDeletedKeys`, but quickly we received the need to have a better granularity level to deal with keys to keep or not and so `requiredKeys` came.
Now, that we have it for some time, we want to drop `withDeletedKeys` as it tends to add complexity to the code and the API.
A migration path and possibly some scripts to help users to run the change might be provided in the future. For now the recommendation would be to replace: `withDeletedKeys: true` by `requiredKeys: []` and `withDeletedKeys: false` by nothing or `requiredKeys: [...here all the keys...]`.
=> 🔥 Remove `withDeletedKeys` from `record`

.yarn/versions/9f104530.yml, packages/fast-check/test/e2e/NoRegressionStack.spec.ts, packages/fast-check/test/e2e/__snapshots__/NoRegressionStack.spec.ts.snap
While for now, it seems that not all helpers in Jest capture the cause properly, it's worth backing us with a test (even if not that verbose for now).
=> ✅ Add cause flag onto snapshot tests checking stack traces

packages/fast-check/src/check/property/AsyncProperty.generic.ts, packages/fast-check/src/check/property/Property.generic.ts
In theory, it should not be considered as a breaking change but as it's rather easy to return null instead of undefined without seeing it (when not using TS it can be easy) we prefer to be safe.
Fixes #4444
=> ⚡️ Faster property::run with strict equality checks

.yarn/versions/f1098851.yml, packages/fast-check/test/e2e/NoRegression.spec.ts, packages/fast-check/test/e2e/NoRegressionBigInt.spec.ts, packages/fast-check/test/e2e/NoRegressionStack.spec.ts, packages/fast-check/test/e2e/__snapshots__/NoRegressionStack.spec.ts.snap, packages/fast-check/test/e2e/__test-helpers__/StackSanitizer.ts
The current snapshots implying stacktraces were luckily never displaying any stack. Indeed stacks never get displayed for the specs NoRegression and NoRegressionBigInt.
We want to make these tests able to support stacks and sanitize them as we already do for NoRegressionStack. As a consequence we extracted the helper defined in NoRegressionStack and used it for the others.
=> ✅ Better snapshots tests implying stacktraces

website/docs/tutorials/detect-race-conditions/one-step-closer-to-real-usages.mdx
=> 📝 Rework section on `waitAll` in the tutorial

packages/fast-check/src/arbitrary/date.ts, packages/fast-check/test/unit/arbitrary/_internals/mappers/TimeToDate.spec.ts, packages/fast-check/test/unit/arbitrary/date.spec.ts, website/docs/core-blocks/arbitraries/composites/object.md, website/docs/core-blocks/arbitraries/primitives/date.md
**💥 Breaking change**
In v3, `fc.date` was not producing "Invalid Date" values by default. One has to specify `noInvalidDate: false` to get some. With this PR we now default the flag to false when not specified: in other words, the new default will be to produce invalid dates except asked explicitly not to.
After that change, if you want not to produce "Invalid Date", you'll have to use:
```js
// in v3, it was only producing valid dates
fc.date()
// equivalent in v4
fc.date({noInvalidDate: true})
//---
// in v3, including invalid dates required users to pass an extra constraint to the arbitrary
fc.date({noInvalidDate: false})
// equivalent in v4
fc.date()
```
You can also prepare yourself to v4 by already toggling: `noInvalidDate: false` on your `fc.date`.
=>  💥 Include invalid dates by default

packages/fast-check/src/check/runner/configuration/Parameters.ts, packages/fast-check/src/check/runner/configuration/QualifiedParameters.ts, packages/fast-check/src/check/runner/utils/RunDetailsFormatter.ts, packages/fast-check/test/e2e/NoRegressionStack.spec.ts, packages/fast-check/test/e2e/__snapshots__/NoRegression.spec.ts.snap, packages/fast-check/test/e2e/__snapshots__/NoRegressionBigInt.spec.ts.snap, packages/fast-check/test/e2e/__snapshots__/NoRegressionStack.spec.ts.snap, packages/fast-check/test/e2e/__test-helpers__/StackSanitizer.ts, packages/fast-check/test/unit/check/runner/Runner.spec.ts, packages/fast-check/test/unit/check/runner/configuration/QualifiedParameters.spec.ts, packages/worker/test/e2e/__test-helpers__/ThrowWithCause.ts, packages/worker/test/e2e/blockEventLoop.spec.ts, packages/worker/test/e2e/failing.spec.ts, packages/worker/test/e2e/noWorker.spec.ts, packages/worker/test/e2e/predicateIsolation.spec.ts, packages/worker/test/e2e/propertyIsolation.spec.ts, packages/worker/test/e2e/unregistered.spec.ts
**💥 Breaking change**
Until now, fast-check have been merging the content and stack of the original Error that caused the property to fail into its own Error. With the recent (2022) introduction of cause on Errors, this complex logic can be dropped in favor of the native cause mechanism.
This PR makes cause mode the default. Before this PR, toggling it was possible via `errorWithCause: true` on `fc.assert`.
Given not all test runners properly support causes attached to the Error, we offer a fallback for users willing to preserve the old behaviour. It can be toggled via `includeErrorInReport: true` on `fc.assert`.
Related to #4416.
=>  💥 Error with cause by default

.yarn/versions/64364831.yml, packages/fast-check/src/arbitrary/object.ts
Our current implementation of `fc.object` with `withNullPrototype: true` was not producing any null-prototype instances at the root. With that fix, it will now produce some.
As the change fixes a slightly minor bug that could cause replays to break (the version including it, would not replay to the same values), it might not be included into a patch but wait for a minor).
=> 🐛 Also produce null-prototype at root level of generated `object` when requested to

.github/workflows/build-status.yml
Reverts dubzzz/fast-check#4537
Waiting for https://github.com/actions/download-artifact/issues/249, so far the bump is very unstable, I cannot keep it.
=> ⬇️ Downgrade actions/{download,upload}-artifact action to v3

.yarn/versions/3036316f.yml, website/docs/ecosystem.md
Hello from Nantes 🐘 !
First off all, thanks for this incredible library !
I made a connector for [idonttrustlikethat](https://github.com/AlexGalays/idonttrustlikethat), it converts validators into arbitraries. Do you mind if I add it to the ecosystem documentation page ?
=> 📝 Add `idonttrustlikethat-fast-check` in ecosystem.md

packages/fast-check/src/arbitrary/_internals/builders/CharacterRangeArbitraryBuilder.ts, packages/fast-check/src/arbitrary/_internals/mappers/UintToBase32String.ts, packages/fast-check/src/utils/stringify.ts
As our next major is close enough, let's wait it to drop such internals from the exports. Even if they are not linked to any officially exposed entry-points they might be referenced by some users.
Fixes #4552
=> 🔥 Un-export internals found by Knip

.yarn/versions/a0f8cbb4.yml, packages/worker/README.md, packages/worker/package.cjs-template.json, packages/worker/package.esm-template.json, packages/worker/package.json
The build chain of `@fast-check/worker` has been CommonJS-based since day 1. With ESM moving forward in the ecosystem, it's time to move ourselves to the new standard and adapt our build chains to ESM.
Another subtle impact is that it would impose our users to run at least Node ≥12.17.0. But it was already a requirement for this package.
As such we consider it as a breaking change.
**_Potential …
=> 👷(worker) Move build chain to ESM

.yarn/versions/2561d1b5.yml, packages/vitest/package.cjs-template.json, packages/vitest/package.esm-template.json, packages/vitest/package.json
The build chain of `@fast-check/vitest` has been CommonJS-based since day 1. With ESM moving forward in the ecosystem, it's time to move ourselves to the new standard and adapt our build chains to ESM.
Another subtle impact is that it would impose our users to run at least Node ≥12.17.0. But it was already a requirement for this package.
As such we consider it as a breaking change.
**_Potential …
=> 👷(vitest) Move build chain to ESM

.yarn/versions/e8f05fd9.yml, packages/expect-type/.gitignore, packages/expect-type/package.json, packages/expect-type/src/cjs/main.js, packages/expect-type/src/cjs/package.json, packages/expect-type/src/esm/main.js, packages/expect-type/src/esm/package.json, packages/expect-type/src/main.js
The build chain of `@fast-check/expect-type` has been CommonJS-based since day 1. With ESM moving forward in the ecosystem, it's time to move ourselves to the new standard and adapt our build chains to ESM.
Another subtle impact is that it would impose our users to run at least Node ≥12.17.0.
As such we consider it as a breaking change.
=> 👷(expect-type) Move build chain to ESM

packages/ava/package.cjs-template.json, packages/ava/package.esm-template.json, packages/ava/package.json, packages/ava/test/ava.config.cjs, packages/ava/test/ava.config.js, packages/ava/test/testProp.js
The build chain of `@fast-check/ava` has been CommonJS-based since day 1. With ESM moving forward in the ecosystem, it's time to move ourselves to the new standard and adapt our build chains to ESM.
Another subtle impact is that it would impose our users to run at least Node ≥12.17.0. But it was already a requirement due to ava itself: …
=> 👷(ava) Move build chain to ESM

packages/jest/README.md, packages/jest/package.cjs-template.json, packages/jest/package.esm-template.json, packages/jest/package.json, packages/jest/test/jest-fast-check.spec.ts
The build chain of `@fast-check/jest` has been CommonJS-based since day 1. With ESM moving forward in the ecosystem, it's time to move ourselves to the new standard and adapt our build chains to ESM.
Another subtle impact is that it would impose our users to run at least Node ≥12.17.0. But it was already a need for this package due to its dependencies.
As such we consider it as a …
=> 👷(jest) Move build chain to ESM

.yarn/versions/7a5e69e8.yml, packages/vitest/babel.config.cjs, packages/vitest/jest.config.js, packages/vitest/package.json, packages/vitest/test/vitest-fast-check.spec.ts, yarn.lock
=> 🔧(vitest) Migrate jest to esm

packages/jest/babel.config.cjs, packages/jest/jest.config.js, packages/jest/package.json, packages/jest/test/jest-fast-check.spec.ts, yarn.lock
=> 🔧(jest) Migrate jest to esm

website/src/components/HomepageContributors/index.js, website/src/components/HomepageHeader/index.js
=> 🚨 Fix console errors of website

website/src/components/HomepageHeader/styles.module.css
Before the fix #4712, the Call To Action (aka CTA) for "Quick Start - 5min" used to be after a 1.25rem spacing (20px).
The fix, dropped that spacing putting the CTA button to close from its preceding title. We just put back (part of) this spacing.
=> 💄 Add extra spacing on top of CTA

packages/fast-check/src/arbitrary/_internals/implementations/SchedulerImplem.ts
**👀 Potentially risky** (risk: low)
The PR #4714 started to rewrite part of the method to make it easier to evolve. In its original implementation each scheduled item was defining its own error handling on the side and a global error handing was responsible to capture any last crash.
This new approach puts the local item-related error handling in the then-sequence and not forked from it.
In theory, it should not break anything, but as it plays with Promises we can have unwantingly added some extra then step or dropped one. As such it should probably not be released outside of a minor or major version.
=> 🐛 Better rejection handling in `scheduleSequence`

packages/fast-check/test/unit/arbitrary/_internals/implementations/SchedulerImplem.spec.ts
No test failed at the moment but the error started to be problematic with #3891. In other words, we may have unwantingly hide real errors from our users and with #3891 (as a whole) we fix that hiding.
=> 💚 Clean unhandled rejections in tests for scheduler

packages/fast-check/src/arbitrary/_internals/implementations/SchedulerImplem.ts
**👀 Potentially risky** (risk: low)
With #3891, our target is to make scheduling faster. Scheduling is one of the built-in arbitrary provided by fast-check. It aims to ease detection of race-conditions by offering a simple way to detect such issues in your code.
Up-to-now the code was doing a bit too many await/then letting it give back the hand many times in a row while it could have been faster to take it back. Additionally, this past behaviour (that we are trying to fix with many PRs) used to be strange as awaiting 1 was ok, but 10-times was not. More precisely there was a number of await working and passed this number it stopped to work as usual and users started to need to use other approaches (drop the `waitAll`).
This set of PRs not only addresses a potential perf concern but also …
=> ⚡️ Faster scheduling of `scheduleSequence`

packages/fast-check/src/arbitrary/_internals/implementations/SchedulerImplem.ts, packages/fast-check/test/unit/arbitrary/_internals/implementations/SchedulerImplem.spec.ts, website/docs/tutorials/detect-race-conditions/snippets.spec.mjs
**💥 Breaking change**
This PR makes schedulers faster. By being faster it means that code that was previously passing may start to fail. Additionally it may predates `waitAll` and makes it not working in some cases that relied on this lucky slow scheduler.
The new scheduler implementation will try to be as fast as possible and skip as few as possible frames. In this change scheduler takes action in places where it used not to because it was waiting for no reasons.
Recreating #3891
=> ⚡️ Speed-up race-condition schedulers

.github/workflows/build-status.yml, website/.gitignore, website/package.json, website/prebuild/optimize-images.mjs, website/src/components/HomepageContributors/index.js, website/src/components/HomepageQuotes/index.js, yarn.lock
Our current version of https://fast-check.dev/ is badly performing on https://www.websitecarbon.com/. It got an F for the homagepage but a good grade on others.
Most of the problem comes from our numerous images assets:
- there are many of them to load
- they are not optimized in size
The current PR is making sure we optimize them beforehand to deliver an optimized version of our assets.
=> ⚡️ Optimize image assets on homepage

.yarn/versions/bbb17765.yml, packages/fast-check/src/check/precondition/Pre.ts
By making `fc.pre` an assertion function TypeScript can narrow types based on the condition. For example:
const item: number | undefined = numberArray[randomIndex]
fc.pre(item !== undefined)
item // narrowed type: number
If `fc.pre` is not an assertion function, we have to do an additional (redundant) check to convince TypeScript that `item` is not `undefined`.
See: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#assertion-functions
I marked this change as "decline" but I'm not sure what's appropriate. There is no runtime impact and the API hasn't really changed either. The return type is technically still `void`.
=> Make `fc.pre` an assertion function

website/docusaurus.config.ts, website/src/components/HomepageHeader/index.js, website/src/components/HomepageHeader/styles.module.css
=> 💄 Better assets on the homepage of the website

packages/fast-check/CHANGELOG.md, website/blog/2024-03-04-whats-new-in-fast-check-3-16-0/index.md, website/blog/2024-03-04-whats-new-in-fast-check-3-16-0/pagespeed.png
=> 📝 Official release note of 3.16.0

.yarn/versions/a6ab7de6.yml, packages/fast-check/package.json, packages/fast-check/src/random/generator/Random.ts, packages/fast-check/test/unit/arbitrary/__test-helpers__/RandomHelpers.ts, yarn.lock
In the context of https://github.com/dubzzz/fast-check/pull/4063, we need to have an access onto the internal state of the PRNG backing the instance of `Random` in order to be able to serialize it and recreate the "exact" same instance of `Random` on destination (another worker thread).
The current PR adds a `getState` method on `Random`.
Adding it should be enough to fulfill the needs of https://github.com/dubzzz/fast-check/pull/4063. But we will wait for it to be confirmed before releasing any minor version including that change.
=> ✨ Expose internal state of the PRNG from `Random`

.yarn/versions/1488efe6.yml, packages/fast-check/src/arbitrary/_internals/helpers/DepthContext.ts, packages/fast-check/src/check/arbitrary/definition/Value.ts, packages/fast-check/src/check/precondition/PreconditionFailure.ts, packages/fast-check/src/random/generator/Random.ts, packages/fast-check/src/stream/Stream.ts
=> internalise private stuff, fixing dual types incompatibility

.yarn/versions/4949103f.yml, packages/fast-check/package.json, packages/fast-check/vitest.unit.config.mjs, yarn.lock
Instanbul used to be the default when we relied on Jest. V8 having its own coverage measurements, we are trying to move to it and to see how much it will impact our coverage.
=> ✅ Move to v8 for coverage

.yarn/versions/bb14e24d.yml, packages/fast-check/src/arbitrary/_internals/helpers/DoubleOnlyHelpers.ts, packages/fast-check/src/arbitrary/double.ts, packages/fast-check/test/unit/arbitrary/_internals/helpers/DoubleOnlyHelpers.spec.ts, website/docs/core-blocks/arbitraries/composites/typed-array.md, website/docs/core-blocks/arbitraries/primitives/number.md
Related to #4831
I still have a bit of refinement to do around it, but I'll do in next PRs:
- produced range is still too large
- no integration layer for tests
- floats
=> ✨ Add option to produce non-integer on `double`

.yarn/versions/814740f1.yml, packages/fast-check/src/arbitrary/_internals/helpers/DoubleOnlyHelpers.ts, packages/fast-check/test/unit/arbitrary/_internals/helpers/DoubleOnlyHelpers.spec.ts
=> ⚡️ More optimal `noInteger` on `double`

.yarn/versions/f365d394.yml, packages/fast-check/src/arbitrary/_internals/helpers/DoubleOnlyHelpers.ts, packages/fast-check/src/arbitrary/_internals/helpers/FloatOnlyHelpers.ts, packages/fast-check/src/arbitrary/_internals/helpers/FloatingOnlyHelpers.ts, packages/fast-check/src/arbitrary/float.ts, packages/fast-check/test/unit/arbitrary/__test-helpers__/FloatingPointHelpers.ts, packages/fast-check/test/unit/arbitrary/_internals/helpers/FloatOnlyHelpers.spec.ts, packages/fast-check/test/unit/arbitrary/float.spec.ts, website/docs/core-blocks/arbitraries/composites/typed-array.md, website/docs/core-blocks/arbitraries/primitives/number.md
=> ✨ Add option to produce non-integer on `float`

.yarn/versions/fe923812.yml, packages/fast-check/test/unit/arbitrary/__test-helpers__/FloatingPointHelpers.ts
=> 💚 Stabilize tests of `double` on small ranges

.yarn/versions/eac5c04e.yml, packages/fast-check/src/check/precondition/PreconditionFailure.ts, packages/fast-check/src/check/symbols.ts, packages/fast-check/src/utils/stringify.ts, packages/fast-check/test/unit/check/precondition/Pre.spec.ts, packages/fast-check/test/unit/check/symbols.spec.ts, packages/fast-check/test/unit/utils/stringify.spec.ts
fast-check was badly behaving on cloning method, custom toString and assertions linked to pre when several versions of it were running at the same time.
One of the case for that issue is ES module and CommonJS being mixed in the same test and leading fast-check to be loaded once in ESM and once in CJS.
Another case is that user relies on two versions of fast-check due to a dependency forcing a version that is not the same as the one requested by the user or by another dependency (not the same meaning not compatible semver ranges).
Fixes #4845
=> 🐛 Better interrupt between multiple versions

packages/fast-check/src/arbitrary/constant.ts, packages/fast-check/test/e2e/RecursiveStructures.spec.ts, packages/fast-check/test/unit/arbitrary/webUrl.spec.ts
As recommended by https://github.com/dubzzz/fast-check/issues/4047, let's leverage const generics to make usage of `constant` even simpler for TS users.
Not really a breaking change on its own but given we play with types and change the way we declare some, let's be safe and pack this change with other "next major" devs.
**Advanced**
=> 🏷️ Better typings for `constant`

website/docs/introduction/getting-started.md
Updates Getting Started > Arbitrary section in docs. Fixes a grammatical error and updates the sentence for conciseness. =)
=> 📝 Update Getting Started section in docs

.yarn/versions/5d397bcb.yml, examples/003-misc/mazeGenerator/main.spec.ts, packages/fast-check/src/arbitrary/_internals/builders/CompareFunctionArbitraryBuilder.ts, packages/fast-check/src/arbitrary/func.ts, packages/fast-check/src/arbitrary/noShrink.ts, packages/fast-check/src/fast-check-default.ts, packages/fast-check/test/e2e/Timeout.spec.ts, packages/fast-check/test/unit/arbitrary/__test-helpers__/ArbitraryAssertions.ts, packages/fast-check/test/unit/arbitrary/commands.spec.ts, packages/fast-check/test/unit/check/runner/Sampler.spec.ts, website/docs/advanced/fake-data.md, website/docs/core-blocks/arbitraries/combiners/any.md
While `noShrink` used to be a thing directly provided on the arbitrary since version 0.0.9, we want to extract it as an independant arbitrary.
Such extraction would allow us to reduce the API surface of the arbitraries to a smaller subset of methods. Aim being to reduce as much of possible the API users will have to deal with from the arbitrary itself.
Related to the PR #4162
**Advanced**
=> ✨ Introduce new `fc.noShrink` arbitrary

.yarn/versions/10482a59.yml, examples/003-misc/mazeGenerator/main.spec.ts, packages/fast-check/src/arbitrary/boolean.ts, packages/fast-check/src/arbitrary/noBias.ts, packages/fast-check/src/fast-check-default.ts, packages/fast-check/test/e2e/RandomEnough.spec.ts, packages/fast-check/test/e2e/arbitraries/BigIntArbitrary.spec.ts, packages/fast-check/test/e2e/arbitraries/DoubleArbitrary.spec.ts, packages/fast-check/test/e2e/arbitraries/FloatArbitrary.spec.ts, packages/fast-check/test/unit/arbitrary/_internals/implementations/SchedulerImplem.spec.ts, website/docs/advanced/fake-data.md, website/docs/core-blocks/arbitraries/combiners/any.md, website/docs/core-blocks/arbitraries/primitives/number.md
While `noBias` used to be a thing directly provided on the arbitrary since version 1.1.0, we want to extract it as an independant arbitrary.
Such extraction would allow us to reduce the API surface of the arbitraries to a smaller subset of methods. Aim being to reduce as much of possible the API users will have to deal with from the arbitrary itself.
**Advanced**
=> ✨ Introduce new `fc.noBias` arbitrary

.yarn/versions/77d32bc6.yml, packages/fast-check/src/arbitrary/limitShrink.ts, packages/fast-check/src/fast-check-default.ts, packages/fast-check/test/e2e/NoRegression.spec.ts, packages/fast-check/test/e2e/StateFullArbitraries.spec.ts, website/docs/core-blocks/arbitraries/combiners/any.md
We align the API of `limitShrink` with other arbitraries referencing compulsory settings. Instead of asking htem to be provided via an object/record, these options are passed as dedicated parameters.
We follow the same logic for `limitShrink`.
**Advanced**
=> ✨ Simplify `limitShrink` before releasing

.yarn/versions/4c50fb71.yml, packages/fast-check/src/arbitrary/_internals/mappers/VersionsApplierForUuid.ts, packages/fast-check/src/arbitrary/uuid.ts, packages/fast-check/src/fast-check-default.ts, packages/fast-check/test/unit/arbitrary/_internals/mappers/VersionsApplierForUuid.spec.ts, packages/fast-check/test/unit/arbitrary/uuid.spec.ts, website/docs/core-blocks/arbitraries/fake-data/identifier.md
This PR adds the ability to customize the versions of the UUIDs produced by `uuid` without having to rely on its counterpart version `uuidV`. It paves the way for the future drop of `uuidV`.
Follow-up of #5172
Related to issues: #5104 and #5103
**Advanced**
=> ✨ Customize versions directly from `uuid`

.github/workflows/build-status.yml
Until now our publication script was unable to publish on a tag not being "latest" (the default when no tag specified). More precisely, unable except changing the script before publishing.
With that change we make it automatic. Things on main will still be issued on latest, things on next- will be flagged for next and all the rest (normally backports) will fall in the legacy bucket.
**Advanced**
=> 👷 Support npm publish on other tags

.yarn/versions/23643846.yml, packages/vitest/src/internals/TestBuilder.ts
In order to toggle ON the flag `isolatedDeclarations` and allow us to use something else than tsc to build our project (not sure we will do one day), we start to make some types more explicit on our exported symbols.
**Advanced**
=> ♻️(vitest) Add missing types on exported

.yarn/versions/4e927b19.yml, packages/fast-check/src/check/symbols.ts, packages/fast-check/src/stream/Stream.ts, packages/fast-check/src/utils/stringify.ts
In order to toggle ON the flag `isolatedDeclarations` and allow us to use something else than tsc to build our project (not sure we will do one day), we start to make some types more explicit on our exported symbols.
This PR does not fix everything as some of the fixes would require some minor (subtle) breaking changes!
**Advanced**
=> ♻️ Add missing types on exported

.yarn/versions/2d16b9e2.yml, packages/fast-check/src/arbitrary/ascii.ts, packages/fast-check/src/arbitrary/asciiString.ts, packages/fast-check/src/arbitrary/base64.ts, packages/fast-check/src/arbitrary/char.ts, packages/fast-check/src/arbitrary/char16bits.ts, packages/fast-check/src/arbitrary/fullUnicode.ts, packages/fast-check/src/arbitrary/fullUnicodeString.ts, packages/fast-check/src/arbitrary/hexa.ts, packages/fast-check/src/arbitrary/hexaString.ts, packages/fast-check/src/arbitrary/string16bits.ts, packages/fast-check/src/arbitrary/stringOf.ts, packages/fast-check/src/arbitrary/unicode.ts, packages/fast-check/src/arbitrary/unicodeString.ts, website/docs/core-blocks/arbitraries/combiners/string.md, website/docs/core-blocks/arbitraries/primitives/char.md, website/docs/core-blocks/arbitraries/primitives/string.md
This PR deprecates all our past arbitraries of single characters. We recommend to replace them by arbitraries on strings with `minLength` and `maxLength` both set to `1`.
This PR also deprecates all string arbitraries except `string`, `base64String`, `stringMatching` and `mixedCase`. All the deprecated arbitraries could now be expressed using `fc.string` with a specific `unit`. Here are our recommended migration paths:
- `asciiString` can be replaced by `fc.string({ unit: 'binary-ascii' })` (identical behavior).
- `unicodeString` does not have direct equivalent in the recommended world, we either recommend you to build a custom unit arbitrary (see 1 below) or to rely on existing units provided by `fc.string`. Depending on what you wanted to achieve when selecting …
=> 🗑️ Mark as deprecated most of char and string arbitraries

.yarn/versions/0a0bca50.yml, packages/fast-check/src/arbitrary/bigIntN.ts, packages/fast-check/src/arbitrary/bigUint.ts, packages/fast-check/src/arbitrary/bigUintN.ts, website/docs/core-blocks/arbitraries/primitives/bigint.md
Starting at 3.22.0 the usage of `bigIntN`, `bigUintN` and `bigUint` will be discouraged. We instead recommend calling `bigInt` with appropriate `min` and `max` values when relevant.
**Advanced**
=> 🗑️ Deprecate `bigInt`'s alternatives

packages/fast-check/src/arbitrary/_internals/helpers/SlicesForStringBuilder.ts, packages/fast-check/src/check/arbitrary/definition/Arbitrary.ts, packages/fast-check/src/utils/apply.ts, packages/fast-check/src/utils/globals.ts, packages/fast-check/src/utils/stringify.ts, packages/fast-check/test/e2e/NoRegression.spec.ts, packages/fast-check/test/e2e/NoStackOverflowOnShrink.spec.ts, packages/fast-check/test/e2e/Poisoning.spec.ts, packages/fast-check/test/e2e/ReplayFailures.spec.ts, packages/fast-check/test/e2e/arbitraries/ObjectArbitrary.spec.ts, packages/fast-check/test/unit/arbitrary/__test-helpers__/ArbitraryAssertions.ts, packages/fast-check/test/unit/arbitrary/_internals/builders/AnyArbitraryBuilder.spec.ts, packages/fast-check/test/unit/arbitrary/commands.spec.ts, packages/fast-check/test/unit/arbitrary/stringMatching.spec.ts, packages/fast-check/test/unit/utils/stringify.spec.ts, packages/poisoning/test/main.spec.ts
There is no more need to specify anything when catching an error without treating it.
Let's adopt "Optional catch binding" in our codebase! Available since Node 10.
Related to #5282
**Important** - Once reaching next-3.23.0, we should add back the eslint configuration: `'@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_', caughtErrors: 'none' }],`.
**Advanced**
=> 🔥 Drop unneeded catch param

.changeset/mighty-teachers-listen.md, packages/fast-check/src/arbitrary/_internals/StringUnitArbitrary.ts, packages/fast-check/src/arbitrary/_internals/helpers/GraphemeRangesHelpers.ts, packages/fast-check/src/arbitrary/_internals/mappers/IndexToMappedConstant.ts, packages/fast-check/src/arbitrary/_internals/mappers/PatternsToString.ts, packages/fast-check/src/arbitrary/mapToConstant.ts, packages/fast-check/src/utils/globals.ts
`string` used to be pretty reliable against poisoning and still is. But when used in some context such as the result of another generated value (in the case of `.chain` or `fc.gen`) it can expose users to unability to compute itself if a poisoning occured in-between.
As such this PR makes it even more reliable.
Thanks to that PR, `string` arbitrary should be able to better support an ustable environment with some globals being altered or dropped.
**Advanced**
=> 🐛 Resist even more to external poisoning for `string`

.changeset/twenty-bananas-double.md, packages/fast-check/src/arbitrary/stringMatching.ts
`stringMatching` used to partially support a poisoned runtime. It worked but some code paths were not totally resilient to such issues. With this updated version of the code, the arbitrary should be way more resilient to such problems.
**Advanced**
=> 🐛 Better support for poisoning on `stringMatching`

.changeset/curvy-dingos-sort.md, packages/fast-check/src/arbitrary/_internals/ConstantArbitrary.ts, packages/fast-check/src/utils/globals.ts, packages/fast-check/test/unit/arbitrary/_internals/ConstantArbitrary.spec.ts
Make execution of `canShrinkWithoutContext` faster for `constantFrom` cases. Execution should be slightly similar for `constant` (if not a bit faster) and faster for `constantFrom` as soon as it gets used for multiple values (the more values, the faster it gets compared to the previous implementation).
**Advanced**
=> ⚡️ Faster `canShrinkWithoutContext` for constants

packages/jest/test/jest-fast-check.spec.ts
Tests used to be scoped via their configuration file. Starting at this PR, they will be scoped via dedicated directories.
It would avoid having Jest to scan all files of the directory including some not relevant for the test itself. With new scoping the directory being passed will be only for this test, not for others. As such Jest can scan all of it.
**Advanced**
=> ✅(jest) Better scoping of tests execution

packages/vitest/test/vitest-fast-check.spec.ts
They used to be running in a concurrent fashion in the past. But we stopped doing it due to a recent regression on the stability of our CI with Node 23.
The regression being still noticeable even without it and because of the cost of not doing the runs in a concurrent fashion, we move back to concurrent execution.
Regression was not related to vitest, but we dropped concurrent on it too in the past.
**Advanced**
=> ✅(vitest) Make tests run concurrently

packages/jest/test/jest-fast-check.spec.ts, packages/jest/vitest.config.ts
They used to be running in a concurrent fashion in the past. But we stopped doing it due to a recent regression on the stability of our CI with Node 23.
The regression being still noticeable even without it and because of the cost of not doing the runs in a concurrent fashion, we move back to concurrent execution.
**Advanced**
=> ✅(jest) Make tests run concurrently

packages/vitest/vitest.config.ts
Retries are needed for now against Node 23. There is an open ticket on V8 side (see https://issues.chromium.org/issues/374285493) and one on Node side (see https://github.com/nodejs/node/issues/54918) regarding hanging issues of Node 23.
=> ✅(vitest) Add retry for Node 23

.changeset/angry-points-raise.md, packages/fast-check/src/arbitrary/_internals/mappers/IndexToMappedConstant.ts
The arbitrary `mapToConstant` used to rely on a linear scan to get the entry to be used to generate the element. It used to be sub-optimal for cases implying several entries (a normal scenario for this arbitrary).
Our new implementation relies on a dichotomic-lookup that will be way less costly to execute.
This change should have a visible impact when generating strings using the `string` arbitrary.
Supersede #5243
**Advanced**
=> ⚡️ Faster generate process for `mapToConstant`

.changeset/swift-dancers-drum.md, packages/fast-check/src/arbitrary/_internals/helpers/SlicesForStringBuilder.ts, packages/fast-check/src/arbitrary/asciiString.ts, packages/fast-check/src/arbitrary/base64String.ts, packages/fast-check/src/arbitrary/fullUnicodeString.ts, packages/fast-check/src/arbitrary/hexaString.ts, packages/fast-check/src/arbitrary/string.ts, packages/fast-check/src/arbitrary/string16bits.ts, packages/fast-check/src/arbitrary/stringOf.ts, packages/fast-check/src/arbitrary/unicodeString.ts
When initializing the `string` arbitrary, we first check what are the known-to-be-vulnerable-strings that we could possibly generate for this instance.
As such we need to take any known-to-be-vulnerable-string and check if it could have been generated by the string builder we are planning to build. This operation is pretty costly as it implies a backtracking algorithm possibly failing and retrying multiple times.
The change introduced by this PR reduces the overhead linked to this computation by dropping part of the operations that were done twice.
**Advanced**
=> ⚡️ Faster initialization of `string` with faster slices

.changeset/three-eggs-doubt.md, packages/fast-check/src/arbitrary/_internals/helpers/SlicesForStringBuilder.ts, packages/fast-check/src/utils/globals.ts
Follow-up of #5388
**Advanced**
=> ⚡️ Faster initialization of `string` with pre-cached slices

packages/fast-check/src/arbitrary/_internals/helpers/SlicesForStringBuilder.ts, packages/fast-check/src/arbitrary/_internals/helpers/TokenizeString.ts, packages/fast-check/src/arbitrary/_internals/mappers/PatternsToString.ts, packages/fast-check/test/unit/arbitrary/_internals/mappers/PatternsToString.spec.ts
Reverting part of the capability-drop introduced by #5387.
When working on #5387, we dropped some unmapping capabilities on `string`. In the past `string` arbitrary used to be able to shrink even custom values and that even if it uses a pretty uncommon dictionary of units. With #5387 we restricted the unmapping capabilities a bit by dropping some of these very advanced supports.
Now that we know that we can add this support back while preserving our performance uplift we add part of them back.
In other words, before #5387 the following arbitrary could have shrunk `...___...`:
```ts
fc.string({ maxLength: 3, unit: fc.constantFrom('._', '_...', '_._.', '_..', '.', '.._.', '__.', '....', '..', '.___', '._..', '__', '_.', '___', '.__.', '__._', '._.', '...', '_', '.._', …
```
=> ✨ Add back strong unmapping capabilities to `string`

packages/fast-check/src/arbitrary/_internals/builders/CharacterRangeArbitraryBuilder.ts, packages/fast-check/src/arbitrary/_internals/builders/UriQueryOrFragmentArbitraryBuilder.ts, packages/fast-check/src/arbitrary/domain.ts, packages/fast-check/src/arbitrary/emailAddress.ts, packages/fast-check/src/arbitrary/webAuthority.ts, packages/fast-check/src/arbitrary/webSegment.ts, packages/fast-check/src/utils/globals.ts
These arbitraries used to be relatively costly to instantiate and re-instantiate. While generally not a huge concern, when used in multiple properties and arbitraries this small cost (around 10ms measured for some of them) could be considered as far too much.
Tis PR is responsible to drop this time for later re-instantiations of the same internet-related arbitrary (and also other internet-related arbitraries).
The measured perfomance uplift is impressive:
```txt
┌──────────────────────────────────────────────────────────────────┬─────────────┬────────────────────┬────────────┬─────────┐
│ Task Name                                                        │ ops/sec     │ Average Time (ns)  │ Margin     │ Samples │
├────────────────────────────────────────────────────────────── …
```
=> ⚡️ Faster instantiation of internet-related arbitraries

website/blog/2024-12-01-advent-of-pbt-day-1/AdventOfTheDayBuilder.tsx
There was a bug in our parsing algorithm. It fails when the code is minified!
=> 📝 Saving Christmas with nroken playground

.changeset/lazy-lamps-repair.md, packages/fast-check/src/arbitrary/_internals/helpers/DepthContext.ts
Retrieving the depth is a shared operations that can be leveraged by various of our arbitraries. Its current implementation was possibly leading to poisoning crashes into some very specific circumstances. This PR drops a few remaing problematic cases.
In theory, while backing ourselves against poisoning is important for us, it should not bring any visible difference to our users except into very corrupted and vulnerable code they could have wrote.
**Advanced**
=> 🐛 Make depth retrieval more resilient to poisoning

website/blog/2024-12-01-advent-of-pbt-day-1/AdventOfTheDayBuilder.tsx
We used to display the number of success for each day of our Advent of PBT. Unfortunately the service we have been trying on is missing lots of points as it tends to timeout on a regular basis. As such it makes it not really usable.
I prefer not showing this stat this year. Maybe I could find an alternative for my next advent.
=> 📝 Do not display success count

website/docs/ecosystem.md
I've been working on the [`typespec-fast-check`](https://github.com/TomerAberbach/typespec-fast-check) package for a while and it's in a pretty usable state now, so I figured I'd add it to the ecosystem documentation page. Check out the [OpenAI example mentioned in the README](https://github.com/TomerAberbach/typespec-fast-check#examples)!
**Checklist**
**Advanced**
---
I'm assuming no bumps are needed because this doesn't affect any published package.
=> 📝 Add `typespec-fast-check` to ecosystem page

.changeset/strong-ties-matter.md, .github/workflows/build-status.yml, .yarn/versions/be2c76af.yml, packages/fast-check/README.md, packages/fast-check/src/arbitrary/_internals/builders/StringifiedNatArbitraryBuilder.ts, packages/fast-check/src/arbitrary/constantFrom.ts, packages/fast-check/test-types/main.ts, website/docs/migration/from-3.x-to-4.x.md, website/docs/migration/index.md, website/docs/support-us.md
As recommended by #4047, let's leverage const generics to make usage of `constantFrom` even simpler for TS users.
**Advanced**
**⚠️ Minor breaking change**: Requires users to use a more recent version of TypeScript.
=> 🏷️ Better typings for `constantFrom`

.changeset/four-pens-happen.md, packages/fast-check/src/check/runner/configuration/Parameters.ts, packages/fast-check/src/check/runner/configuration/QualifiedParameters.ts, packages/fast-check/src/check/runner/utils/RunDetailsFormatter.ts, packages/fast-check/test/e2e/NoRegressionStack.spec.ts, packages/fast-check/test/e2e/__snapshots__/NoRegression.spec.ts.snap, packages/fast-check/test/e2e/__snapshots__/NoRegressionBigInt.spec.ts.snap, packages/fast-check/test/e2e/__test-helpers__/StackSanitizer.ts, packages/fast-check/test/unit/check/runner/Runner.spec.ts, packages/fast-check/test/unit/check/runner/configuration/QualifiedParameters.spec.ts, packages/worker/test/e2e/__test-helpers__/ThrowWithCause.ts, packages/worker/test/e2e/asyncThrow.spec.ts, packages/worker/test/e2e/blockEventLoop.spec.ts, packages/worker/test/e2e/failing.spec.ts, packages/worker/test/e2e/noWorker.spec.ts, packages/worker/test/e2e/nonSerializableButSameData.spec.ts, packages/worker/test/e2e/nonSerializableData.spec.ts, packages/worker/test/e2e/predicateIsolation.spec.ts, packages/worker/test/e2e/propertyIsolation.spec.ts, packages/worker/test/e2e/syncThrow.spec.ts, packages/worker/test/e2e/unregistered.spec.ts, website/docs/migration/from-3.x-to-4.x.md
Until now, fast-check have been merging the content and stack of the original Error that caused the property to fail into its own Error. With the recent (2022) introduction of cause on Errors, this complex logic can be dropped in favor of the native cause mechanism.
This PR makes cause mode the default. Before this PR, toggling it was possible via `errorWithCause: true` on `fc.assert`.
Given not all test runners properly support causes attached to the Error, we offer a fallback for users willing to preserve the old behaviour. It can be toggled via `includeErrorInReport: true` on `fc.assert`.
Related to #4416.
**Advanced**
**💥 Breaking change**: The display of errors being …
=> 💥 Error with cause by default

.changeset/lazy-cherries-grin.md, packages/fast-check/src/arbitrary/mixedCase.ts
While not being really expensive to compute it's yet another check and dropping it could be useful if we want to go faster. Indeed with `BigInt` being a thing in Node since 10.5.0, we probably don't want to pay for checking it all the time.
We will probably have to bump our minimal requirement to 10.5.0+ for the version 4 of fast-check so that we can expect it to always be a thing no matter the runtime being used as long as it fits our requirements.
**Advanced**
=> ⚡️ Drop unneeded `BigInt` check in `mixedCase`

packages/fast-check/README.md, packages/fast-check/package.json, packages/fast-check/src/utils/globals.ts, website/docs/migration/from-3.x-to-4.x.md
In the past we used to checks for `typeof Type` when initializing our globals (the globals protecting fast-check from poisoning). It used to be done because some of them only appeared starting at Node >8. With our minimal target version being bumped to at least 10.5.0 we can safely stop having these checks and save some precious time during tests (for our users).
This change forces us to move minimal requirements to at least 10.5.0.
**Advanced**
=> ⚡️ Faster initialization of globals by dropping `typeof` checks

.changeset/twenty-worms-listen.md, packages/fast-check/src/arbitrary/json.ts
The `json` arbitrary used to be skipped by our Poisoning-resilience checks as it was depending on a set of helpers that was not that resilient to it.
Following deep refactorings and changes of the helpers backing it we can now check it. While doing so we found it was not that resilent as it was not capable of keeping working properly after a destructive change of `JSON.stringify`. As such we fixed it.
**Advanced**
=> 🐛 Resist to external poisoning for `json`

.changeset/wet-tools-remember.md, packages/fast-check/src/check/runner/DecorateProperty.ts, packages/fast-check/src/check/runner/Runner.ts, packages/fast-check/src/check/runner/configuration/QualifiedParameters.ts, packages/fast-check/test/unit/check/runner/DecorateProperty.spec.ts
The code that was responsible to read the parameters passed to runners such as `assert` or `check` used not to be really optimized. It feft at runtime into megamorphic complexities and leveraged comparisons known to be inefficient.
This PR attempts to make it faster. Given this piece of code is used for any execution of property, even a small performance uplift is good to take.
**Advanced**
=> ⚡️ Faster read of parameters passed to runners

.changeset/swift-buckets-perform.md, packages/fast-check/src/arbitrary/ipV6.ts
While we moved away from `hexa` and `hexaString` we somehow killed the performance of `ipV6`. Indeed it used to rely on `hexaString` which was extremely fast to be instantiated. By switching to `string` we forgot about stabilizing the `unit`. As such each call to create a string of hexa characters will pay an extra cost.
This PR is supposed to address this regression.
```txt
│ (index) │ Task Name                                                        │ ops/sec     │ Average Time (ns)  │ Margin     │ Samples │
├─────────┼──────────────────────────────────────────────────────────────────┼─────────────┼────────────────────┼────────────┼─────────┤
│ 164     │ 'ipV6 [property] on fast-check@3.23.0'                           │ '1,759'     │ 568265.730002895   │ '±4.34%'   │ 100 …
```
=> ⚡️ Faster ipV6 generation with cached string builders

packages/fast-check/src/random/generator/Random.ts, packages/fast-check/test/unit/arbitrary/__test-helpers__/RandomHelpers.ts, website/docs/migration/from-3.x-to-4.x.md
The method `nextArrayInt` has initially be introduced on our instances of `Random` in order to ease the implementation of our arbitrary `double`. When introduced the type bigint was not really supported and thus we had to use something else. Now that this type is available, we can drop this legacy helper.
**Advanced**
=> 💥 Drop method `nextArrayInt` from `Random`

.changeset/ten-wolves-jam.md, packages/fast-check/src/arbitrary/noBias.ts, packages/fast-check/test/unit/arbitrary/noBias.spec.ts
When wrapping twice in a row an arbitrary using `noBias`, the helper function responsible to add `noBias` to your arbitrary may decide not to do so if the provided arbitrary is already the result of `noBias`.
Previously the check was limited to prototype and generate method. We extended it to all methods of our arbitraries.
**Advanced**
=> 🐛 Stricter checks for consecutive `noBias`

.gitignore, pnpm-lock.yaml, website/docs/tutorials/detect-race-conditions/snippets.spec.mjs, website/package.json, website/vitest.config.ts
We move our tests from Jest to Vitest on the website.
**Advanced**
=> ✅ Move website tests to Vitest

.changeset/breezy-grapes-suffer.md, packages/vitest/src/internals/TestBuilder.ts, packages/vitest/src/internals/TestWithPropRunnerBuilder.ts
=> 🚨(vitest) Abide by lint rule `no-duplicate-type-constituents`

examples/005-race/supertest/src/db.ts, packages/fast-check/test/unit/arbitrary/__test-helpers__/FloatingPointHelpers.ts, packages/fast-check/test/unit/arbitrary/double.spec.ts, packages/fast-check/test/unit/arbitrary/float.spec.ts
Related to Typing too permissive #5282.
**Advanced**
=>  🚨 Abide by lint rule `no-unused-vars`

.changeset/plenty-snakes-clean.md, packages/fast-check/postbuild/main.mjs
Fixes #5560
So far we did it via a post build script as we strip comments in the build process configured with tsc.
Results: [here](https://stackblitz.com/edit/node-m2wqwvcg).
**Advanced**
=> ⚡️ Mark all arbitraries as side-effect free

.changeset/deep-emus-speak.md, CONTRIBUTING.md
The `CONTRIBUTING.md` was still mentioning `yarn` commands. I changed them all to `pnpm`. At least this is my best guess interpretation. I also did a quick grep over the whole repo with remaining mentions of `yarn`. I think most are in changelogs or on the website but not related to workflow in this repo. 
**Advanced**
=> 📝 Update CONTRIBUTING.md after switch to pnpm

.changeset/true-carrots-wish.md, packages/fast-check/package.json, packages/fast-check/postbuild/main.mjs, packages/fast-check/src/arbitrary/bigInt64Array.ts, packages/fast-check/src/arbitrary/bigUint64Array.ts, packages/fast-check/src/arbitrary/float32Array.ts, packages/fast-check/src/arbitrary/float64Array.ts, packages/fast-check/src/arbitrary/int16Array.ts, packages/fast-check/src/arbitrary/int32Array.ts, packages/fast-check/src/arbitrary/int8Array.ts, packages/fast-check/src/arbitrary/uint16Array.ts, packages/fast-check/src/arbitrary/uint32Array.ts, packages/fast-check/src/arbitrary/uint8Array.ts, packages/fast-check/src/arbitrary/uint8ClampedArray.ts
Closes https://github.com/dubzzz/fast-check/issues/5752
**Advanced**
=> 🏷️ `Arbitrary<XxxArray>` => `Arbitrary<XxxArray<ArrayBuffer>>`

.changeset/spicy-cameras-provide.md, packages/ava/tsconfig.json, packages/ava/tsconfig.publish.json, packages/ava/tsconfig.publish.types.json, packages/expect-type/tsconfig.json, packages/fast-check/test/e2e/arbitraries/FunctionArbitrary.spec.ts, packages/fast-check/test/unit/arbitrary/_internals/helpers/SanitizeRegexAst.spec.ts, packages/fast-check/test/unit/arbitrary/_internals/helpers/TokenizeRegex.spec.ts, packages/jest/tsconfig.json, packages/jest/tsconfig.publish.json, packages/jest/tsconfig.publish.types.json, packages/packaged/tsconfig.json, packages/packaged/tsconfig.publish.json, packages/packaged/tsconfig.publish.types.json, packages/poisoning/tsconfig.json, packages/poisoning/tsconfig.publish.json, packages/poisoning/tsconfig.publish.types.json, packages/vitest/tsconfig.json, packages/vitest/tsconfig.publish.json, packages/vitest/tsconfig.publish.types.json, packages/worker/tsconfig.json, packages/worker/tsconfig.publish.json, packages/worker/tsconfig.publish.types.json, tsconfig.common.json, tsconfig.common.legacy.json, tsconfig.publish.legacy.json, tsconfig.publish.types.legacy.json, website/docs/migration/from-3.x-to-4.x.md
The bundle of fast-check that we have been producing until now were targeting ES2017. As such any feature not compatible with this standard got transpiled to be compatible.
While allowing older versions of node to be able to run fast-check properly it created a performance cliff for others. With v4 and our target being moved to ES2020 we increased the target version to ES2020.
**Advanced**
=> ⚡️ Target ES2020 in produced bundle

.github/workflows/scripts/generate-changelog.cjs
Our generate changelog is by default stripping all bumps. That said bumps clearly stating the name of the package between parentheses should probably never be skipped. As such we put them back in the generated changelogs.
**Advanced**
=> 🔨 Take into account bumps on one part of monorepo for changelogs

packages/fast-check/README.md, website/docs/ecosystem.md
The package doesn't seem to be maintained anymore. I prefer dropping it from our official recommendations.
=> 📝 Drop link to rescript-fast-check

.changeset/eleven-rice-matter.md, packages/fast-check/src/arbitrary/_internals/implementations/SchedulerImplem.ts, packages/fast-check/test/unit/arbitrary/_internals/implementations/SchedulerImplem.spec.ts
Our scheduler API provides multiple ways to wait for scheduled tasks. One of them is `waitFor`.
The `waitFor` awaiter is currently waiting for 1 tick before starting to schedule anything. The "1 tick" sounds both high and low at the same time. Our target is to bump to something more realistic to avoid our users from running into strange issues where fast-check is just stupidly scheduling tasks one after the others without changing the ordering just because our users has to deal with extra ticks between tasks (user awaits things before scheduling something in one code path and not the other).
This PR bumps this 1 tick to 50. Normally most users will be safe. 
**Advanced**
=> ✨ Wait longer before scheduling anything with `waitFor`

.changeset/happy-donuts-invite.md, packages/fast-check/src/arbitrary/_internals/implementations/SchedulerImplem.ts, packages/fast-check/test/unit/arbitrary/_internals/implementations/SchedulerImplem.spec.ts
When `waitFor` ends, ideally it should cut instantly. In this ideal scenario, any promise started after the end of `waitFor` will just be pending when `waitFor` ends.
But today, we are not yet there. We have still a few promises escaping us. This PR limits the number of such escaping promises.
**Advanced**
=> ⚡️ Move back to better tick management of `waitFor`

.changeset/tough-cameras-brush.md, packages/fast-check/src/arbitrary/_internals/implementations/SchedulerImplem.ts, packages/fast-check/test/unit/arbitrary/_internals/implementations/SchedulerImplem.spec.ts
We want our users never to worry about how we internally deal with waiting for promises to be scheduled. Given the fact there is no API (in JS) available to know if they are pending promises awaiting, we are empirically letting a few ticks running before closing the set of promises that we consider for a batch.
This PR makes sure that anytime a new promise gets added for a batch, we reset our window to wait a bit longer. It makes us safer on the fast that we are gonna catch them all.
**Advanced**
=> ✨ Better capture scheduled tasks before running scheduling

.github/workflows/build-status.yml
Measuring coverage on Linux makes the CI unhappy as Vitest suddenly started to crash on the spec responsible to generate our documentation. Switching to Mac OS fixed the issue for now.
=> 👷 Measure coverage on Mac OS

.changeset/real-bananas-report.md, packages/fast-check/src/arbitrary/_internals/interfaces/Scheduler.ts, website/docs/advanced/race-conditions.md, website/docs/migration/from-3.x-to-4.x.md
The methods `waitOne` and `waitAll` suffer from being hardly usable without a deep knowledge of their way to work. In a code snippet like:
```js
const f = s.scheduleFunction(something);
async function abc() {
const a = await somethingAlreadyResolvedFromCache;
const b = await somethingElseAlreadyResolvedFromCache;
await f(a, b);
}
const p = abc();
await s.waitAll();
```
The `waitAll` call will be unable to wait for `p` to be done. It will end even before `f` got called as it has been developed to avoid letting any promise be executed before itself. Before 4.2.0, the only way to wait safely for `p` to be done with everything leading to `p` being scheduled was to use `waitFor(p)`.
Starting at 4.2.0, you can now use `waitIdle`. It will really wait for everything needing to be …
=> 🗑️ Deprecate `waitOne` and `waitAll`

.changeset/light-eggs-cut.md, packages/fast-check/src/arbitrary/bigInt.ts, packages/fast-check/src/arbitrary/nat.ts, packages/fast-check/test/unit/arbitrary/bigInt.spec.ts, packages/fast-check/test/unit/arbitrary/double.spec.ts, packages/fast-check/test/unit/arbitrary/nat.spec.ts
Adds the following function definitions:
```typescript
declare function nat(arg?: number | NatConstraints): Arbitrary<number>;
declare function bigInt(...args: [] | [bigint, bigint] | [BigIntConstraints]): Arbitrary<bigint>;
```
Previously, passing a `number | NatConstraints` to `nat` would fail:
```
nat can accept a number, but number | NatConstraints is not assignable to number.
nat can accept a NatConstraints, but number | NatConstraints is not assignable to NatConstraints.
```
And similar behavior for `bigInt`.
These are the only arbitraries that require appropriate union type overloads.
Fixes #6073.
**Advanced**
=> 🏷️ Add union type overloads for nat() and bigInt()
