dubzzz/fast-check

src/check/arbitrary/RecordArbitrary.ts
test/e2e/arbitraries/RecordArbitrary.spec.ts
test/unit/check/arbitrary/OneOfArbitrary.spec.ts
test/unit/check/arbitrary/RecordArbitrary.spec.ts
test/unit/check/runner/configuration/QualifiedParameters.spec.ts
test/unit/check/runner/reporter/RunExecution.spec.ts

`record` could preserve more type information
Fixes #71

`record` could preserve more type information - feat/record/1

---

package-lock.json
package.json

Update to TypeScript 2.9

---

src/check/runner/utils/PathWalker.ts
test/unit/check/runner/Sampler.spec.ts

Throw exception in case of bad path

---

documentation/AdvancedArbitraries.md
example/binary-trees/arbitraries/BinarySearchTreeArbitrary.ts
example/binary-trees/arbitraries/BinaryTreeArbitrary.ts
example/binary-trees/arbitraries/FullBinaryTreeArbitrary.ts
example/binary-trees/arbitraries/PerfectBinaryTreeArbitrary.ts
example/binary-trees/models/BinaryTree.ts
example/binary-trees/test.ts
example/package.json
example/run.sh

Document how to generate recursive structures

---

.travis.yml
package-lock.json
package.json
src/check/polyfills.ts
src/check/runner/Sampler.ts
src/fast-check-default.ts
test/legacy/main.js

Remove the use of core-js

---

.travis.yml

https://github.com/nodejs/Release/blob/master/README.md

Do not build on non LTS and expired node

---

src/check/arbitrary/CharacterArbitrary.ts
test/unit/check/arbitrary/CharacterArbitrary.spec.ts

Characters must shrink to printable ascii for minimum

---

package-lock.json
package.json

Move to TypeScript 3.0

---

README.md

Switch to bundle.run instead of jsDelivr

---

src/check/arbitrary/CharacterArbitrary.ts
src/check/polyfills.ts
test/legacy/main.js
test/unit/check/polyfills.spec.ts

No legacy check for fullUnicode

---

src/check/arbitrary/CharacterArbitrary.ts

Fixes #164 - fullUnicode has not been switched to prefer printable

fullUnicode must favor printable characters

---

.travis.yml
package.json

There are some things to troubleshoot with lorem-ipsum.js dependency before moving on

Remove esm build from publish

---

.travis.yml

Build against head dependencies test

---

.travis.yml
package.json

Publish both cjs and esm of the package

---

package-lock.json
package.json
src/check/runner/Runner.ts
src/check/runner/Sampler.ts
src/check/runner/Tosser.ts
src/check/runner/configuration/Parameters.ts
src/check/runner/configuration/QualifiedParameters.ts
src/check/runner/configuration/RandomType.ts
test/unit/check/runner/Tosser.spec.ts
test/unit/check/runner/configuration/QualifiedParameters.spec.ts

Add parameter to change the random generator
Fixes #128

Add parameter to change the random generator

---

CONTRIBUTORS.md

sort contributors by first name

---

documentation/Runners.md

Fix small typo in Runners.md

---

package-lock.json
package.json

Related to #147
More details at: https://github.com/dubzzz/pure-rand/commit/5f36e2081080b3b0a2ad12cd0154e0e5ee519357

Bump pure-rand for better performances

---

src/check/arbitrary/RecordArbitrary.ts

Even better typings for fc.record

---

package-lock.json
package.json
src/check/runner/configuration/Parameters.ts
src/check/runner/configuration/QualifiedParameters.ts
src/check/runner/configuration/RandomType.ts
test/e2e/GenerateAllValues.spec.ts
test/unit/check/arbitrary/LoremArbitrary.spec.ts
test/unit/check/arbitrary/OptionArbitrary.spec.ts
test/unit/check/arbitrary/RecordArbitrary.spec.ts
test/unit/check/arbitrary/definition/ArbitraryWithShrink.spec.ts
test/unit/check/arbitrary/generic/GenericArbitraryHelper.ts
test/unit/check/model/commands/CommandsArbitrary.spec.ts
test/unit/check/runner/Tosser.spec.ts
test/unit/check/runner/configuration/QualifiedParameters.spec.ts
test/unit/random/generator/Random.spec.ts

Switch to another PRNG as default random

---

README.md
documentation/AdvancedArbitraries.md
documentation/Arbitraries.md
documentation/Tips.md
src/check/arbitrary/ArrayArbitrary.ts
src/check/arbitrary/ContextArbitrary.ts
src/check/arbitrary/OptionArbitrary.ts
src/check/arbitrary/SetArbitrary.ts
src/check/arbitrary/TupleArbitrary.generic.ts
src/check/arbitrary/definition/Shrinkable.ts
src/check/runner/Runner.ts
src/check/symbols.ts
src/fast-check-default.ts
test/e2e/StateFullArbitraries.spec.ts
test/unit/check/arbitrary/ArrayArbitrary.spec.ts
test/unit/check/arbitrary/ContextArbitrary.spec.ts
test/unit/check/arbitrary/TupleArbitrary.generic.spec.ts
test/unit/check/arbitrary/definition/Shrinkable.spec.ts

Should unlock some capabilities:
- better function logs (issue to be opened)
- better handling of commands (issue to be opened)
- internal predicate logger (done in the PR)
- stream generator (more at #222)
Certainly others to come ;)

Handle unpure generated values and Logger

---

example/async-property/FakeApi.ts
example/async-property/test.ts
example/package-lock.json
example/package.json
example/run.sh

Add an example for asyncProperty

---

src/check/runner/configuration/Parameters.ts
src/check/runner/configuration/QualifiedParameters.ts
test/e2e/Shadows.spec.ts
test/unit/check/runner/configuration/QualifiedParameters.spec.ts

Incoming seed should accept any possible double values

---

prebuild/property.ts
test/e2e/GenerateAllValues.spec.ts
test/e2e/ModelBased.spec.ts
test/e2e/Shadows.spec.ts
test/unit/check/arbitrary/ConstantArbitrary.spec.ts
test/unit/check/arbitrary/FrequencyArbitrary.spec.ts
test/unit/check/arbitrary/ObjectArbitrary.spec.ts
test/unit/check/arbitrary/StringArbitrary.spec.ts
test/unit/check/arbitrary/definition/Arbitrary.spec.ts
test/unit/check/runner/Sampler.spec.ts
test/unit/random/generator/Random.spec.ts
test/unit/stream/Stream.spec.ts
tsconfig.json
tslint.json

Update linter configuration

---

test/e2e/model/CommandsArbitrary.spec.ts

E2E shrink of commands along other arbitraries

---

documentation/Arbitraries.md
src/check/model/ModelRunner.ts
src/check/model/command/AsyncCommand.ts
src/check/model/command/ICommand.ts
src/check/model/commands/CommandWrapper.ts
src/check/model/commands/CommandsArbitrary.ts
src/check/model/commands/CommandsIterable.ts
test/unit/check/model/ModelRunner.spec.ts

Add support for an async check method in commands

---

README.md
documentation/IssuesDiscovered.md

List some issues discovered by using fast-check

---

documentation/Arbitraries.md
src/check/arbitrary/IntegerArbitrary.ts
src/fast-check-default.ts
test/unit/check/arbitrary/IntegerArbitrary.spec.ts

Add maxSafeInteger and maxSafeNat

---

src/check/runner/reporter/ExecutionStatus.ts

It should be usable by JavaScript clients

Do not define ExecutionStatus as const enum

---

package.json

[BUG] Browser bundle broken since v1.9.2

---

src/check/arbitrary/ObjectArbitrary.ts
test/unit/check/arbitrary/ObjectArbitrary.spec.ts

Better balance between values produced by `fc.anything()`

---

documentation/Arbitraries.md
src/check/arbitrary/HostArbitrary.ts
src/check/arbitrary/WebArbitrary.ts
src/check/arbitrary/helpers/SpecificCharacterRange.ts
src/fast-check-default.ts
test/e2e/arbitraries/WebArbitrary.spec.ts
test/unit/check/arbitrary/HostArbitrary.spec.ts
test/unit/check/arbitrary/WebArbitrary.spec.ts

Implement Url arbitraries

---

package-lock.json
package.json
tsconfig.json

* bundle: 139128 -> 118443
* [before] npm pack --dry-run:
npm notice package size:  178.6 kB
npm notice unpacked size: 941.9 kB
npm notice total files:   342
* [after] npm pack --dry-run:
npm notice package size:  172.4 kB
npm notice unpacked size: 829.4 kB
npm notice total files:   342

Add dependency on tslib

---

documentation/1-Guides/Runners.md
src/check/property/SkipAfterProperty.ts
src/check/runner/DecorateProperty.ts
src/check/runner/Runner.ts
src/check/runner/configuration/Parameters.ts
src/check/runner/configuration/QualifiedParameters.ts
test/e2e/ReplayCommands.spec.ts
test/unit/check/property/SkipAfterProperty.spec.ts
test/unit/check/runner/DecorateProperty.spec.ts
test/unit/check/runner/configuration/QualifiedParameters.spec.ts

Ability to auto skip runs after time limit

---

documentation/1-Guides/Arbitraries.md
documentation/1-Guides/Tips.md

Clarify replay of fc.commands

---

src/utils/stringify.ts
test/unit/utils/stringify.spec.ts

Stringify Date as valid JavaScript

---

src/check/model/commands/CommandWrapper.ts
test/unit/check/model/commands/CommandWrapper.spec.ts

CommandWrapper was not applying cloneMethod

---

src/check/arbitrary/WebArbitrary.ts

Circular dependency in fast-check for WebArbitrary

---

test/rollup/esm/rollup.config.js
test/rollup/iife/rollup.config.js

Related to #383
Follow-up of #384

Consider (most) warnings as errors in rollup

---

src/check/arbitrary/LetRecArbitrary.ts
test/unit/check/arbitrary/LetRecArbitrary.spec.ts

Add caching for withBias of letrec

---

documentation/1-Guides/Tips.md

Document how to use in conjonction with faker

---

documentation/1-Guides/HandsOnPropertyBased.md

Remove a warning from the getting started tutorial.
❌ New feature
None.

Update ts-jest config (tsConfigFile -> tsConfig)

---

documentation/1-Guides/Tips.md

Fixes #413
❌ New feature
❌ Fix an issue
None.

Add section "Migrate from jsverify to fast-check"

---

CONTRIBUTORS.md
documentation/1-Guides/Arbitraries.md
src/check/arbitrary/DateArbitrary.ts
src/fast-check-default.ts
test/e2e/NoRegression.spec.ts
test/e2e/__snapshots__/NoRegression.spec.ts.snap
test/unit/check/arbitrary/DateArbitrary.spec.ts

Fixes #403 
✔️ New feature
❌ Fix an issue
None

Add Date arbitrary

---

documentation/1-Guides/AdvancedArbitraries.md
documentation/1-Guides/Arbitraries.md
documentation/1-Guides/Runners.md
documentation/1-Guides/Tips.md

Better documentation with table of contents.
❌ New feature
❌ Fix an issue
None.

Add table of contents on top of the documentation

---

.travis.yml

NPM deployment key has been revoked.
❌ New feature
❌ Fix an issue
✔️ Other: CI fix
None.

🔧 Update key for Travis CI

---

package-lock.json
package.json

Bump direct dependencies
❌ New feature
❌ Fix an issue
✔️ Other: Bump dependencies
None.

:arrow_up: Bump direct dependencies

---

example/package.json
example/yarn.lock

Related to #373
❌ New feature
❌ Fix an issue
✔️ Other: *test & doc*
None.

✅ Update package.json to have the tests running in CodeSandbox

---

example/002-recursive/isSearchTree/arbitraries/BinarySearchTreeArbitrary.ts
example/003-misc/knight/arbitraries/SpaceArbitrary.ts
example/003-misc/knight/main.spec.ts
example/003-misc/mazeGenerator/main.spec.ts
example/003-misc/mazeGenerator/src/mazeGenerator.ts

FIX CodeSandbox tests not running properly due to typos
❌ New feature
None.

🐛 FIX CodeSandbox tests not running properly due to typos

---

example/003-misc/roman/main.spec.ts
example/003-misc/roman/src/roman.ts
example/README.md

Add a code example.
❌ New feature
❌ Fix an issue
None.

✏️ Add example showing how to test fromRoman/toRoman

---

src/check/arbitrary/ConstantArbitrary.ts
src/check/arbitrary/IntegerArbitrary.ts
src/check/arbitrary/OneOfArbitrary.ts
src/check/arbitrary/definition/BiasedArbitraryWrapper.ts
src/check/arbitrary/definition/Shrinkable.ts
src/check/arbitrary/helpers/BiasNumeric.ts
src/check/model/ModelRunner.ts
src/check/runner/RunnerIterator.ts
src/check/runner/configuration/QualifiedParameters.ts
src/check/runner/reporter/RunExecution.ts

Internal typings
❌ New feature
❌ Fix an issue
✔️ Other: *internal typings*
None.

🏷️ Minor fixes related to internal typings

---

.travis.yml

CI.
❌ New feature
❌ Fix an issue
✔️ Other: *CI Configuration*
None.

🔧 Do not run travis outside of master and PRs for master

---

.eslintignore
.eslintrc.js
src/check/arbitrary/definition/Arbitrary.ts
src/check/property/TimeoutProperty.ts
src/check/property/UnbiasedProperty.ts
src/stream/Stream.ts

Fix #448
❌ New feature
❌ Fix an issue
✔️ Other: *cleaning*
None.

🚨 Enable no-unused-vars eslint rule

---

.codesandbox/ci.json

Adding CodeSandbox CI
❌ New feature
❌ Fix an issue
✔️ Other: *ci*
None.

👷 Configure CodeSandbox CI

---

example/005-race/autocomplete/main.spec.tsx

Simplify CodeSandbox example for Autocomplete.
❌ New feature
❌ Fix an issue
None.

Simplify CodeSandbox example for Autocomplete

---

documentation/1-Guides/Arbitraries.md
example/005-race/autocomplete/main.spec.tsx
example/005-race/dependencyTree/main.spec.ts
example/005-race/userProfile/main.spec.tsx
src/check/arbitrary/AsyncSchedulerArbitrary.ts
test/unit/check/arbitrary/AsyncSchedulerArbitrary.spec.ts

Must have for #491 
It also highly simplify the usage of `fc.scheduler` on React
✔️ New feature
❌ Fix an issue
None.

✨ Ability to automatically wrap the tasks resolved by the scheduler

---

src/check/arbitrary/HostArbitrary.ts
src/check/arbitrary/WebArbitrary.ts
test/e2e/arbitraries/WebArbitrary.spec.ts
test/unit/check/arbitrary/WebArbitrary.spec.ts

Exclude punycode domains if asked to
Fixes #532
✔️ New feature
❌ Fix an issue
None.

✨ Exclude internationalized domains if asked to

---

src/check/runner/configuration/Parameters.ts
src/check/runner/configuration/QualifiedParameters.ts
src/check/runner/configuration/RandomType.ts
test/unit/check/runner/configuration/QualifiedParameters.spec.ts

Add xoroshiro128plus in RandomType
✔️ New feature
❌ Fix an issue
None.

✨ Add xoroshiro128plus in RandomType

---

example/001-simple/sort/main.spec.ts
example/001-simple/sort/src/sort.ts

Fixes #531
❌ New feature
❌ Fix an issue
None.

✅ Add an example using a function generator

---

.npmignore

Do not publish unneeded files
❌ New feature
❌ Fix an issue
✔️ Other: *remove unneeded published files*
None.

🔧 Remove postbuild folder from published package

---

documentation/1-Guides/Arbitraries.md
src/check/arbitrary/ObjectArbitrary.ts
test/e2e/GenerateAllValues.spec.ts
test/unit/check/arbitrary/ObjectArbitrary.spec.ts
test/unit/utils/stringify.spec.ts

Fixes #506
✔️ New feature
❌ Fix an issue
None.

✨ Add ability to generate objects without prototype

---

example/001-simple/decompPrime/main.spec.ts
example/001-simple/decompPrime/src/decompPrime.ts
example/README.md

Add example based on decomposition in prime numbers
❌ New feature
❌ Fix an issue
None.

📝 Add example based on decomposition in prime numbers

---

test/unit/utils/polyfills.spec.ts

FIX Broken build following bump of libs.
❌ New feature
None.

💚 FIX Broken build following bump of libs

---

example/yarn.lock
test/type/yarn.lock
yarn.lock

Fix security alerts reported by GitHub.
❌ New feature
❌ Fix an issue
✔️ Other: *security issue reported by GitHub*
None.

🔧 Upgrade dependencies and devDependencies

---

package.json
yarn.lock

FIX Broken documentation build
❌ New feature
❌ Fix an issue
✔️ Other: *fix docs*
None

🔧 FIX Broken documentation build

---

.travis.yml

Use "next" tag to flag next versions
❌ New feature
❌ Fix an issue
✔️ Other: *travis config*
None.

🔧 Use "next" tag to flag next versions

---

README.md

Tried, and failed, to run the mocha integration example, however, it had some small human mistakes.
✔️ Fixed small mocha integration example mistake.

Fixed mocha integration example

---

example/001-simple/decompPrime/src/decompPrime.ts

Adapt decompPrime to be compatible with CodeSandbox
❌ New feature
❌ Fix an issue
None

📝 Adapt decompPrime to be compatible with CodeSandbox

---

documentation/1-Guides/Arbitraries.md

Document how to schedule native timers with fc.scheduler
❌ New feature
❌ Fix an issue
None

📝 Document how to schedule native timers with fc.scheduler

---

example/005-race/debounced-autocomplete/main.spec.tsx

Fixes #580
❌ New feature
None.

💚 Fix wrongly used userEvent.type in examples

---

package.json

Add funding url in package.json
❌ New feature
❌ Fix an issue
None.

📄 Add funding url in package.json

---

package.json
yarn.lock

Bump to the latest version of TypeScript and tslib
❌ New feature
❌ Fix an issue
✔️ Other: *Bump tslib*
Maybe some regressions due to the major bump of tslib 🤔

⬆️ Bump to the latest version of TypeScript and tslib

---

.travis.yml

Update travis configuration to use Node 14
❌ New feature
❌ Fix an issue
✔️ Other: *CI configuration*
None

🔧 Update travis configuration to use Node 14

---

README.md

Update README with Credits section
❌ New feature
❌ Fix an issue
None.

📄 Update README with Credits section

---

documentation/1-Guides/Tips.md

Document how to use fast-check in web using pika.
❌ New feature
❌ Fix an issue
None.

📝 Document how to use fast-check in web using pika

---

.travis.yml

Try to generate the documentation when building the PR.
❌ New feature
/❌ Fix an issue
None

✅ Try to generate the documentation when building the PR

---

.eslintrc.cjs
src/check/arbitrary/ObjectArbitrary.ts
test/unit/check/arbitrary/ObjectArbitrary.spec.ts
yarn.lock

Update `ObjectConstraints`
❌ New feature
Typings impact

💥 Get rid of old namespace syntax for ObjectArbitrary

---

README.md

Add a compatibility section into the README
❌ New feature
❌ Fix an issue
None

📄 Add a compatibility section into the README

---

documentation/1-Guides/HowItWorks.md

fix some typos

---

.github/dependabot.yml

More package.json for dependabot
❌ New feature
❌ Fix an issue
✔️ Other: *ci*
None

💚 More package.json for dependabot

---

.github/dependabot.yml

Add missing test project into dependabot list
❌ New feature
❌ Fix an issue
✔️ Other: *CI*
None

👷 Add missing test project into dependabot list

---

.github/dependabot.yml

Fix dependabot configuration
❌ New feature
❌ Fix an issue
✔️ Other: *CI*
None

👷 Fix dependabot configuration

---

.github/dependabot.yml

Remove unneeded package from dependabot scope
❌ New feature
❌ Fix an issue
✔️ Other: *CI*
None

👷 Remove unneeded package from dependabot scope

---

CHANGELOG.md

Add links to commit diff into the CHANGELOG
❌ New feature
❌ Fix an issue
None

📝 Add links to commit diff into the CHANGELOG

---

README.md

Update compatibility table on README.md
❌ New feature
❌ Fix an issue
None

✏️ Update compatibility table on README.md

---

MIGRATION_1.X_TO_2.X.md

Migration guide
❌ New feature
❌ Fix an issue
None.

✏️ Migration guide to ease migration from version 1.x to 2.x

---

example/package.json
example/yarn.lock
test/esm/node-extension-cjs/yarn.lock
test/esm/node-extension-mjs/yarn.lock
test/esm/node-with-import/yarn.lock
test/esm/node-with-require/yarn.lock
test/esm/rollup-with-import/yarn.lock
test/esm/rollup-with-require/yarn.lock
test/esm/webpack-with-import/yarn.lock
test/esm/webpack-with-require/yarn.lock
test/legacy/typescript-3.2/package.json
test/legacy/typescript-3.2/yarn.lock
test/type/package.json
test/type/yarn.lock

Bump to fast-check 2.0.0 in lock files
❌ New feature
❌ Fix an issue
✔️ Other: *bump*
None

⬆️ Bump fast-check to 2.0.0 in *

---

test/unit/check/arbitrary/OptionArbitrary.spec.ts

Better coverage
❌ New feature
❌ Fix an issue
✔️ Other: *better coverage*
None

✅ Better coverage for option

---

.github/workflows/codeql-analysis.yml

❌ New feature
❌ Fix an issue
✔️ Other: *CI*
None.

👷 Enable CodeQL Analysis

---

src/fast-check-default.ts
src/utils/hash.ts

✔️ New feature
❌ Fix an issue
None.

✨ Export internal `hash` function

---

MIGRATION_1.X_TO_2.X.md
documentation/1-Guides/Tips.md

❌ New feature
❌ Fix an issue
None.

📝 Update links for `pika.dev` to `skypack.dev`

---

example/005-race/todolist/model-based/AddItemCommand.ts

❌ New feature
❌ Fix an issue
✔️ Other: *examples cleaning*
None

✅ Do not use `@testing-library/dom` directly in `examples/`

---

README.md

It does not bring any value now that dependabot warns us related to security issues.
Moreover it not seem to support Yarn 2 (aka. Berry)
❌ New feature
❌ Fix an issue
None

📝 Remove snyk badge

---

test/unit/utils/hash.spec.ts

❌ New feature
❌ Fix an issue
None

💚 Reduce coverage flakiness on `hash.ts`

---

.github/PULL_REQUEST_TEMPLATE.md

Update the PR template
❌ New feature
❌ Fix an issue
None

📝 Update the template for new Pull Requests

---

.travis.yml

Apply post-build script before generating the doc
❌ New feature
❌ Fix an issue
None

📝 Apply post-build script before generating the doc

---

.github/stale.yml

More details at https://probot.github.io/apps/stale/
❌ New feature
❌ Fix an issue
✔️ Other: *ci*
None

👷 Enable protobot-stale

---

src/check/arbitrary/AsyncSchedulerArbitrary.ts
src/check/arbitrary/FalsyArbitrary.ts
src/check/arbitrary/FrequencyArbitrary.ts
src/check/arbitrary/MixedCaseArbitrary.ts
src/check/arbitrary/ObjectArbitrary.ts
src/check/arbitrary/OptionArbitrary.ts
src/check/arbitrary/RecordArbitrary.ts
src/check/arbitrary/WebArbitrary.ts
src/check/model/command/AsyncCommand.ts
src/check/model/command/Command.ts
src/check/model/command/ICommand.ts
src/check/runner/configuration/GlobalParameters.ts
src/check/runner/configuration/Parameters.ts
src/check/runner/reporter/RunDetails.ts
src/check/runner/utils/RunDetailsFormatter.ts
src/random/generator/Random.ts
src/stream/Stream.ts

❌ New feature
❌ Fix an issue
None

📝 Document non-documented sections

---

.github/dependabot.yml

❌ New feature
❌ Fix an issue
✔️ Other: *ci*
None

👷 Update dependabot configuration on versioning-strategy

---

package.json
yarn.lock

❌ New feature
❌ Fix an issue
✔️ Other: *bump*
None

⬆️ Bump typescript to 4.0.2

---

.github/dependabot.yml

Revert "👷 Update dependabot configuration on versioning-strategy"

---

README.md

❌ New feature
❌ Fix an issue
None

📝 Rename 'Documentation' badge into 'API Reference'

---

documentation/Arbitraries.md
src/check/arbitrary/FunctionArbitrary.ts

❌ New feature
Potential impact if someone rely on the string produced in case of errors. Actually nothing really expected as the function is the same and its toString is similar and still valid JavaScript.

✏️ Clean unneeded lines on toString for func arbitraries

---

package.json
runkit.cjs

Fixes #937
❌ New feature
❌ Fix an issue
None

📝 Add runkit code example

---

src/check/arbitrary/WebArbitrary.ts

✏️ WebUrlConstraints instead of inlined type for webUrl

---

test/unit/check/arbitrary/ArrayArbitrary.spec.ts
test/unit/check/arbitrary/SetArbitrary.spec.ts
test/unit/check/arbitrary/StringArbitrary.spec.ts
test/unit/check/arbitrary/SubarrayArbitrary.spec.ts
test/unit/check/arbitrary/generic/ArrayHelpers.ts
test/unit/check/arbitrary/generic/GenerateOneValue.ts
test/unit/check/model/commands/CommandsArbitrary.spec.ts

Add missing tests before releasing next minor
❌ New feature
❌ Fix an issue
None

✅ Cover non-recommended signatures with tests

---

package.json
test/unit/utils/stringify.spec.ts
yarn.lock

🐛 FIX Publication following introduction of buffer

---

codemods/unify-signatures/snippet-5.js
codemods/unify-signatures/transform.cjs
documentation/Arbitraries.md
test/unit/check/arbitrary/DateArbitrary.utest.spec.ts
test/unit/check/arbitrary/generic/GenericArbitraryHelper.ts

Related to #992
❌ New feature
❌ Fix an issue
✔️ Other: *codemod enhancement*
None

🚸 Support option in codemod unify-signatures

---

codemods/unify-signatures/snippet-5.js
codemods/unify-signatures/transform.cjs
documentation/Arbitraries.md
test/e2e/ModelBased.spec.ts

Related to #992 
❌ New feature
❌ Fix an issue
✔️ Other: *codemod enhancement*
None

🚸 Support commands in codemod unify-signatures

---

documentation/Arbitraries.md
src/check/arbitrary/ObjectArbitrary.ts
test/e2e/GenerateAllValues.spec.ts
test/unit/check/arbitrary/ObjectArbitrary.spec.ts
test/unit/utils/stringify.spec.ts

✔️ New feature
❌ Fix an issue
None

✨ Add withDate option on fc.object

---

codemods/unify-signatures/snippet-5.js
codemods/unify-signatures/transform.cjs
documentation/Arbitraries.md
src/check/arbitrary/FloatingPointArbitrary.ts
src/fast-check-default.ts
test/unit/check/arbitrary/FloatingPointArbitrary.spec.ts
test/unit/check/runner/configuration/QualifiedParameters.spec.ts

Related to #992
✔️ New feature
❌ Fix an issue
None.

✨ Add constraints-based signature for float and double

---

documentation/Arbitraries.md
src/check/arbitrary/ArrayArbitrary.ts
src/check/arbitrary/FloatingPointArbitrary.ts
src/check/arbitrary/IntegerArbitrary.ts
src/check/arbitrary/LoremArbitrary.ts
src/check/arbitrary/ObjectArbitrary.ts
src/check/arbitrary/OptionArbitrary.ts
src/check/arbitrary/SetArbitrary.ts
src/check/arbitrary/StringArbitrary.ts
src/check/arbitrary/SubarrayArbitrary.ts
src/check/model/commands/CommandsArbitrary.ts

More details on #992
Fixes #992
❌ New feature
❌ Fix an issue
✔️ Other: *deprecation notice*
Code has been deprecated.
BUT nothing has been removed for the moment and nothing will be at least before next major (or another one).

🗑️ Deprecate old signatures

---

.travis.yml

❌ New feature
❌ Fix an issue
✔️ Other: *ci*
None

👷 Check package's compatibility against latest node

---

.travis.yml

More details here: https://www.skypack.dev/blog/2020/10/skypack-quality-score-actionable-feedback-to-build-better-packages/
❌ New feature
❌ Fix an issue
✔️ Other: *ci*
None

👷 Add Skypack package score during tests

---

documentation/Tips.md

Fix a small typographical error.
❌ New feature
❌ Fix an issue
None

Fix typographical error

---

.github/workflows/build-status.yml

❌ New feature
❌ Fix an issue
✔️ Other: *ci workflows*
None

👷 Try to fix publish to gh-pages

---

.github/workflows/build-status.yml

❌ New feature
❌ Fix an issue
✔️ Other: *ci builds*
None

👷 Try to fix publish to gh-pages (2)

---

.github/workflows/build-status.yml

❌ New feature
❌ Fix an issue
✔️ Other: *ci builds*
None

👷 Try to fix publish to gh-pages (3)

---

README.md

Fixes #360 by including a link to my bindings
❌ New feature
❌ Fix an issue
None

✏️ Add link to ReScript bindings

---

test/unit/check/arbitrary/generic/GenericArbitraryHelper.ts

❌ New feature
❌ Fix an issue
✔️ Other: *test helpers*
None

✅ Better error reporting with `isValidArbitrary`

---

.github/workflows/build-status.yml

Release note: https://nodejs.org/en/blog/release/v12.2.0/
News from Twitter: https://twitter.com/MylesBorins/status/1331342373801123843
❌ New feature
❌ Fix an issue
✔️ Other: *more envs for tests*
None

👷 Check CJS/ESM against node 12.20

---

test/legacy/node-8/main.js

❌ New feature
❌ Fix an issue
None

✅ Add missing legacy tests for node 8 on next floats and others

---

test/unit/check/arbitrary/helpers/ArrayInt64.spec.ts

❌ New feature
❌ Fix an issue
✔️ Other: *just tests*
None

✅ Add some more tests for ArrayInt64 for coverage stability

---

src/check/arbitrary/ObjectArbitrary.ts
test/unit/check/arbitrary/ObjectArbitrary.spec.ts

❌ New feature
❌ Fix an issue
✔️ Other: *coverage*
None

💚 Reduce flakyness of object boxing coverage

---

.github/workflows/build-status.yml

❌ New feature
❌ Fix an issue
✔️ Other: *ci*
None

👷 Split test task into two tasks: one for units, another for e2e

---

.github/workflows/build-status.yml

❌ New feature
❌ Fix an issue
✔️ Other: *ci*
None

👷 Run E2E tests on multiple platforms

---

documentation/Arbitraries.md
src/check/arbitrary/ObjectArbitrary.ts
test/e2e/GenerateAllValues.spec.ts
test/unit/check/arbitrary/ObjectArbitrary.spec.ts
test/unit/utils/stringify.spec.ts

✔️ New feature
❌ Fix an issue
None

✨ Add option withTypedArray to `fc.object` and `fc.anything`

---

test/legacy/node-8/main.js

❌ New feature
❌ Fix an issue
✔️ Other: *legacy tests*
None

✅ Add legacy tests for typed arrays

---

.github/dependabot.yml

❌ New feature
❌ Fix an issue
✔️ Other: *dependabot*
None

🔧 Add github-actions to dependabot list

---

test/e2e/arbitraries/DoubleNextArbitrary.spec.ts
test/e2e/arbitraries/FloatNextArbitrary.spec.ts

❌ New feature
❌ Fix an issue
✔️ Other: *flaky*
None

💚 Increase stability of e2e on floatNext/doubleNext

---

test/unit/check/arbitrary/ObjectArbitrary.spec.ts

❌ New feature
❌ Fix an issue
✔️ Other: *coverage*
None

💚 Add more tests for fc.anything to reduce coverage flakiness

---

jest.config.cjs

❌ New feature
❌ Fix an issue
✔️ Other: *better coverage*
None

👷 Only take into account files from src/ in coverage

---

.github/workflows/build-status.yml

❌ New feature
❌ Fix an issue
✔️ Other: *ci*
None

👷 Remove coveralls from the CI

---

README.md

❌ New feature
❌ Fix an issue
None

📝 Switch to codecov in README

---

README.md

❌ New feature
❌ Fix an issue
None

📝 Prefer spaces over tabs in the README (easier to fit in screen)

---

.github/actions/comment-on-pr/index.cjs
.github/workflows/build-status.yml

❌ New feature
❌ Fix an issue
❌ Other: *ci*
None

👷 Better message for automatic comments

---

src/utils/stringify.ts
test/unit/utils/stringify.spec.ts

✔️ New feature
❌ Fix an issue
None

✨ Better handling of known symbols with `fc.stringify`

---

src/check/arbitrary/RecordArbitrary.ts
test/unit/check/arbitrary/RecordArbitrary.spec.ts

✔️ New feature
❌ Fix an issue
None

✨ Throw if non enumerable keys declared in requiredKeys of record

---

example/yarn.lock
test/esm/node-extension-cjs/yarn.lock
test/esm/node-extension-mjs/yarn.lock
test/esm/node-with-import/yarn.lock
test/esm/node-with-require/yarn.lock
test/esm/rollup-with-import/yarn.lock
test/esm/rollup-with-require/yarn.lock
test/esm/webpack-with-import/yarn.lock
test/esm/webpack-with-require/yarn.lock
test/type/yarn.lock
yarn.lock

Ideally it should be part of the CI:
```sh
yarn dedupe --check
```
_See https://yarnpkg.com/cli/dedupe_
❌ New feature
❌ Fix an issue
✔️ Other: *dedup locks*
None

📌 Re-generate yarn.lock files

---

test/unit/utils/stringify.spec.ts

❌ New feature
❌ Fix an issue
✔️ Other: *new tests*
None

✅ Add unit tests for stringify on Regex

---

src/check/arbitrary/IntegerArbitrary.ts
src/check/arbitrary/helpers/ShrinkInteger.ts
test/unit/check/arbitrary/IntegerArbitrary.spec.ts
test/unit/check/arbitrary/generic/ArbitraryBuilder.ts

❌ New feature
❌ Fix an issue
✔️ Other: *moving internal code towards new api*
Potential impact on shrinkers for integer and all others (as integer is the base for all the others)

♻️ Re-implement shrinker for integer based on contextual shrinker

---

test/type/main.ts

❌ New feature
❌ Fix an issue
✔️ Other: *Missing typing test*
None

✅ Typecheck ArbitraryWithContextualShrink compatible with older version

---

src/check/model/commands/CommandsArbitrary.ts

❌ New feature
❌ Fix an issue
✔️ Other: *use modern*
None

♻️ Re-use contextual shrinker of integer in commands

---

.github/actions/deploy-netlify/index.cjs
README.md
documentation/Arbitraries.md
package.json

❌ New feature
❌ Fix an issue
None

📝 Only specify a single entryPoint in TypeDoc

---

src/check/arbitrary/ArrayArbitrary.ts
src/check/arbitrary/SubarrayArbitrary.ts

❌ New feature
❌ Fix an issue
✔️ Other: *better shrinker*
Shrink on subarray

⚡️ More efficient shrinker on subarray

---

test/type/main.ts
test/type/type-checker.ts

❌ New feature
❌ Fix an issue
None

✅ Tests on typings should fail with explicit errors

---

src/check/arbitrary/BigIntArbitrary.ts
src/check/arbitrary/IntegerArbitrary.ts
src/check/arbitrary/helpers/ArrayInt64Arbitrary.ts
src/stream/Stream.ts
test/unit/stream/Stream.spec.ts

❌ New feature
❌ Fix an issue
✔️ Other: *code cleaning*
None

♻️ Extract Stream.of logic for re-use

---

src/check/arbitrary/definition/ArbitraryWithContextualShrink.ts
test/unit/check/arbitrary/definition/ArbitraryWithContextualShrink.utest.spec.ts

❌ New feature
❌ Fix an issue
None

✅ Add tests for ArbitraryWithContextualShrink

---

src/check/arbitrary/BigIntArbitrary.ts
src/check/arbitrary/IntegerArbitrary.ts
src/check/arbitrary/helpers/ArrayInt64Arbitrary.ts

❌ New feature
❌ Fix an issue
✔️ Other: *better structure for the implem*
None

♻️ Restructure implementations of ArbitraryWithContextualShrink

---

src/check/arbitrary/helpers/ArrayInt64Arbitrary.ts
test/unit/check/arbitrary/BigIntArbitrary.spec.ts
test/unit/check/arbitrary/IntegerArbitrary.spec.ts
test/unit/check/arbitrary/generic/ShrinkTree.ts
test/unit/check/arbitrary/helpers/ArrayInt64Arbitrary.utest.spec.ts

❌ New feature
❌ Fix an issue
None

✅ Add snapshot tests for new core shrinkers: integer, bigint, arrayInt64

---

README.md

❌ New feature
❌ Fix an issue
None

📝 Add badge from packagequality.com

---

SECURITY.md

❌ New feature
❌ Fix an issue
✔️ Other: *security policy*
None

🔒 Setup a security policy

---

CODE_OF_CONDUCT.md

❌ New feature
❌ Fix an issue
None

👮 Add a code of conduct

---

README.md

❌ New feature
❌ Fix an issue
None

📝 Add Snyk badge for package quality

---

README.md

❌ New feature
❌ Fix an issue
None

📝 Add semver stability badge

---

README.md

Too many badges. Need to do some cleaning. 
❌ New feature
❌ Fix an issue
None

📝 Remove dependencies related badges

---

.github/actions/github-actions-comments/index.cjs
.github/workflows/request-deploy-netlify.yml

❌ New feature
❌ Fix an issue
✔️ Other: *ci*
None

👷 Rework workflow "Request Deploy Netlify"

---

.github/actions/deploy-netlify/index.cjs
.github/actions/github-actions-comments/index.cjs
.github/workflows/build-status.yml
.github/workflows/request-deploy-netlify.yml

❌ New feature
❌ Fix an issue
✔️ Other: *ci*
None

👷 Clean old netlify job

---

.github/workflows/request-deploy-netlify.yml

❌ New feature
❌ Fix an issue
✔️ Other: *ci*
None

👷 Fix skip check for 'Deploy to Netlify'

---

.github/actions/github-actions-comments/index.cjs

❌ New feature
❌ Fix an issue
✔️ Other: *ci*
None

👷 Fix API calls for octokit in Netlify job

---

.github/actions/github-actions-comments/action.yml
.github/actions/github-actions-comments/index.cjs
.github/workflows/request-deploy-netlify.yml

❌ New feature
❌ Fix an issue
✔️ Other: *ci*
None

👷 Post reactions for netlify on issue comment

---

.github/actions/deploy-netlify/index.cjs

✔️/❌ New feature
✔️/❌ Fix an issue
✔️/❌ Documentation improvement
✔️/❌ Other: *please explain*

👷 Do not add new lines when adding comit hash in deploy message

---

.github/actions/deploy-netlify/index.cjs

✔️/❌ New feature
✔️/❌ Fix an issue
✔️/❌ Documentation improvement
✔️/❌ Other: *please explain*

👷 Do not add new lines when adding comit hash in deploy message (2)

---

documentation/Tips.md

❌ New feature
❌ Fix an issue
None

📝 Add tip regarding "Value depending on another one"

---

.github/workflows/build-status.yml

❌ New feature
❌ Fix an issue
None

✅ Add `--strict` option for tests on types

---

.github/workflows/build-status.yml
test/type/tsconfig.json

❌ New feature
❌ Fix an issue
None

✅ Add `--strict` option for tests on types (2)

---

src/utils/stringify.ts
test/unit/utils/stringify.spec.ts

✔️ New feature
❌ Fix an issue
Possible impact on stringified values but actually no problems expected.

✨ Support sparse arrays in stringify

---

test/unit/utils/stringify.spec.ts

❌ New feature
❌ Fix an issue
None

✅ Better coverage for stringify of sparse arrays

---

.github/workflows/build-status.yml
src/check/arbitrary/RecordArbitrary.ts
test/type/main.ts

Fixes #1453
❌ New feature
Typings of record

🚑 Fixing typings of `record` altered by version 2.11.0

---

.github/workflows/build-status.yml
test/type/main.ts

❌ New feature
❌ Fix an issue
✔️ Other: *ci*
None

👷 Check typings against more versions of TS

---

.github/workflows/build-status.yml

Reverts dubzzz/fast-check#1462

Revert "⬆️ Bump JamesIves/github-pages-deploy-action from 3.7.1 to 4.0.0"

---

src/fast-check-default.ts

🏷️ Add missing export for double constraints

---

.github/workflows/build-status.yml
.github/workflows/codeql-analysis.yml
CHANGELOG.md
CONTRIBUTING.md
README.md
codemods/unify-signatures/README.md
documentation/AdvancedArbitraries.md
documentation/HandsOnPropertyBased.md
documentation/HandsOnPropertyBasedJs.md
documentation/RaceConditions.md
documentation/Tips.md
example/003-misc/mazeGenerator/src/mazeGenerator.ts
example/003-misc/roman/src/roman.ts
example/README.md
src/check/arbitrary/ArrayArbitrary.ts
src/check/arbitrary/FloatingPointArbitrary.ts
src/check/arbitrary/IntegerArbitrary.ts
src/check/arbitrary/LoremArbitrary.ts
src/check/arbitrary/ObjectArbitrary.ts
src/check/arbitrary/OptionArbitrary.ts
src/check/arbitrary/SetArbitrary.ts
src/check/arbitrary/StringArbitrary.ts
src/check/arbitrary/SubarrayArbitrary.ts
src/check/model/commands/CommandsArbitrary.ts

❌ New feature
❌ Fix an issue
✔️ Other: *renaming*
```
git branch -m master main
git fetch origin
git branch -u origin/main main
```
None

🚚 Rename master into main

---

documentation/Arbitraries.md
perf/tasks.js
src/check/arbitrary/LoremArbitrary.ts
test/unit/check/arbitrary/LoremArbitrary.spec.ts

❌ New feature
❌ Fix an issue
Remove deprecated signatures of `fc.lorem`.

💥 Remove deprecated signatures of `fc.lorem`

---

README.md

❌ New feature
❌ Fix an issue
None

📝 Build status should open actions page filtered on main

---

README.md

❌ New feature
❌ Fix an issue
None

📝 Build status should open builds page filtered on main

---

src/check/arbitrary/AsyncSchedulerArbitrary.ts
src/check/arbitrary/RecordArbitrary.ts
src/check/arbitrary/SubarrayArbitrary.ts
src/check/model/ModelRunner.ts
src/check/runner/Runner.ts
src/check/runner/Sampler.ts
src/check/runner/reporter/RunExecution.ts
test/e2e/Shadows.spec.ts
test/unit/check/arbitrary/SparseArrayArbitrary.itest.spec.ts
test/unit/check/arbitrary/UuidArbitrary.itest.spec.ts
test/unit/check/arbitrary/generic/GenericArbitraryHelper.ts
test/unit/check/runner/reporter/RunExecution.spec.ts
tsconfig.json

Safer build
❌ New feature
❌ Fix an issue
Maybe a typing issue with `scheduleSequence` but actually it would highlight a real bug.

🔧 Enable strict mode in tsconfig

---

test/unit/check/arbitrary/helpers/ArrayInt64.spec.ts

❌ New feature
❌ Fix an issue
None

✅ Fix coverage flakiness on add64

---

.github/workflows/build-status.yml

❌ New feature
❌ Fix an issue
None

👷‍♂️ Run ESM tests against node 13

---

src/check/arbitrary/FrequencyArbitrary.ts
test/unit/check/arbitrary/FrequencyArbitrary.spec.ts

❌ New feature
❌ Fix an issue
✔️ Other: *refactoring*
None

♻️ Rework initialisation phase of `fc.frequency`

---

src/check/arbitrary/OneOfArbitrary.ts
test/unit/check/arbitrary/OneOfArbitrary.spec.ts

❌ New feature
❌ Fix an issue
✔️ Other: *refactoring*
None

♻️ Rework initialisation phase of `fc.oneof`

---

documentation/Arbitraries.md
src/check/arbitrary/FrequencyArbitrary.ts
test/unit/check/arbitrary/FrequencyArbitrary.itest.spec.ts
test/unit/check/arbitrary/FrequencyArbitrary.utest.spec.ts

✔️ New feature
❌ Fix an issue
None

✨ Add `maxDepth` constraint on `fc.frequency`

---

documentation/Arbitraries.md
src/check/arbitrary/FrequencyArbitrary.ts
src/check/arbitrary/helpers/DepthContext.ts
test/unit/check/arbitrary/FrequencyArbitrary.itest.spec.ts
test/unit/check/arbitrary/FrequencyArbitrary.utest.spec.ts

✔️ New feature
❌ Fix an issue
None

✨ Ability to share depth accross instances

---

test/unit/check/arbitrary/generic/GenericArbitraryHelper.ts

❌ New feature
❌ Fix an issue
None

✅ Better errors for isValidValue in helpers

---

documentation/Arbitraries.md
src/check/arbitrary/FrequencyArbitrary.ts
src/check/arbitrary/OptionArbitrary.ts
test/e2e/RecursiveStructures.spec.ts

✔️ New feature
❌ Fix an issue
None

✨ Add recursive constraints on `fc.option`

---

src/check/property/IgnoreEqualValuesProperty.ts
src/check/runner/DecorateProperty.ts
src/check/runner/configuration/Parameters.ts

❌ New feature
❌ Fix an issue
None

📝 Add missing annotations and jsdoc

---

example/002-recursive/isSearchTree/arbitraries/BinaryTreeArbitrary.ts
src/check/arbitrary/LetRecArbitrary.ts
test/legacy/node-8/main.js

❌ New feature
❌ Fix an issue
None

📝 Update some `fc.memo` to `fc.letrec`

---

src/check/arbitrary/OneOfArbitrary.ts
src/fast-check-default.ts
test/unit/check/arbitrary/OneOfArbitrary.utest.spec.ts

🩹 Add missing export for `OneOfConstraints`

---

documentation/Runners.md
src/check/property/IgnoreEqualValuesProperty.ts
src/check/runner/DecorateProperty.ts
src/check/runner/configuration/Parameters.ts
src/check/runner/configuration/QualifiedParameters.ts
test/e2e/IgnoreEqualValues.spec.ts
test/unit/check/property/IgnoreEqualValuesProperty.spec.ts
test/unit/check/runner/DecorateProperty.spec.ts
test/unit/check/runner/configuration/QualifiedParameters.spec.ts

✔️ New feature
❌ Fix an issue
None

✨ Introduce a way to mark equal values as skipped

---

.github/workflows/build-status.yml

❌ New feature
❌ Fix an issue
✔️ Other: *ci improvment*
None

👷 Stricter conditions to trigger workflow on `push`

---

.github/workflows/build-status.yml

❌ New feature
❌ Fix an issue
None

👷 Stricter conditions to trigger workflow on `push` (2)

---

README.md

❌ New feature
❌ Fix an issue
None

📝 Only mark relevant titles as H* in the Readme

---

README.md

❌ New feature
❌ Fix an issue
None

📝 Move back to H2 for titles in the Readme

---

src/check/symbols.ts
src/fast-check-default.ts

✔️ New feature
❌ Fix an issue
None

✨ Document and expose clone related methods

---

example/package.json
example/yarn.lock

Reverts dubzzz/fast-check#1679

Revert "⬆️ Bump @testing-library/user-event from 12.8.0 to 13.1.1 in /example"

---

src/check/arbitrary/definition/Shrinkable.ts
test/unit/check/arbitrary/definition/Shrinkable.spec.ts

❌ New feature
Potential impacts on:
Only if one of the generators produces cloneable values.

🐛 Apply cloneMethod on map/filter instances of Shrinkable

---

README.md

fix: grammar

---

src/check/arbitrary/LetRecArbitrary.ts
test/unit/check/arbitrary/LetRecArbitrary.utest.spec.ts

❌ New feature
❌ Fix an issue
✔️ Other: *remove useless code*
None

♻️ Simplify letrec initial construction

---

src/check/arbitrary/FrequencyArbitrary.ts

❌ New feature
❌ Fix an issue
✔️ Other: *refactor*
None, but if any on frequency, oneof and option for:
- Shrink values impact

♻️ Migrate frequency to NextArbitrary

---

src/arbitrary/_internals/IntegerArbitrary.ts

❌ New feature
❌ Fix an issue
None

♻️ Remove unneeded if-branch in shrinker for integer

---

src/arbitrary/_internals/BigIntArbitrary.ts

❌ New feature
❌ Fix an issue
✔️ Other: *refactoring*
None

♻️ Remove unneeded if-branch in shrinker for bigint

---

documentation/Tips.md
example/005-race/autocomplete/main.spec.tsx
example/005-race/debounced-autocomplete/main.spec.tsx
example/005-race/todolist/main.spec.tsx
example/005-race/userProfile/main.spec.tsx
perf/tasks.js
src/check/arbitrary/ObjectArbitrary.ts
test/unit/check/arbitrary/DoubleNextArbitrary.utest.spec.ts
test/unit/check/arbitrary/FloatNextArbitrary.utest.spec.ts

Fixes bad usages detected while working on #1492.
❌ New feature
❌ Fix an issue
None

👽️ Migrate missing snippets to our new APIs

---

src/check/arbitrary/MemoArbitrary.ts
test/unit/check/arbitrary/MemoArbitrary.utest.spec.ts

❌ New feature
❌ Fix an issue
✔️ Other: *refactor*
Nothing expected

♻️ Simplify internal implementation of `memo`

---

test/unit/arbitrary/_internals/LazyArbitrary.spec.ts
test/unit/arbitrary/letrec.spec.ts

❌ New feature
❌ Fix an issue
None

✅ Rewrite tests dealing with letrec

---

src/check/arbitrary/ConstantArbitrary.ts

❌ New feature
❌ Fix an issue
✔️ Other: *migrate to next arbitrary*
No impact expected. But if any: `constant`, `clonedConstant`, `constantFrom`

♻️ Migrate constant to NextArbitrary

---

src/arbitrary/_internals/ConstantArbitrary.ts

✔️ New feature
❌ Fix an issue
None - mostly internal change to prepare https://github.com/dubzzz/fast-check/pull/1750

✨Add support for cloneables in ConstantArbitrary

---

documentation/Arbitraries.md
src/check/arbitrary/MixedCaseArbitrary.ts
test/e2e/__snapshots__/NoRegressionBigInt.spec.ts.snap

✔️ New feature
❌ Fix an issue
Generated values impact: `mixedCase`

✨ Add support for bias in `mixedCase`

---

documentation/Arbitraries.md
src/check/arbitrary/MixedCaseArbitrary.ts
test/e2e/__snapshots__/NoRegressionBigInt.spec.ts.snap

https://github.com/dubzzz/fast-check/pull/1758 was not applying bias correctly.
❌ New feature
Generated values impact: `mixedCase`

🐛 Not properly biased `mixedCase`

---

src/check/arbitrary/AsyncSchedulerArbitrary.ts

❌ New feature
❌ Fix an issue
None expected

♻️ Migrate `scheduler` to `NextArbitrary`

---

src/arbitrary/_internals/StreamArbitrary.ts
src/arbitrary/infiniteStream.ts
src/fast-check-default.ts
test/unit/arbitrary/StreamArbitrary.spec.ts

❌ New feature
❌ Fix an issue
✔️ Other: *moving code*
None expected.

🚚 Move stream arbitraries into /arbitrary

---

test/unit/arbitrary/_internals/ConstantArbitrary.spec.ts

❌ New feature
❌ Fix an issue
None

💚 FIX Assumptions in tests related to `ConstantArbitrary`

---

src/stream/Stream.ts
src/stream/StreamHelpers.ts
test/e2e/__snapshots__/NoRegression.spec.ts.snap
test/unit/arbitrary/StreamArbitrary.spec.ts
test/unit/stream/Stream.spec.ts

🐛 `Stream.take` pull one unneeded value from the source

---

example/package.json
example/yarn.lock

Reverts dubzzz/fast-check#1811

Revert "⬆️ Bump @testing-library/user-event from 12.8.0 to 13.1.8 in /example"

---

.github/workflows/build-status.yml
.github/workflows/request-deploy-netlify.yml

❌ New feature
❌ Fix an issue
None

👷 Build against Node 16.x

---

src/arbitrary/_internals/builders/CharacterArbitraryBuilder.ts
src/arbitrary/_internals/mappers/IndexToCharString.ts
test/unit/arbitrary/_internals/mappers/IndexToCharString.spec.ts

❌ New feature
❌ Fix an issue
No

🚚 Extract internal mapper into its own file

---

src/arbitrary/_internals/mappers/IndexToMappedConstant.ts
src/arbitrary/mapToConstant.ts
src/check/arbitrary/helpers/SpecificCharacterRange.ts
src/fast-check-default.ts
test/unit/arbitrary/MapToConstantArbitrary.spec.ts

❌ New feature
❌ Fix an issue
No

🚚 Move `mapToConstant` arbitrary into /arbitrary

---

src/arbitrary/_internals/mappers/IndexToMappedConstant.ts

Fixes #1841
❌ New feature
None

🐛 Build reverse-mapping built by `mapToConstant` for node 10

---

src/arbitrary/_internals/mappers/KeyValuePairsToObject.ts
src/arbitrary/dictionary.ts
test/unit/arbitrary/_internals/mappers/KeyValuePairsToObject.spec.ts
test/unit/arbitrary/dictionary.spec.ts

✔️ New feature
❌ Fix an issue
None

✨ Add built-in unmapper support onto dictionary

---

.github/PULL_REQUEST_TEMPLATE.md

Current template for Pull Request was too complex to fill. It has been reworked to be simpler to fill.

📝 Rework PR template

---

test/unit/arbitrary/dictionary.spec.ts

💚 Fix wrongly written `isCorrect` in tests on `dictionary`

---

src/arbitrary/_internals/builders/FullRecordArbitraryBuilder.ts
src/arbitrary/_internals/helpers/EnumerableKeysExtractor.ts
src/arbitrary/record.ts
src/fast-check-default.ts
test/unit/arbitrary/RecordArbitrary.spec.ts

🚚 Move `record` arbitrary into /arbitrary

---

src/arbitrary/_internals/builders/PartialRecordArbitraryBuilder.ts

⚡️ Remove unneeded `map` in `record` for required keys

---

test/unit/arbitrary/nat.spec.ts

✏️ Fix typos in naming for `describe` on `nat`

---

src/arbitrary/_internals/mappers/KeyValuePairsToObject.ts
test/unit/arbitrary/_internals/mappers/KeyValuePairsToObject.spec.ts

🐛 Stricter unmapper for `dictionary` to prevent unmapping unrelated values

---

.github/PULL_REQUEST_TEMPLATE.md

📝 Fix typo in PR template

---

documentation/AdvancedArbitraries.md

📝 Update outdated links in `AdvancedArbitraries.md`

---

src/check/arbitrary/definition/ConverterFromNext.ts
src/check/arbitrary/definition/ConverterToNext.ts

⚡️ Try to optimize conversions from/to `NextValue`

---

src/check/arbitrary/definition/ConverterFromNext.ts
src/check/property/AsyncProperty.generic.ts
src/check/property/Property.generic.ts

⚡️ Call `generate` on the `NextArbitrary` from `Property`

---

.github/PULL_REQUEST_TEMPLATE.md

📝 Add "Performance" category into the PR template

---

.github/actions/deploy-netlify/index.cjs

👷 Use the right API from octokit to call createComment

---

CONTRIBUTING.md

Improve yarn commands in contribution guide.

🔨fix contribution guide

---

.github/workflows/build-status.yml

👷 Drop Node 10 from CI tool-chain

---

.codesandbox/ci.json

👷 Override default version of node in codesandbox with node 14

---

.github/workflows/build-status.yml
package.json
src/arbitrary/_internals/TupleArbitrary.ts
src/check/arbitrary/definition/Converters.ts
test/unit/arbitrary/_internals/CloneArbitrary.spec.ts
test/unit/arbitrary/_internals/TupleArbitrary.spec.ts
yarn.lock

⬆️ Bump to typescript 4.3.2

---

src/arbitrary/_internals/ArrayArbitrary.ts

The arbitrary for arrays is extensively used in fast-check. Improving it of a few percents would benefit to the whole framework.
Up-to-now both `fc.array` and `fc.set` were using the same code to generate values. BUT `fc.set` has one more constraint compared to `fc.array`. In order not to negatively impact `fc.array` due to this constraint we just fork the code into two distinct paths: one able to deal with duplicates (to avoid them), the other not.

⚡️ Fork paths of array/set in `ArrayArbitrary::generate`

---

src/check/runner/Runner.ts
src/check/runner/utils/RunDetailsFormatter.ts
src/fast-check-default.ts
src/utils/stringify.ts
test/unit/utils/stringify.spec.ts

✨ Async reporters can enrich the output with async data

---

src/arbitrary/_internals/ArrayArbitrary.ts

♻️ Build context when building the item itself in `ArrayArbitrary`

---

documentation/HowItWorks.md

Fix the wording in the documentation from `generators produce barely and kind of value` to `nearly any kind of value`

📝 barely -> nearly

---

example/005-race/autocomplete/main.spec.tsx
example/005-race/counter/main.spec.ts
example/005-race/dependencyTree/main.spec.ts
example/005-race/todolist/main.spec.tsx
example/005-race/userProfile/main.spec.tsx

📝 Prefer more explicit async/await properties in `examples/`

---

src/check/model/commands/CommandWrapper.ts
src/utils/stringify.ts
test/unit/check/model/commands/CommandWrapper.spec.ts

✨ Forward the custom toString methods of the underlying commands

---

src/arbitrary/func.ts
test/e2e/NoRegression.spec.ts
test/e2e/__snapshots__/NoRegression.spec.ts.snap

✨ Better stringified value for `func` producing async values

---

src/check/arbitrary/definition/NextArbitrary.ts

🐛 Better detection for objects that could define `cloneMethod` in `map`

---

src/arbitrary/_internals/StreamArbitrary.ts
test/e2e/NoRegression.spec.ts
test/e2e/__snapshots__/NoRegression.spec.ts.snap

✨ Better stringified value for `infiniteStream` producing async values

---

src/check/symbols.ts
test/unit/check/symbols.spec.ts

🐛 Safer check for `cloneMethod` to also support prototype-less objects

---

documentation/Tips.md
src/fast-check-default.ts
src/utils/stringify.ts
test/unit/utils/stringify.spec.ts

✨ Expose custom to string methods

---

src/arbitrary/_internals/builders/CharacterRangeArbitraryBuilder.ts
src/arbitrary/webAuthority.ts
test/unit/arbitrary/webAuthority.spec.ts

✨ Add built-in unmapper support onto `webAuthority`

---

documentation/Arbitraries.md
src/arbitrary/jsonObject.ts
src/arbitrary/unicodeJsonObject.ts

📝 Clarify the case of `-0` on `jsonObject` and `unicodeJsonObject`

---

src/arbitrary/integer.ts

✏️ Clean badly renamed import in `integer`

---

test/unit/arbitrary/integer.spec.ts

✅ Fix tests on legacy versions of `integer`

---

src/check/model/commands/CommandsArbitrary.ts

♻️ Migrate commands to NextArbitrary

---

src/arbitrary/_internals/CommandsArbitrary.ts
src/arbitrary/commands.ts
src/fast-check-default.ts
test/unit/check/model/commands/CommandsArbitrary.spec.ts

🚚 Move commands arbitrary into /arbitrary

---

package.json

Adding yet another script to ease debugging and troubleshooting of issues.

🔨 Add `test:debug` script for easier debugging

---

src/arbitrary/_next/floatNext.ts
test/unit/arbitrary/_next/floatNext.spec.ts

✨ Add built-in unmapper support onto `float`

---

src/arbitrary/_next/doubleNext.ts
test/unit/arbitrary/_next/doubleNext.spec.ts

✨ Add built-in unmapper support onto `double`

---

test/e2e/AsyncScheduler.spec.ts

💚 Adapt e2e on `scheduler` for node 16

---

.github/workflows/build-status.yml
test/type/main.ts

This PR is currently waiting for something on `@types/node` side. There is cirrently an opened-discussion about issues linked to the flag `--exactOptionalPropertyType` and the typings declared within `@types/node`.
See https://github.com/DefinitelyTyped/DefinitelyTyped/discussions/54673

✅ Make sure `--exactOptionalPropertyTypes` is properly handled

---

test/unit/arbitrary/__test-helpers__/ComputeObjectDepth.ts
test/unit/arbitrary/jsonObject.spec.ts
test/unit/arbitrary/unicodeJsonObject.spec.ts

✅ Add tests for JSON arbitraries

---

src/arbitrary/_internals/helpers/QualifiedObjectConstraints.ts
src/arbitrary/anything.ts
src/arbitrary/object.ts

♻️ Simplify conversion to qualified object's constraints

---

src/arbitrary/json.ts
src/arbitrary/unicodeJson.ts

Mid-way between a bug and a feature. Actually a bug but for the end user the type was not just clear enough. So let's mark it as an improvement of the existing typings.

🏷️ Update too large typings on `json` and `unicodeJson`

---

src/random/generator/PureRandom.ts

🗑️ Mark forked typings of `pure-rand` as deprecated

---

README.md

📝 Remove outdated dependabot's badge

---

codemods/unify-signatures/README.md
codemods/unify-signatures/transform.cjs

♻️ Simplify codemod to be more focused

---

codemods/unify-signatures/README.md
codemods/unify-signatures/transform.cjs
test/e2e/codemods/UnifySignatures.spec.ts
test/e2e/codemods/__snapshots__/UnifySignatures.spec.ts.snap

🐛 No dangerous transform in codemod

---

codemods/unify-signatures/transform.cjs
test/e2e/codemods/UnifySignatures.spec.ts
test/e2e/codemods/__snapshots__/UnifySignatures.spec.ts.snap

✅ Check codemod against several parsers

---

documentation/HandsOnPropertyBased.md
documentation/HandsOnPropertyBasedJs.md
documentation/HowItWorks.md
documentation/RaceConditions.md

I only fixed a small typo error 😅

fix: small typo error

---

src/arbitrary/_internals/FrequencyArbitrary.ts
src/arbitrary/frequency.ts
src/arbitrary/lorem.ts
src/arbitrary/oneof.ts
src/arbitrary/option.ts
src/check/arbitrary/definition/Arbitrary.ts
test/unit/arbitrary/frequency.spec.ts
test/unit/arbitrary/oneof.spec.ts
test/unit/arbitrary/option.spec.ts

♻️ Clean src thanks to `NextArbitrary`

---

test/unit/check/arbitrary/definition/Arbitrary.utest.spec.ts

Follow-up of #2515!
It should be squashed with #2515 for the final release.

✅ Switch to `NextArbitrary` was incomplete in tests

---

documentation/Tips.md

Fix typo (deinable -> definable)

---

.github/actions/reaction-to-comment.cjs
.github/workflows/please-actions.yml
.github/workflows/request-deploy-netlify.yml

👷 Fix deploy to Netlify

---

.github/workflows/please-actions.yml

👷 Fully remove external script for reactions

---

.github/workflows/please-actions.yml

👷 Add "please merge" action

---

.github/workflows/please-actions.yml

👷 Add "please debug" action

---

.github/workflows/please-actions.yml

👷 Shorter github-script

---

.github/workflows/please-actions.yml

👷 Rename netlify "please deploy"

---

.github/actions/deploy-netlify/index.cjs

👷 Fix GH action for deploy-netlify

---

.github/actions/deploy-netlify/index.cjs

👷 Trim ANSI modifiers for deploy-netlify

---

.github/workflows/please-actions.yml

👷 More verbose "please debug"

---

.github/workflows/please-actions.yml

👷 More generic "please merge"

---

.github/workflows/please-actions.yml

👷 Rewrite "please merge" with JavaScript

---

.github/workflows/please-actions.yml

👷 Wrong ref retrieval in "please merge"

---

.github/workflows/please-actions.yml

👷 Nicer log in "please merge"

---

documentation/Arbitraries.md
src/arbitrary/set.ts
src/fast-check-default.ts

✨ Selector-based compare for `set`

---

documentation/Arbitraries.md
src/arbitrary/_internals/helpers/SameValueSet.ts
src/arbitrary/_internals/helpers/SameValueZeroSet.ts
src/arbitrary/set.ts
test/unit/arbitrary/_internals/helpers/SameValueSet.spec.ts
test/unit/arbitrary/_internals/helpers/SameValueZeroSet.spec.ts

✨ Add types of operators for set

---

src/arbitrary/_internals/builders/AnyArbitraryBuilder.ts
src/arbitrary/dictionary.ts
src/arbitrary/sparseArray.ts

⚡️ Switch to optimized compare of set internally

---

.github/workflows/generate-changelog.yml

👷 Attempt to generate changelog from GitHub Actions

---

.github/workflows/generate-changelog.yml

👷 Verbose fails when generating changelogs

---

.github/workflows/generate-changelog.yml

👷 Attempt to fix action building changelog

---

.github/workflows/generate-changelog.yml

👷 Do not scope variables inside try/catch for changelog

---

.github/workflows/generate-changelog.yml

👷 Report errors in logs instead of throwing when computing changelog

---

.github/workflows/generate-changelog.yml

👷 Fix typo when building maintenance changelog

---

.github/workflows/generate-changelog.yml

👷 Last little changes to adapt auto changelog script

---

.github/workflows/publish-version.yml

👷 Add a publish version GitHub Action

---

.github/workflows/generate-changelog.yml
.github/workflows/scripts/generate-changelog.cjs

👷 Extract the script generating changelog

---

.github/workflows/generate-changelog.yml
.github/workflows/scripts/generate-changelog.cjs

👷 Create PRs with updated CHANGELOG.md from action

---

.github/workflows/scripts/generate-changelog.cjs

👷 Import from fs and not fs/promises for action

---

.github/workflows/generate-changelog.yml

👷 Fill head with the name of the newly created branch

---

.github/workflows/scripts/generate-changelog.cjs

👷 Better naming for branches generated by actions

---

.github/workflows/generate-changelog.yml
.github/workflows/scripts/generate-changelog.cjs

👷 Some refinements for commit name of actions

---

.github/workflows/publish-version.yml

👷 Properly define the tag when publishing versions

---

.github/workflows/scripts/generate-changelog.cjs

Understand `:fire:` as some kind of cleaning. The official meaning being: "Remove code or files.".

👷 Support fire emoji in changelog

---

documentation/Arbitraries.md
src/arbitrary/sparseArray.ts

🔥 Remove redundant computation in `sparseArray`

---

documentation/Tips.md
src/arbitrary/_internals/helpers/MaxLengthFromMinLength.ts
src/check/runner/configuration/GlobalParameters.ts

✨ Add ability to configure a base size

---

documentation/Arbitraries.md
src/arbitrary/set.ts

✨ Add built-in support for `size` to `set`

---

documentation/Arbitraries.md
src/arbitrary/_internals/builders/AnyArbitraryBuilder.ts
src/arbitrary/_internals/helpers/QualifiedObjectConstraints.ts
src/arbitrary/object.ts

✨ Add support for size onto object arbitraries

---

src/arbitrary/_internals/builders/AnyArbitraryBuilder.ts

✨ Forward size of `anything` to underlying `sparseArray`

---

src/arbitrary/ipV6.ts
test/unit/arbitrary/__test-helpers__/NextArbitraryAssertions.ts
test/unit/arbitrary/ipV6.spec.ts

✨ Make ipV6 independent of size global settings

---

test/unit/arbitrary/_internals/helpers/StrictlyEqualSet.spec.ts

✅ More stable test on StrictlyEqualSet

---

documentation/Arbitraries.md
src/arbitrary/_internals/builders/TypedIntArrayArbitraryBuilder.ts
src/arbitrary/float32Array.ts
src/arbitrary/float64Array.ts

✨ Add support for size on typed arrays

---

documentation/Arbitraries.md
src/arbitrary/lorem.ts

✨ Add support for `size` onto `lorem`

---

src/arbitrary/_internals/helpers/MaxLengthFromMinLength.ts
test/unit/arbitrary/_internals/helpers/MaxLengthFromMinLength.spec.ts

🐛 Cap the max generated length with max length

---

test/unit/arbitrary/__test-helpers__/GlobalSettingsHelpers.ts
test/unit/arbitrary/__test-helpers__/NextArbitraryAssertions.ts
test/unit/arbitrary/__test-helpers__/SizeHelpers.ts
test/unit/arbitrary/_internals/helpers/MaxLengthFromMinLength.spec.ts

✅ Add more tests on size related helpers

---

src/arbitrary/_internals/helpers/QualifiedObjectConstraints.ts

Not really a bug so far as the feature has not been released yet. But it is one from a code point of view as currently main branch would not be suitable for a release without this fix.

🐛 Pass size to any key and default value in `anything`

---

documentation/Arbitraries.md
documentation/Tips.md
src/arbitrary/_internals/CommandsArbitrary.ts
src/arbitrary/commands.ts
src/check/model/commands/CommandsContraints.ts
test/e2e/ModelBased.spec.ts
test/e2e/model/CommandsArbitrary.spec.ts

✨ Add support for `size` on `commands`

---

test/unit/arbitrary/_internals/AdapterArbitrary.spec.ts

✅ Stabilize tests of `adapter` by switching to `Object.is`

---

test/unit/arbitrary/_internals/ArrayArbitrary.spec.ts

✅ Add some tests onto `ArrayArbitrary`

---

documentation/css/typedoc.css
src/check/runner/Runner.ts
typedoc.json

📝 Reorder assert overloads to render better documentation

---

.github/workflows/scripts/generate-changelog.cjs

🔨 Mark changes for "deprecated" as feature

---

.github/workflows/publish-version.yml

Creating the tag that ay was not launching the deployment workflow. So for now, we will tag the commit manually to trigger the workflow.

👷 Stop creating the tags via action

---

.github/workflows/build-status.yml

👷 Preserve Jest's cache accross runs

---

documentation/Arbitraries.md
src/arbitrary/_internals/builders/AnyArbitraryBuilder.ts
src/arbitrary/dictionary.ts
src/arbitrary/set.ts
src/arbitrary/sparseArray.ts
test/unit/arbitrary/sparseArray.spec.ts

🗑️ Mark `fc.set` as deprecated

---

test/unit/arbitrary/uniqueArray.spec.ts

✅ Better coverage for `selector` and `comparator` in `uniqueArray`

---

.github/workflows/scripts/generate-changelog.cjs

🔨 Properly change package.json when generating changelog

---

example/005-race/supertest/app.spec.ts
example/005-race/supertest/src/app.ts
example/005-race/supertest/src/appBug.ts
example/005-race/supertest/src/db.ts
example/package.json
example/yarn.lock

📝 Add examples based on supertest

---

src/check/runner/configuration/GlobalParameters.ts

🐛 Narrow return type of readConfigureGlobal

---

documentation/Tips.md

Instead of using the old (corrupted) faker library (https://www.npmjs.com/package/faker), reference the newer fork instead (https://www.npmjs.com/package/@faker-js/faker)

📝 Replace faker with the new official fork of faker

---

documentation/Arbitraries.md
example/002-recursive/isSearchTree/arbitraries/BinaryTreeArbitrary.ts
src/arbitrary/_internals/FrequencyArbitrary.ts
src/arbitrary/_internals/helpers/JsonConstraintsBuilder.ts
src/arbitrary/_internals/helpers/MaxLengthFromMinLength.ts
src/arbitrary/_internals/helpers/QualifiedObjectConstraints.ts
src/arbitrary/frequency.ts
src/arbitrary/jsonObject.ts
src/arbitrary/letrec.ts
src/arbitrary/oneof.ts
src/arbitrary/option.ts
src/arbitrary/unicodeJsonObject.ts
src/fast-check-default.ts
test/e2e/NoRegression.spec.ts
test/e2e/RecursiveStructures.spec.ts
test/legacy/node-8/main.js
test/unit/arbitrary/_internals/FrequencyArbitrary.spec.ts
test/unit/arbitrary/_internals/builders/AnyArbitraryBuilder.spec.ts
test/unit/arbitrary/_internals/helpers/MaxLengthFromMinLength.spec.ts
test/unit/arbitrary/_internals/implementations/SchedulerImplem.spec.ts
test/unit/arbitrary/frequency.spec.ts
test/unit/arbitrary/jsonValue.spec.ts
test/unit/arbitrary/option.spec.ts
test/unit/arbitrary/unicodeJsonValue.spec.ts

✨ Extend `size` to defaulting of `depthFactor`

---

test/e2e/documentation/Docs.md.spec.ts

Up-to-now the automatically generated documentation was not able to show statistics concerning how well the values were spread. Now, we will be able to do so by executing the same Docs.md.spec.ts test file but with new macros.

📝 Add ability to show statistics in generated doc

---

renovate.json

👷 Attempt to fix renovate

---

renovate.json

👷 Stop pinning dependencies with renovate

---

.github/ISSUE_TEMPLATE/Question.md

📝 Update "Question" template to request users to prefer "Discussions"

---

example/001-simple/decompPrime/main.spec.ts
example/001-simple/fibonacci/main.spec.ts
example/002-recursive/isSearchTree/arbitraries/BinarySearchTreeArbitrary.ts
example/003-misc/knight/arbitraries/SpaceArbitrary.ts
example/003-misc/mazeGenerator/main.spec.ts
example/003-misc/roman/main.spec.ts
example/005-race/dependencyTree/main.spec.ts
src/arbitrary/_internals/ArrayArbitrary.ts
src/arbitrary/_internals/builders/CharacterArbitraryBuilder.ts
src/arbitrary/_internals/builders/CompareFunctionArbitraryBuilder.ts
src/arbitrary/date.ts
test/e2e/GenerateAllValues.spec.ts
test/e2e/Shadows.spec.ts
test/e2e/WithProvidedExamples.spec.ts
test/e2e/arbitraries/ArrayArbitrary.spec.ts
test/e2e/arbitraries/IntegerArbitrary.spec.ts
test/e2e/arbitraries/OneOfArbitrary.spec.ts
test/unit/arbitrary/_internals/ArrayArbitrary.spec.ts
test/unit/arbitrary/_internals/builders/TypedIntArrayArbitraryBuilder.spec.ts
test/unit/arbitrary/_internals/helpers/BiasNumericRange.spec.ts
test/unit/arbitrary/_internals/helpers/FloatHelpers.spec.ts
test/unit/arbitrary/_internals/helpers/ToggleFlags.spec.ts
test/unit/arbitrary/date.spec.ts
test/unit/check/runner/Runner.spec.ts
test/unit/check/runner/Sampler.spec.ts
test/unit/check/runner/SourceValuesIterator.spec.ts
test/unit/check/runner/configuration/QualifiedParameters.spec.ts
test/unit/utils/stringify.spec.ts

♻️ Replace deprecated usages of `integer` by constraint-based ones

---

src/arbitrary/_internals/builders/AnyArbitraryBuilder.ts

Those TODOs were mostly old remarks not true anymore following the migration from `set` to `uniqueArray`. While not true anymore, they allowed some minor changes to stop overriding the default comparator when not needed.

♻️ Adapt some code in `anything` thanks to TODO

---

documentation/Tips.md

Just fixes link to timeout section in tips doc

📝 fix link to timeout section in tips doc

---

.github/workflows/scripts/generate-changelog.cjs

While it should not be used to release minor versions (no breaking) not major ones (not the right format), the generated CHANGELOG will help to build the CHANGELOG for the next major.

🔨 Support breaking changes in generated CHANGELOG

---

.github/workflows/scripts/generate-changelog.cjs

🔨 Support typing related PRs in CHANGELOG

---

packages/run-test-bundle.sh

👷 Simplify test-bundle script following merge of Yarn 3

---

packages/fast-check/jest.unit.config.cjs
packages/fast-check/package.json

👷 Fix script not using the right path

---

.github/workflows/build-status.yml

👷 Fix gh-pages publication follwoing move to monorepo

---

.gitignore

👷 Clean-up `.gitignore`

---

.github/workflows/generate-changelog.yml
.github/workflows/scripts/generate-changelog.cjs
.yarn/versions/02c891bf.yml

👷 Make use of `yarn version` for generate changelog

---

.github/workflows/scripts/generate-changelog.cjs

👷 Fix usages of `yarn version` when generating changelog

---

.yarn/versions/8650dd69.yml
packages/fast-check/README.md

📝 Rework the "bug discovered with fast-check" section of the README

---

.github/workflows/build-status.yml
.yarn/versions/beb2f1c9.yml
yarn.lock

👷 Check the need for `dedupe` on each CI run

---

.github/workflows/build-status.yml
.yarn/versions/088596ee.yml
package.json
yarn.lock

Adopt a more effecient caching strategy inspired by the cache optimization done by babel on their own repository. Instead of handling the cache strategy fully on our side we try to delegate part of it to `actions/setup-node`.
The idea is to call this action once for warm-up and then re-use this warm-up on all subsequent jobs.
Fixes #3009

👷 Cross-jobs caching for yarn

---

.yarn/versions/60fc0e89.yml
CONTRIBUTING.md
package.json

👷 Enhance and document version related rules for PRs

---

.github/actions/install-deps-with-current-fc/action.yml
.github/workflows/build-status.yml
.yarn/versions/cfdaa0c2.yml
package.json
packages/fast-check/package.json
packages/packaged/LICENSE
packages/packaged/README.md
packages/packaged/bin/packaged.js
packages/packaged/package.json
packages/packaged/src/packaged.ts
packages/packaged/tsconfig.json
yarn.lock

`@fast-check/packaged` is an internal but published utility used internally by the CI around `fast-check` to confirm that we properly bundle our code before publishing anything onto official registries.
New root scripts:
- `pack:all`: we pack all public packages to "{packageLocation}/package.tgz", package.tgz is the default name but we enforce it for clarity

🎉 First steps towards `@fast-check/packaged`

---

.github/workflows/build-status.yml

What changed:
- jobs gets re-ordered
- warm-up has been split into two distinct parts: default os and others
- jobs with unneeded dependencies have been simplified
What has to change:
- rename some jobs whose names are not adapted

👷 Faster workflow of GH Actions

---

.github/workflows/build-status.yml
.yarn/versions/6f837768.yml
packages/packaged/.gitignore
packages/packaged/jest.config.cjs
packages/packaged/package.json
packages/packaged/src/packaged.ts
packages/packaged/test/packaged.spec.ts
packages/packaged/tsconfig.json
packages/packaged/tsconfig.publish.json
yarn.lock

✅ Add some tests for `@fast-check/packaged`

---

.yarn/versions/4cb7827f.yml
packages/ava/CHANGELOG.md
packages/ava/README.md
packages/ava/package.json
packages/packaged/README.md

As I forgot to add the contributors that made `@fast-check/ava` possible, this PR will also add them as co-authors.

📝 Add missing README for `@fast-check/ava`

---

.yarn/versions/20c9f349.yml
packages/jest/CHANGELOG.md
packages/jest/README.md

📝 Basic README for `@fast-check/jest`

---

.yarn/versions/34e29aea.yml
packages/test-ava-bundle-cjs/README.md
packages/test-ava-bundle-esm/README.md
packages/test-jest-bundle-cjs/README.md
packages/test-jest-bundle-esm/README.md

📝 Add missing README files on bundle related tests

---

.github/workflows/generate-changelog.yml
.github/workflows/scripts/generate-changelog.cjs

👷 Better links in PR generating changelog

---

.github/workflows/scripts/generate-changelog.cjs

👷 Also commit `.yarn/versions` with changelogs

---

.github/workflows/build-status.yml

👷 Add missing `--access public` on publish

---

.github/FUNDING.yml

💸 Add GitHub Sponsors in funding sections

---

.github/workflows/build-status.yml

👷 Add missing Ubuntu env for e2e

---

.github/workflows/scripts/generate-changelog.cjs

🔨 Only commit `package.json` corresponding to impacted CHANGELOGs

---

.yarn/versions/ab6286cd.yml
packages/ava/CHANGELOG.md
packages/jest/CHANGELOG.md

🔧 Prepare 1.x for `@fast-check/{ava,jest}`

---

packages/fast-check/test/unit/utils/stringify.spec.ts

✅ Fix test comparing `stringify` and `JSON.stringify`

---

packages/fast-check/test/unit/arbitrary/record.spec.ts

✅ Fix tests on `record` wrongly manipulating `__proto__`

---

.all-contributorsrc
packages/fast-check/README.md

👥 Add matinzd as 'code' contributor

---

.github/workflows/build-status.yml
.yarn/versions/d57ea87f.yml
packages/poisoning/README.md
packages/poisoning/package.json

✨ Mark `@fast-check/poisoning` as public

---

.github/workflows/build-status.yml

👷 Auto-cancel previous runs on new commits

---

.yarn/versions/66305bf3.yml
packages/poisoning/src/internals/TrackDiffsOnGlobal.ts
packages/poisoning/test/internals/TrackDiffsOnGlobal.spec.ts

🐛 Properly distinguish from prototype and from instance

---

packages/fast-check/test/e2e/Poisoning.spec.ts

✅ Check poisoning against noop arbitrary (for now)

---

.yarn/versions/1ee87470.yml
packages/fast-check/package.json

🔨 Add script to run e2e tests in debug mode

---

.yarn/versions/dad29060.yml
packages/fast-check/src/check/arbitrary/definition/Arbitrary.ts
packages/fast-check/test/e2e/Poisoning.spec.ts

🐛 Clear poisoning instability in `filter`, `map`, `chain`

---

.github/workflows/scripts/generate-changelog.cjs

🔨 Better handle new projects in changelog generator

---

.yarn/versions/415cc4cf.yml
packages/fast-check/src/arbitrary/_internals/IntegerArbitrary.ts
packages/fast-check/src/arbitrary/_internals/helpers/BiasNumericRange.ts
packages/fast-check/src/arbitrary/_internals/helpers/DoubleHelpers.ts
packages/fast-check/src/arbitrary/_internals/helpers/FloatHelpers.ts
packages/fast-check/src/arbitrary/double.ts
packages/fast-check/src/arbitrary/float.ts
packages/fast-check/src/arbitrary/integer.ts
packages/fast-check/src/arbitrary/nat.ts
packages/fast-check/src/utils/stringify.ts
packages/fast-check/test/e2e/Poisoning.spec.ts

🐛 Make numeric arbitraries resistant to poisoning

---

packages/poisoning/test/main.spec.ts

✅(poisoning) Test against direct updates of globals

---

.yarn/versions/3c1a5020.yml
packages/fast-check/src/utils/stringify.ts
packages/fast-check/test/e2e/Poisoning.spec.ts

🐛 Make single char arbitraries resistant to poisoning

---

.yarn/versions/b4cafc0d.yml
packages/fast-check/src/arbitrary/_internals/helpers/CustomEqualSet.ts
packages/fast-check/src/arbitrary/_internals/mappers/CharsToString.ts
packages/fast-check/src/arbitrary/_internals/mappers/CodePointsToString.ts
packages/fast-check/src/arbitrary/_internals/mappers/PatternsToString.ts
packages/fast-check/src/arbitrary/_internals/mappers/StringToBase64.ts
packages/fast-check/src/arbitrary/asciiString.ts
packages/fast-check/src/arbitrary/fullUnicodeString.ts
packages/fast-check/src/arbitrary/hexaString.ts
packages/fast-check/src/arbitrary/string.ts
packages/fast-check/src/arbitrary/string16bits.ts
packages/fast-check/src/arbitrary/stringOf.ts
packages/fast-check/src/arbitrary/unicodeString.ts
packages/fast-check/src/utils/globals.ts
packages/fast-check/test/e2e/Poisoning.spec.ts

🐛 Make multi chars arbitraries resistant to poisoning

---

.yarn/versions/0fa4df25.yml
packages/fast-check/src/arbitrary/_internals/helpers/CustomEqualSet.ts

⚡️ Drop unneeded copy for full custom `uniqueArray`

---

packages/fast-check/src/arbitrary/_internals/builders/PartialRecordArbitraryBuilder.ts
packages/fast-check/src/arbitrary/_internals/helpers/EnumerableKeysExtractor.ts
packages/fast-check/src/arbitrary/_internals/mappers/ValuesAndSeparateKeysToObject.ts
packages/fast-check/src/utils/globals.ts
packages/fast-check/src/utils/stringify.ts
packages/fast-check/test/e2e/Poisoning.spec.ts

🐛 Make object arbitraries resistant to poisoning

---

.yarn/versions/d6cbe479.yml
packages/fast-check/src/arbitrary/_internals/mappers/TimeToDate.ts
packages/fast-check/src/arbitrary/date.ts
packages/fast-check/src/utils/globals.ts
packages/fast-check/src/utils/stringify.ts
packages/fast-check/test/e2e/Poisoning.spec.ts

🐛 Make typed arrays arbitraries resistant to poisoning

---

.yarn/versions/e31a4d1a.yml
packages/fast-check/src/arbitrary/letrec.ts
packages/fast-check/src/arbitrary/memo.ts
packages/fast-check/src/utils/globals.ts
packages/fast-check/test/e2e/Poisoning.spec.ts

🐛 Make recursive arbitraries resistant to poisoning

---

.yarn/versions/b43d7426.yml
packages/fast-check/src/arbitrary/_internals/builders/CompareFunctionArbitraryBuilder.ts
packages/fast-check/src/arbitrary/compareBooleanFunc.ts
packages/fast-check/src/arbitrary/compareFunc.ts
packages/fast-check/src/arbitrary/func.ts
packages/fast-check/test/e2e/Poisoning.spec.ts

🐛 Make function arbitraries resistant to poisoning

---

.yarn/versions/1c078047.yml
packages/fast-check/src/arbitrary/_internals/MixedCaseArbitrary.ts
packages/fast-check/src/arbitrary/_internals/builders/CharacterRangeArbitraryBuilder.ts
packages/fast-check/src/arbitrary/_internals/helpers/ToggleFlags.ts
packages/fast-check/src/arbitrary/_internals/mappers/EntitiesToIPv6.ts
packages/fast-check/src/arbitrary/_internals/mappers/NatToStringifiedNat.ts
packages/fast-check/src/arbitrary/_internals/mappers/NumberToPaddedEight.ts
packages/fast-check/src/arbitrary/_internals/mappers/PaddedEightsToUuid.ts
packages/fast-check/src/arbitrary/_internals/mappers/SegmentsToPath.ts
packages/fast-check/src/arbitrary/_internals/mappers/WordsToLorem.ts
packages/fast-check/src/arbitrary/domain.ts
packages/fast-check/src/arbitrary/emailAddress.ts
packages/fast-check/src/arbitrary/ipV4.ts
packages/fast-check/src/arbitrary/ipV4Extended.ts
packages/fast-check/src/arbitrary/mixedCase.ts
packages/fast-check/src/arbitrary/webAuthority.ts
packages/fast-check/src/arbitrary/webUrl.ts
packages/fast-check/src/utils/globals.ts
packages/fast-check/test/e2e/Poisoning.spec.ts

🐛 Make complex strings arbitraries resistant to poisoning

---

.github/workflows/scripts/generate-changelog.cjs

👷 Consider ⚡️ aka zap PRs as fixes for changelog

---

renovate.json

👷 Try to configure renovate to open more PRs

---

packages/ava/package.json
packages/fast-check/package.json
packages/jest/package.json
yarn.lock

🔥 Drop unused dependencies

---

.github/renovate.json

🔧 Change update strategy for renovate

---

.github/renovate.json

🔧 Update bump strategy of renovate

---

.github/workflows/scripts/generate-changelog.cjs

🔨 More verbose CHANGELOG script and continue on failure

---

.github/workflows/scripts/generate-changelog.cjs

🔨 Less verbose description for PRs of CHANGELOG

---

packages/poisoning/test/internals/CaptureAllGlobals.spec.ts

✅(poisoning) Check captured name for globals

---

.yarn/versions/36eb543b.yml
packages/fast-check/package.json
yarn.lock

⬆️ Bump required pure-rand to `^5.0.2`

---

.github/renovate.json

👷 Require renovate to always try to dedupe

---

.yarn/versions/992ade39.yml
packages/fast-check/jest.config.cjs
packages/jest/package.json
packages/packaged/jest.config.cjs
packages/poisoning/jest.config.cjs

🔧 Adapt configuration for new ts-jest

---

.yarn/versions/161c63aa.yml
packages/poisoning/src/internals/CaptureAllGlobals.ts
packages/poisoning/src/internals/PoisoningFreeArray.ts
packages/poisoning/test/internals/CaptureAllGlobals.spec.ts

🐛(poisoning) Compute smallest depth for each global

---

.github/workflows/please-actions.yml

👷 Attempt to fix "please deploy"

---

.yarn/versions/b8a5437c.yml
packages/poisoning/src/internals/CaptureAllGlobals.ts
packages/poisoning/src/internals/PoisoningFreeSet.ts
packages/poisoning/src/internals/types/AllGlobals.ts
packages/poisoning/test/internals/CaptureAllGlobals.spec.ts
packages/poisoning/test/internals/PoisoningFreeSet.spec.ts
packages/poisoning/test/internals/TrackDiffsOnGlobal.spec.ts

♻️(poisoning) Keep track of root ancestors

---

.github/workflows/please-actions.yml

👷 Build every package for "please deploy"

---

.yarn/versions/55fbbf4e.yml
packages/poisoning/src/internals/FilterNonEligibleDiffs.ts
packages/poisoning/src/internals/TrackDiffsOnGlobal.ts
packages/poisoning/src/main.ts
packages/poisoning/test/internals/FilterNonEligibleDiffs.spec.ts
packages/poisoning/test/internals/TrackDiffsOnGlobal.spec.ts

✨(poisoning) Add ability to ignore some roots

---

.yarn/versions/6421b19b.yml
packages/jest/jest.config.cjs
packages/jest/package.json

👷(jest) Extract jest config outside of package.json

---

.yarn/versions/2bc0bd38.yml
packages/poisoning/src/internals/CaptureAllGlobals.ts

✨(poisoning) Also track roots starting by "_"

---

.yarn/versions/17d2e240.yml
packages/jest/package.json
packages/jest/src/jest-fast-check.ts
packages/jest/test/itProp.spec.ts
yarn.lock

♻️(jest) Rely on `@jest/globals` for `@fast-check/jest`

---

.yarn/versions/5b25f869.yml
packages/ava/package.json
packages/ava/tsconfig.json
packages/ava/tsconfig.publish.json
packages/fast-check/jest.config.cjs
packages/jest/package.json
packages/jest/tsconfig.json
packages/jest/tsconfig.publish.json
packages/packaged/jest.config.cjs
packages/poisoning/jest.config.cjs

✅ Add missing "typecheck" scripts on packages

---

.github/workflows/scripts/generate-changelog.cjs

👷 Better PRs for changelogs cross packages

---

.yarn/versions/546af4c2.yml
packages/ava/package.json
packages/ava/tsconfig.publish.json
packages/ava/tsconfig.publish.types.json
packages/fast-check/tsconfig.publish.json
packages/fast-check/tsconfig.publish.types.json
packages/jest/package.json
packages/jest/tsconfig.publish.json
packages/jest/tsconfig.publish.types.json
packages/packaged/package.json
packages/packaged/tsconfig.publish.json
packages/packaged/tsconfig.publish.types.json
packages/poisoning/package.json
packages/poisoning/tsconfig.publish.json
packages/poisoning/tsconfig.publish.types.json
tsconfig.publish.json
tsconfig.publish.types.json

🔨 Factorize production `tsconfig.json`

---

.codesandbox/ci.json

👷 Publish `@fast-check/poisoning` on CodeSandbox's builds

---

.yarn/versions/3f25fd26.yml
packages/worker/test/main.properties.cjs
packages/worker/test/main.spec.ts

✅(worker) Add test on detection of unregistered properties

---

.yarn/versions/7981d8b0.yml
packages/worker/src/internals/MainThreadRunner.ts
packages/worker/src/internals/worker-pool/BasicPool.ts
packages/worker/src/internals/worker-pool/WorkerPool.ts
packages/worker/test/internals/worker-pool/BasicPool.spec.ts

✨(worker) Wait worker to be ready before querying it

---

.yarn/versions/f096709d.yml
packages/worker/README.md
packages/worker/src/main.ts
packages/worker/test/main.spec.ts

✨(worker) Introduce dedicated `assert` terminating workers

---

packages/fast-check/documentation/AdvancedArbitraries.md

This was out of date since moving to the monorepo, apparently

 📝 🐛 Sync with current path

---

packages/fast-check/documentation/HowItWorks.md

:memo: Improve grammar in HowItWorks

---

.yarn/versions/20d6d92b.yml
packages/jest/src/jest-fast-check.ts

✨(jest) Align seed computation with fast-check's one

---

.yarn/versions/cc7ad899.yml
packages/ava/src/ava-fast-check.ts

✨(ava) Align seed computation with fast-check's one

---

.yarn/versions/a654603f.yml
packages/jest/src/jest-fast-check.ts

🐛(jest) Pass the forged seed to the runner

---

.yarn/versions/ecbbce2f.yml
packages/ava/src/ava-fast-check.ts

🐛(ava) Pass the forged seed to the runner

---

.yarn/versions/ce4146a5.yml
packages/jest/src/jest-fast-check.ts

🐛(jest) Fallback on the seed coming from globals if any

---

.yarn/versions/7913cc63.yml
packages/ava/src/ava-fast-check.ts

🐛(ava) Fallback on the seed coming from globals if any

---

packages/jest/test/jest-fast-check.spec.ts

✅(jest) Faster tests without `babel-jest`

---

.yarn/versions/cd5c5583.yml
packages/worker/README.md
packages/worker/src/main.ts
packages/worker/test/main.properties.cjs

✨(worker) Better worker API for `property` via `propertyFor`

---

packages/fast-check/test/unit/arbitrary/_internals/implementations/SlicedBasedGenerator.spec.ts

✅ Stabilize tests of `SlicedBasedGenerator`

---

.yarn/versions/f605ac8e.yml
packages/fast-check/src/arbitrary/date.ts
packages/fast-check/src/fast-check-default.ts

🏷️ Explicitely declare typings for constraints on `date`

---

.yarn/versions/a4fed84e.yml
packages/fast-check/test/unit/arbitrary/__test-helpers__/ArbitraryAssertions.ts

✅ Poisoning checks compatible with watch mode

---

.yarn/versions/95af649d.yml
packages/ava/package.json
packages/fast-check/package.json
packages/jest/package.json
packages/packaged/package.json
packages/poisoning/package.json
packages/worker/package.json

💸 Add link to GitHub sponsors in funding

---

.yarn/versions/18f900e1.yml
packages/poisoning/src/internals/FilterNonEligibleDiffs.ts
packages/poisoning/src/internals/TrackDiffsOnGlobal.ts
packages/poisoning/src/main.ts
packages/poisoning/test/internals/FilterNonEligibleDiffs.spec.ts
packages/poisoning/test/internals/TrackDiffsOnGlobal.spec.ts

⚡️(poisoning) Faster diff tracking with pre-filtering of uneligible

---

.yarn/versions/3145b94a.yml
packages/poisoning/src/internals/FilterNonEligibleDiffs.ts
packages/poisoning/test/internals/FilterNonEligibleDiffs.spec.ts

⚡ (poisoning) Do not recompute ignore globals for attributes

---

.yarn/versions/b5979ebb.yml
packages/jest/README.md

📝(jest) Add new recommendations around Jest and `--show-seed`

---

packages/jest/README.md

📝(jest) Fix dead link in readme

---

.yarn/versions/d67cbf91.yml
packages/ava/CHANGELOG.md
packages/jest/CHANGELOG.md

📝 Update changelogs following backports

---

packages/jest/CHANGELOG.md

📝(jest) Add missing 'Typing' on PRs in changelog

---

.github/workflows/build-status.yml

👷(expect-type) Adapt publication workflow

---

.yarn/versions/d4bbed25.yml
packages/jest/src/jest-fast-check.ts
packages/jest/test/jest-fast-check.spec.ts

✨(jest) Add support for record-based `it.prop`

---

.yarn/versions/a798d33a.yml
packages/expect-type/package.json

🐛(expect-type) Fix types not being properly exported for ESM

---

.yarn/versions/52e05aca.yml
packages/poisoning/package.json

🐛(poisoning) Fix types not being properly exported for ESM

---

.yarn/versions/360ec246.yml
packages/worker/package.json

🐛(worker) Fix types not being properly exported for ESM

---

.yarn/versions/c688fd92.yml
packages/ava/package.json

🐛(ava) Fix types not being properly exported for ESM

---

.yarn/versions/2198c986.yml
packages/jest/README.md

📝(jest) Adapt documentation for new API based on `it`/`test`

---

.github/workflows/build-status.yml

👷 Limit scope of "All ...bump declared"

---

.yarn/versions/1571ad44.yml
packages/expect-type/README.md

📝(expect-type) Fix links in README

---

.yarn/versions/e1a0cb52.yml
packages/fast-check/src/arbitrary/_internals/TupleArbitrary.ts

♻️ Expose shrinker of tuples internally

---

.yarn/versions/629728e0.yml
packages/fast-check/src/arbitrary/_internals/ArrayArbitrary.ts
packages/fast-check/test/e2e/NoStackOverflowOnShrink.spec.ts

🐛 Avoid stack overflow during shrinking of arrays

---

.yarn/versions/c7fd55a8.yml
packages/jest/src/internals/TestBuilder.ts
packages/jest/src/internals/TestPropBuilder.ts
packages/jest/src/internals/TestWithPropRunnerBuilder.ts
packages/jest/src/internals/types.ts
packages/jest/src/jest-fast-check.ts

♻️(jest) Take `jest` and `fc` as input for main internals

---

.yarn/versions/fdead730.yml
packages/worker/package.json
packages/worker/src/internals/SharedTypes.ts
packages/worker/src/internals/worker-pool/WorkerPool.ts
packages/worker/test-bundle/main.cjs
packages/worker/test-bundle/main.mjs

🐛(worker) Unable to import in ESM mode

---

.yarn/versions/4b1c4552.yml
package.json
packages/fast-check/package.json
yarn.lock

👷 Drop circular deps for dev topo builds

---

.yarn/versions/8c771e26.yml
packages/jest/README.md
packages/jest/package.json
packages/jest/src/internals/TestWithPropRunnerBuilder.ts
packages/jest/src/jest-fast-check-worker.ts
packages/jest/test-bundle/worker.spec.cjs
packages/jest/test-bundle/worker.spec.mjs
packages/jest/test/jest-fast-check.spec.ts
yarn.lock

✨(jest) Add basic worker based runner

---

.all-contributorsrc
packages/fast-check/README.md

👥 Add new contributor tskj

---

.yarn/versions/294d69aa.yml
packages/jest/package.json
yarn.lock

🔧(jest) Add missing peerDependency for worker-based

---

.yarn/versions/75b971b8.yml
packages/ava/package.json
packages/expect-type/package.json
packages/fast-check/package.json
packages/jest/package.json
packages/packaged/package.json
packages/poisoning/package.json
packages/worker/package.json

💸 Re-order links in funding section

---

package.json

🔨 Add `--cache` option to Prettier

---

packages/jest/test/jest-fast-check.spec.ts

✅(jest) Properly categorize timeout tests

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.devcontainer/postCreateCommand.sh

🔨 Initialize default devcontainer

---

.devcontainer/Dockerfile
.devcontainer/devcontainer.json
.devcontainer/postCreateCommand.sh

🔨 Install and setup nvs inside Dockerfile

---

.yarn/versions/92718861.yml
packages/fast-check/src/check/runner/Runner.ts
packages/fast-check/src/check/runner/utils/PathWalker.ts

⚡️ Drop useless internal stream conversions

---

tsconfig.common.json
tsconfig.publish.json
tsconfig.publish.types.json

👷 Enable sourceMap in unpublished for coverage

---

.yarn/versions/aae163da.yml
packages/fast-check/src/check/runner/Runner.ts
packages/fast-check/src/check/runner/Sampler.ts
packages/fast-check/src/check/runner/SourceValuesIterator.ts
packages/fast-check/src/check/runner/Tosser.ts
packages/fast-check/test/unit/check/runner/SourceValuesIterator.spec.ts
packages/fast-check/test/unit/check/runner/Tosser.spec.ts

...instead of producing generators that will be called to produce the values.

⚡️ Tosser must immediately produce values

---

.yarn/versions/1f0ff650.yml

📝 Error in the release type being declared

---

.yarn/versions/5ad0dbaf.yml
packages/fast-check/src/check/property/SkipAfterProperty.ts
packages/fast-check/src/check/runner/DecorateProperty.ts
packages/fast-check/test/unit/check/property/SkipAfterProperty.spec.ts

🐛 Resist to fake timers in interruptAfterTimeLimit

---

.yarn/versions/e6cc67a3.yml
packages/fast-check/src/check/property/TimeoutProperty.ts
packages/fast-check/src/check/runner/DecorateProperty.ts
packages/fast-check/test/unit/check/property/TimeoutProperty.spec.ts

🐛 Resist to fake timers in timeout

---

packages/fast-check/CHANGELOG.md

🔖 Update CHANGELOG.md for fast-check@3.5.1

---

packages/vitest/CHANGELOG.md

📝(vitest) Format CHANGELOG.md of vitest

---

.github/workflows/build-status.yml

👷 Do not run publish workflow of fast-check for vitest

---

.github/workflows/build-status.yml
.yarn/versions/58228535.yml
packages/vitest/jest.config.cjs
packages/vitest/package.json
packages/vitest/test/vitest-fast-check.spec.ts
yarn.lock

✅(vitest) Add basic units on vitest

---

.yarn/versions/68fc4d22.yml
packages/fast-check/jest.config.cjs
packages/jest/jest.config.cjs
packages/packaged/jest.config.cjs
packages/poisoning/jest.config.cjs
packages/vitest/jest.config.cjs
packages/worker/jest.config.cjs

🔧 Update ts-jest configuration files

---

examples/package.json
yarn.lock

⬆️ Bump pure-rand in examples

---

.yarn/versions/70cbda0f.yml
packages/fast-check/package.json

📝 Add fuzz keywords

---

.github/workflows/build-status.yml

🔧 Move back to github-pages-deploy-action

---

.yarn/versions/d0ed9a6e.yml
website/docusaurus.config.js

📝 Add search capability to the doc

---

.yarn/versions/eaeab6e7.yml
website/docusaurus.config.js

🔧 Add gtag for analytics

---

.yarn/versions/e41015ec.yml
packages/fast-check/documentation/Arbitraries.md

📝 Fix broken links to api-reference

---

website/docusaurus.config.js

🔧 Update `baseUrl` on the ain documentation

---

packages/fast-check/README.md
packages/fast-check/documentation/Arbitraries.md
packages/fast-check/documentation/Runners.md
website/docs/configuration/global-settings.md
website/docs/core-blocks/arbitraries/combiners/any.md
website/docs/core-blocks/arbitraries/combiners/constant.md
website/docs/core-blocks/arbitraries/combiners/recursive-structure.md
website/docs/core-blocks/arbitraries/combiners/string.md
website/docs/core-blocks/arbitraries/composites/array.md
website/docs/core-blocks/arbitraries/composites/function.md
website/docs/core-blocks/arbitraries/composites/iterable.md
website/docs/core-blocks/arbitraries/composites/object.md
website/docs/core-blocks/arbitraries/composites/typed-array.md
website/docs/core-blocks/arbitraries/fake-data/file.md
website/docs/core-blocks/arbitraries/fake-data/identifier.md
website/docs/core-blocks/arbitraries/fake-data/internet.md
website/docs/core-blocks/arbitraries/others.md
website/docs/core-blocks/arbitraries/primitives/bigint.md
website/docs/core-blocks/arbitraries/primitives/boolean.md
website/docs/core-blocks/arbitraries/primitives/char.md
website/docs/core-blocks/arbitraries/primitives/date.md
website/docs/core-blocks/arbitraries/primitives/number.md
website/docs/core-blocks/arbitraries/primitives/string.md
website/docs/core-blocks/runners.md
website/docusaurus.config.js

📝 Update all links to target fast-check.dev

---

website/docusaurus.config.js
website/src/components/HomepageFeatures/index.js
website/src/components/HomepageFeatures/styles.module.css
website/src/pages/index.js
website/src/pages/index.module.css

Following report: https://pagespeed.web.dev/analysis/https-fast-check-dev/r0wjpxp602?hl=fr&form_factor=mobile

📝 Quick a11y pass on the documentation

---

.github/workflows/build-status.yml

🔧 Drop the need for a branch on doc

---

website/docs/core-blocks/arbitraries/fake-data/internet.md
website/docs/core-blocks/arbitraries/others.md

📝 Fix broken links in new doc 

---

.github/workflows/build-status.yml
.yarn/versions/a937d2f7.yml

More details at: https://docs.npmjs.com/generating-provenance-statements

🔒️ Attach provenance to the packages

---

.github/workflows/build-status.yml

🔧 Do not relaunch build on new tag

---

website/docs/advanced/_category_.json
website/docs/advanced/fake-data.md
website/docs/advanced/fuzzing.md
website/docs/advanced/model-based-testing.md
website/docs/advanced/race-conditions.md
website/docs/tutorials/_category_.json
website/docusaurus.config.js

📝 Add "advanced" part of the documentation

---

.devcontainer/Dockerfile
website/.gitattributes
website/docusaurus.config.js
website/static/img/social.png

🍱 New social card for the website

---

.github/workflows/build-status.yml

🔧 Build documentation with LFS enabled

---

website/docs/introduction/why-property-based.md
website/docs/tutorials/quick-start/our-first-property-based-test.md

📝 Fix typos in docs

---

website/docs/tutorials/detect-race-conditions/introduction.md

📝 Rework intro of race condition tutorial

---

website/docs/tutorials/detect-race-conditions/_category_.json
website/docs/tutorials/detect-race-conditions/index.md
website/docs/tutorials/detect-race-conditions/multiple-batches-of-calls.mdx
website/docs/tutorials/detect-race-conditions/one-step-closer-to-real-usages.mdx
website/docs/tutorials/detect-race-conditions/the-missing-part.mdx
website/docs/tutorials/detect-race-conditions/wrapping-up.mdx
website/docs/tutorials/detect-race-conditions/your-first-race-condition-test.mdx

📝 Merge category and intro for race condition

---

website/docs/tutorials/detect-race-conditions/index.md
website/docusaurus.config.js

📝 Note about solving race conditions

---

website/docs/ecosystem.md

📝 Points to projects in our ecosystem

---

website/src/components/HomepageHeader/index.js

💄 Properly display the quick nav buttons

---

.yarn/versions/d638c028.yml
CONTRIBUTING.md
packages/fast-check/README.md

📝 Update all links to new documentation

---

.yarn/versions/41b40135.yml
packages/worker/README.md

📝(worker) Add worker logo url

---

.yarn/versions/08d3868e.yml
packages/vitest/README.md

📝(vitest) Update logo url

---

.yarn/versions/63014794.yml
packages/ava/README.md

📝(ava) Update logo url

---

.yarn/versions/95ee8c6e.yml
packages/ava/README.md
packages/fast-check/README.md
packages/jest/README.md
packages/vitest/README.md
packages/worker/README.md

📝 Reference image from LFS in README

---

.yarn/versions/38b7b42c.yml
packages/poisoning/README.md

📝(poisoning) Add poisoning logo url

---

website/blog/2023-05-21-whats-new-in-fast-check-3-9-0/index.md
website/docs/advanced/race-conditions.md

📝 Release note page for 3.9.0

---

website/docs/tutorials/detect-race-conditions/snippets.mjs
website/docs/tutorials/detect-race-conditions/snippets.spec.mjs

✅ Rework race conditions specs in tutorial

---

website/blog/2023-05-21-whats-new-in-fast-check-3-9-0/index.md

📝 Fix typo in What's new 3.9.0

---

.yarn/versions/0725513f.yml
packages/fast-check/src/arbitrary/_internals/helpers/ReadRegex.ts
packages/fast-check/src/arbitrary/_internals/helpers/TokenizeRegex.ts
packages/fast-check/src/arbitrary/stringMatching.ts
packages/fast-check/test/unit/arbitrary/_internals/helpers/ReadRegex.spec.ts
packages/fast-check/test/unit/arbitrary/_internals/helpers/TokenizeRegex.spec.ts

✨ Add support for capturing regexes

---

packages/fast-check/src/arbitrary/_internals/helpers/TokenizeRegex.ts
packages/fast-check/src/arbitrary/stringMatching.ts
packages/fast-check/test/unit/arbitrary/_internals/helpers/TokenizeRegex.spec.ts

✨ Support empty disjunctions in regexes

---

packages/fast-check/test/unit/arbitrary/stringMatching.spec.ts
website/docs/core-blocks/arbitraries/combiners/string.md

✅ Add some more known regexes in our test suite

---

.yarn/versions/6de571cd.yml
packages/worker/README.md
packages/worker/src/internals/MainThreadRunner.ts
packages/worker/src/internals/worker-pool/OneTimePool.ts
packages/worker/src/main.ts
packages/worker/test/main.properties.cjs
packages/worker/test/main.spec.ts

✨(worker) Introduce levels of isolation

---

.github/workflows/scorecard.yml

👷 Add scorecard security workflow

---

.yarn/versions/9584fe6f.yml
packages/fast-check/README.md

📝 Add some OpenSSF badges

---

website/blog/2023-06-07-whats-new-in-fast-check-3-11-0/index.md

📝 Prepare release note for 3.11.0

---

.github/workflows/scripts/generate-changelog.cjs

🔨 Add support for more gitmojis

---

.github/workflows/build-status.yml

👷 Ensure we use latest node in range

---

.devcontainer/devcontainer.json

🔧 Update devcontainer configuration

---

.github/renovate.json

👷 Disable nodenv bumps on renovate

---

.all-contributorsrc
.yarn/versions/0e1376d0.yml
packages/fast-check/README.md

👥 Add new contributor zbjornson

---

.yarn/versions/d7649f72.yml
packages/fast-check/src/arbitrary/_internals/mappers/UintToBase32String.ts
packages/fast-check/test/unit/arbitrary/_internals/mappers/UintToBase32String.spec.ts

⚡️ Faster generation of `ulid`

---

.yarn/versions/8f3deb8b.yml
packages/fast-check/src/arbitrary/_internals/mappers/UintToBase32String.ts
packages/fast-check/test/e2e/Poisoning.spec.ts
packages/fast-check/test/unit/arbitrary/ulid.spec.ts

🐛 Be resilient to poisoning with `ulid`

---

.prettierignore

🔧 Stop formatting built website

---

.devcontainer/devcontainer.json

🔧 Update Devcontainer settings

---

.yarn/versions/38f141a1.yml
packages/ava/package.json

🏷️(ava) Better declare ESM's types

---

.yarn/versions/2365e721.yml
packages/worker/package.json

🏷️(worker) Better declare ESM's types

---

.yarn/versions/3e90c5b4.yml
packages/fast-check/package.json

🏷️ Better declare ESM's types

---

website/blog/2023-09-04-dual-packages-or-supporting-both-cjs-and-esm/index.md

📝 Document our approach to dual package

---

website/docusaurus.config.js
website/manifest.json
website/package.json
yarn.lock

📝 Expose website as PWA too

---

.github/workflows/build-status.yml

✅ Drop Node 14.x from the test-chain

---

.yarn/versions/1513e567.yml
packages/jest/src/jest-fast-check.ts

🗑️(jest) Flag `{it,test}Prop` as deprecated

---

.yarn/versions/f65646a5.yml
packages/fast-check/src/arbitrary/record.ts

🗑️ Deprecate `withDeletedKeys` on `record`

---

.yarn/versions/7430031d.yml
packages/fast-check/src/arbitrary/_internals/mappers/KeyValuePairsToObject.ts

🐛 Better poisoning resiliency for `dictionary`

---

packages/fast-check/test/unit/arbitrary/date.spec.ts

💚 Rework broken test on `date`

---

packages/fast-check/test/unit/arbitrary/_internals/mappers/TimeToDate.spec.ts

💚 Rework another broken test on date

---

website/blog/2023-09-17-whats-new-in-fast-check-3-13-0/index.md

📝 Release note for 3.13.0

---

website/blog/2023-09-21-detect-prototype-pollution-automatically/index.md

📝 Some tips on prototype pollution

---

website/blog/2023-09-21-detect-prototype-pollution-automatically/index.md

📝 Fix typo in "Detect prototype pollution automatically"

---

.yarn/versions/4e8735e8.yml
packages/vitest/src/vitest-fast-check.ts

🐛(vitest) Fix typings for node native esm

---

packages/vitest/test-types/main.ts

✅(vitest) Confirm typings work well

---

.yarn/versions/fbd92e9d.yml
packages/ava/test-types/main.ts

✅(ava) Confirm basic typings work well

---

.yarn/versions/f6e7489b.yml
packages/expect-type/test-types/main.ts

✅(expect-type) Confirm basic typings work well

---

.yarn/versions/2ece6823.yml
packages/packaged/test-types/main.ts

✅(packaged) Confirm basic typings work well

---

.yarn/versions/c3e534ed.yml
packages/poisoning/test-types/main.ts

✅(poisoning) Confirm basic typings work well

---

.yarn/versions/c223f19c.yml
packages/worker/test-types/main.ts

✅(worker) Confirm basic typings work well

---

.yarn/versions/a9c1de2c.yml
packages/vitest/test-types/main.ts

💚(vitest) Fix broken typing checks in CI

---

.yarn/versions/2cf26c53.yml
packages/jest/test-types/main.ts

✅(jest) Confirm basic typings work well

---

website/static/robots.txt

🔍️ Add missing robots.txt

---

.github/workflows/build-status.yml

👷 Better yarn caching in CI

---

.github/workflows/build-status.yml

👷 Create job to confirm all passed

---

.yarn/versions/b172fa28.yml
packages/packaged/src/packaged.ts

⚡(packaged) Faster directory traversal

---

.yarn/versions/c2440f6f.yml
packages/fast-check/src/arbitrary/gen.ts
website/docs/core-blocks/arbitraries/others.md

📝 Better document limitations of `gen`

---

.github/workflows/build-status.yml

👷 Toggle more immutable on yarn

---

package.json

Up-to-now we were doing so from time to time. It's 1. fully useless 2. potential source of issues.

👷 Do not override existing on untar

---

package.json

Reverts dubzzz/fast-check#4369

👷 REVERT Do not override existing on untar

---

package.json

Second attempt, same philosophy for now.

💚 Attempt to patch untar step

---

.codesandbox/ci.json
.github/workflows/build-status.yml

👷 Default to Node 20 for CI

---

.yarn/versions/43c7daff.yml
packages/jest/test-bundle/jest.config.cjs
packages/jest/test-bundle/jest.config.mjs

💚(jest) Stabilize CI with higher timeout for test-bundle tests

---

website/blog/2023-11-22-whats-new-in-fast-check-3-14-0/index.md

📝 Blog post for 3.14.0

---

.yarn/versions/2dbe017d.yml
packages/fast-check/test/e2e/NoRegression.spec.ts
packages/fast-check/test/e2e/__snapshots__/NoRegression.spec.ts.snap
packages/fast-check/test/e2e/__test-helpers__/StackSanitizer.ts

✅ Wrap async no-regression snapshots within a sanitizer for stacktraces

---

.yarn/versions/d27914ad.yml
website/docs/core-blocks/arbitraries/primitives/date.md

fix typo in the doco for date arbitraries at https://fast-check.dev/docs/core-blocks/arbitraries/primitives/date/

📝 fix typo in date.md

---

.all-contributorsrc
packages/fast-check/README.md

👥 Add new contributor bennettp123

---

packages/ava/package.json
yarn.lock

No breakage expected: v6 is the last, no risk to have v7 on the wild before I release this fix.

🐛(ava) Stricter (peer) range definition for ava

---

.yarn/versions/32bfbc6a.yml
packages/vitest/package.json
yarn.lock

🐛(vitest) Stricter (peer) range definition for vitest

---

.yarn/versions/aacb5134.yml
packages/ava/src/ava-fast-check.ts

🐛(ava) Add support for `pre` on AVA v6

---

.yarn/versions/7dbac1db.yml
packages/fast-check/src/arbitrary/dictionary.ts
website/docs/core-blocks/arbitraries/composites/object.md

✨ Add support for `depthIdentifier` to `dictionary`

---

.yarn/versions/de08319f.yml
packages/fast-check/src/arbitrary/_internals/builders/AnyArbitraryBuilder.ts
packages/fast-check/src/arbitrary/dictionary.ts

♻️ Rely on `dictionary` for `object` instead of inlined reimplementation

---

.yarn/versions/b22148a6.yml
packages/poisoning/README.md
packages/poisoning/package.cjs-template.json
packages/poisoning/package.esm-template.json
packages/poisoning/package.json

The build chain of `@fast-check/poisoning` has been CommonJS-based since day 1. With ESM moving forward in the ecosystem, it's time to move ourselves to the new standard and adapt our build chains to ESM.
Another subtle impact is that it would impose our users to run at least Node ≥12.17.0.
As such we consider it as a breaking change.

👷(poisoning) Move build chain to ESM

---

package.json

Moving the root of the monorepo to ESM.
This part not being published at all, we don't expect any impacts to our users and can safely flag it as no-op from a versionning point of view.

👷 Move build chain to ESM

---

.yarn/versions/e057419f.yml
packages/packaged/babel.config.cjs
packages/packaged/jest.config.js
packages/packaged/package.json
packages/packaged/test/packaged.spec.ts
yarn.lock

🔧(packaged) Migrate jest to esm

---

.yarn/versions/ea1bb510.yml
packages/poisoning/babel.config.cjs
packages/poisoning/jest.config.cjs
packages/poisoning/jest.config.js
packages/poisoning/package.json
packages/poisoning/test/main.spec.ts
yarn.lock

🔧(poisoning) Migrate jest to esm

---

.gitignore
.vscode/extensions.json
.vscode/settings.json
.yarn/sdks/eslint/package.json
.yarn/sdks/prettier/package.json
.yarn/sdks/typescript/package.json

🔧 Configuration files for VSCode

---

examples/001-simple/sort/main.spec.ts
examples/002-recursive/isSearchTree/main.spec.ts
examples/003-misc/mazeGenerator/main.spec.ts
examples/005-race/autocomplete/main.spec.tsx
examples/005-race/debounced-autocomplete/main.spec.tsx
examples/005-race/supertest/app.spec.ts
examples/005-race/todolist/model-based/AddItemCommand.ts
examples/005-race/userProfile/main.spec.tsx
examples/babel.config.cjs
examples/jest.config.js
examples/jest.setup.js
examples/package.json
yarn.lock

👷 Move examples build chain to ESM

---

packages/fast-check/test/e2e/arbitraries/WebArbitrary.spec.ts

✅ Stabilize flaky URL-related test

---

website/docs/ecosystem.md

📝 Add `@effect/schema` in ecosystem

---

website/docs/introduction/track-record.md

📝 Add `jsonwebtoken` to track record

---

website/docusaurus.config.ts

In an attempt to unroll fast-check.dev into https://www.netlify.com/legal/open-source-policy/, I'm adding a backlink leading to Netlify.

📝 Add link to Netlify

---

.github/workflows/build-status.yml

🔧 Drop configuration of GitHub Pages

---

.github/workflows/build-status.yml

🔒️ Configure CSP for fast-check.dev

---

.github/workflows/build-status.yml
website/blog/authors.yml
website/prebuild/optimize-images.mjs

🔒️ Enforce Content-Security-Policy on our website

---

website/blog/2024-03-01-whats-new-in-fast-check-3-15-0/index.md

📝 Blog post for 3.15.0

---

.github/workflows/build-status.yml

🔒️ Relax CSP policy to support Algolia

---

website/docusaurus.config.ts

📝 Add more links in the footer

---

website/src/components/HomepageQuotes/styles.module.css
website/src/css/custom.css

💄 Better colors for footer and dark mode

---

website/blog/2024-03-26-whats-new-in-fast-check-3-17-0/index.md
website/blog/2024-03-26-whats-new-in-fast-check-3-17-0/worker-parent-gen.png
website/blog/2024-03-26-whats-new-in-fast-check-3-17-0/worker-worker-gen.png

📝 Release note for 3.17.0

---

packages/worker/test/e2e/__properties__/nonSerializableButSameData.cjs
packages/worker/test/e2e/nonSerializableButSameData.spec.ts

💚(worker) Stabilize tests on worker

---

.all-contributorsrc
.yarn/versions/fda76d8e.yml
packages/fast-check/README.md

👥 Add new contributor patroza

---

website/docusaurus.config.ts
website/src/components/HomepageFeatures/index.js
website/src/components/HomepageHeader/index.js
website/src/pages/index.js

📝 Enhance SEO for homepage

---

.github/workflows/build-status.yml

👷 Stop caching Jest on CI

---

.yarn/versions/632bba5e.yml
packages/fast-check/src/arbitrary/_internals/helpers/DoubleOnlyHelpers.ts
packages/fast-check/test/unit/arbitrary/__test-helpers__/FloatingPointHelpers.ts
packages/fast-check/test/unit/arbitrary/double.spec.ts

✅ Cover `noInteger` on `double` via integration layers

---

tsconfig.common.json

Based on suggestions from https://www.totaltypescript.com/tsconfig-cheat-sheet

🔧 Enable more advanced TS flags

---

.yarn/versions/36811c13.yml
eslint.config.mjs
packages/fast-check/src/check/model/commands/ScheduledCommand.ts
packages/fast-check/src/check/runner/Runner.ts
packages/fast-check/src/utils/stringify.ts
packages/fast-check/test-types/main.ts
packages/vitest/src/internals/TestBuilder.ts
packages/vitest/src/internals/TestWithPropRunnerBuilder.ts
packages/worker/src/internals/worker-pool/GlobalPool.ts

🔨 Switch on more eslint rules

---

website/blog/2024-04-28-whats-new-in-fast-check-3-18-0/index.md

📝 Publish release note for 3.18.0

---

.github/PULL_REQUEST_TEMPLATE.md

Inspired from Vitest's template.

🔧 Rework issue template

---

.yarn/versions/a0484bf6.yml
packages/jest/package.json
yarn.lock

⬆️(jest) Relax version constraint to allow 0.4.x of worker

---

package.json

Just dropping verbosity for less logs and possibly a slightly faster execution.
**Advanced**

👷 Drop verbosity flag at unpack step in CI

---

website/blog/2024-05-23-whats-new-in-fast-check-3-19-0/index.md

Release note for 3.19.0.
**Advanced**

📝 Release note for 3.19.0

---

.github/PULL_REQUEST_TEMPLATE.md

Fixing a typo in the template for PRs.
**Advanced**

📝 Fix typo in the PR template

---

website/docs/tutorials/detect-race-conditions/your-first-race-condition-test.mdx

📝 Remove duplicate paragraph in `your-first-race-condition-test.mdx`

---

.all-contributorsrc
.yarn/versions/62db1e8a.yml
packages/fast-check/README.md

Adding new contributors!
**Advanced**

👥 Add new contributors cindywu and nmay231

---

website/blog/2024-07-12-whats-new-in-fast-check-3-20-0/index.md

Just a release note.
The main reason to push this release has been to make sure users of Vitest will not be blocked by our connector to Vitest. As such we published both `@fast-check/vitest` and `fast-check`. In order to push the new release of `fast-check` we just made sure to have everything packed for a small minor, then we created the release and tada!
**Advanced**

📝 Publish release note for 3.20.0

---

website/docs/core-blocks/arbitraries/primitives/number.md

The documentation was missing some attributes. This PR makes sure we have them properly displayed in the documentation.
**Advanced**

📝 Add missing options in the documentation for `float` and `double`

---

website/src/components/HomepageHeader/index.js

Fixing a wrong sizing for a badge.
**Advanced**

📝 Better width for stargazer badge in the documentation

---

website/blog/2024-07-18-integrating-faker-with-fast-check/index.md
website/blog/2024-07-18-integrating-faker-with-fast-check/social.png
website/docs/advanced/fake-data.md

📝 Document Faker integration

---

website/docs/support-us.md
website/docusaurus.config.ts

📝 Add support us page in our documentation

---

packages/jest/babel.config.cjs
packages/jest/jest.config.js
packages/jest/package.json
packages/jest/test/jest-fast-check.spec.ts
yarn.lock

**Description** first opened as #4605
Updating test chain to esm.
**Advanced**

🔧(jest) Migrate jest to esm

---

.yarn/versions/4e97eaaf.yml
packages/fast-check/src/arbitrary/uuidV.ts
website/docs/core-blocks/arbitraries/fake-data/identifier.md

Deprecating `uuidV` in favor of `uuid`. No need to have both now that `uuid` also offers ways to customize the generated versions (see #5188).
**Advanced**

🗑️ Deprecate `uuidV` in favor of `uuid`

---

website/blog/2024-08-10-whats-new-in-fast-check-3-21-0/index.md

Release note, nothing more!
**Advanced**

📝 Publish release note for 3.21.0

---

.yarn/versions/59366db4.yml
packages/jest/src/internals/TestBuilder.ts

In order to toggle ON the flag `isolatedDeclarations` and allow us to use something else than tsc to build our project (not sure we will do one day), we start to make some types more explicit on our exported symbols.
**Advanced**

♻️(jest) Add missing types on exported

---

.yarn/versions/66578bf1.yml
packages/poisoning/src/internals/PoisoningFreeArray.ts
packages/poisoning/src/internals/PoisoningFreeMap.ts
packages/poisoning/src/internals/PoisoningFreeSet.ts

In order to toggle ON the flag `isolatedDeclarations` and allow us to use something else than tsc to build our project (not sure we will do one day), we start to make some types more explicit on our exported symbols.
**Advanced**

♻️(poisoning) Add missing types on exported

---

packages/fast-check/src/arbitrary/mixedCase.ts

While not being really expensive to compute it's yet another check and dropping it could be useful if we want to go faster. Indeed with `BigInt` being a thing in Node since 10.5.0, we probably don't want to pay for checking it all the time.
We will probably have to bump our minimal requirement to 10.5.0+ for the version 4 of fast-check so that we can expect it to always be a thing no matter the runtime being used as long as it fits our requirements.
**Advanced**

⚡️ Drop unneeded `BigInt` check in `mixedCase`

---

packages/fast-check/package.json
packages/fast-check/src/utils/globals.ts

In the past we used to checks for `typeof Type` when initializing our globals (the globals protecting fast-check from poisoning). It used to be done because some of them only appeared starting at Node >8. With our minimal target version being bumped to at least 10.5.0 we can safely stop having these checks and save some precious time during tests (for our users).
This change forces us to move minimal requirements to at least 10.5.0.
**Advanced**

⚡️ Faster initialization of globals by dropping `typeof` checks

---

.github/workflows/build-status.yml

The RC release channel of TypeScript has been used for quite some time in our CI. It ensured fast-check never break on new release of TypeScript.
Unfortunately, new releases of TypeScript needs to wait some patches on yarn side before being compatible. In order not to block the project while yarn's team is working on a fix, we drop it from the CI.
More information at: https://github.com/yarnpkg/berry/pull/6461
**Advanced**

👷 Drop TypeScript rc release channel

---

website/docs/core-blocks/arbitraries/combiners/string.md
website/docs/core-blocks/arbitraries/primitives/char.md
website/docs/core-blocks/arbitraries/primitives/string.md

Our documentation was forcing users to open the associated deprecation Pull Request in order to read for the recommended alternates to the deprecated helpers.
This PR makes sure we just link to `string` when it is the recommended replacement.
**Advanced**

📝 Better `string`'s deprecation note in documentation

---

website/blog/2024-08-29-whats-new-in-fast-check-3-22-0/index.md
website/blog/2024-08-29-whats-new-in-fast-check-3-22-0/printable-ascii.png

Just a release note!
**Advanced**

📝 Release note for fast-check 3.22.0

---

packages/fast-check/src/arbitrary/string.ts
packages/fast-check/src/arbitrary/webUrl.ts
packages/fast-check/src/check/arbitrary/definition/Arbitrary.ts
packages/fast-check/src/check/runner/Runner.ts

As we dropped support for versions of Node not supporting object spreading we can now use it barely everywhere needed.
Fix #5299
**Advanced**

♻️ Switch to object spreading rather than `Object.assign`

---

packages/fast-check/src/arbitrary/json.ts

The `json` arbitrary used to be skipped by our Poisoning-resilience checks as it was depending on a set of helpers that was not that resilient to it.
Following deep refactorings and changes of the helpers backing it we can now check it. While doing so we found it was not that resilent as it was not capable of keeping working properly after a destructive change of `JSON.stringify`. As such we fixed it.
**Advanced**

🐛 Resist to external poisoning for `json`

---

packages/fast-check/test/unit/utils/stringify.spec.ts

💚 Adapt some tests for Node v23

---

packages/jest/test/jest-fast-check.spec.ts
packages/vitest/test/vitest-fast-check.spec.ts
website/docs/tutorials/detect-race-conditions/snippets.spec.mjs

💚 Drop usages of `it.concurrent` due to Node 23 failing

---

.changeset/hot-weeks-divide.md
packages/worker/babel.config.cjs
packages/worker/package.json
yarn.lock

Follow-up of #5347.
We forgot to drop some unneeded development dependencies from the definition of the package after the move to Vitest.
**Advanced**

👷(worker) Drop unneeded devDependencies

---

.changeset/afraid-forks-press.md
packages/vitest/babel.config.cjs
packages/vitest/jest.config.js

Follow-up of #5350.
We forgot to drop some unneeded configuration files when moving to Vitest.
**Advanced**

👷(vitest) Drop unneeded configuration files

---

.changeset/green-owls-tap.md
packages/poisoning/babel.config.cjs
packages/poisoning/jest.config.js
packages/poisoning/package.json
packages/poisoning/test/internals/CaptureAllGlobals.spec.ts
packages/poisoning/test/internals/FilterNonEligibleDiffs.spec.ts
packages/poisoning/test/internals/PoisoningFreeArray.spec.ts
packages/poisoning/test/internals/PoisoningFreeMap.spec.ts
packages/poisoning/test/internals/PoisoningFreeSet.spec.ts
packages/poisoning/test/internals/TrackDiffsOnGlobal.spec.ts
packages/poisoning/test/main.spec.ts
yarn.lock

Change our test runner to Vitest.
Jest is great but it's partial support for ESM is putting us in troubles. As such we passed fast-check to Vitest a while ago and want to unify all others so that we preserve a unique test runner in our CI.
**Advanced**

👷(poisoning) Move to Vitest

---

examples/001-simple/decompPrime/main.spec.ts
examples/001-simple/fibonacci/main.spec.ts
examples/001-simple/indexOf/main.spec.ts
examples/001-simple/sort/main.spec.ts
examples/002-recursive/isSearchTree/main.spec.ts
examples/003-misc/knight/main.spec.ts
examples/003-misc/mazeGenerator/main.spec.ts
examples/003-misc/roman/main.spec.ts
examples/004-stateMachine/musicPlayer/main.spec.ts
examples/005-race/autocomplete/main.spec.tsx
examples/005-race/counter/main.spec.ts
examples/005-race/debounced-autocomplete/main.spec.tsx
examples/005-race/dependencyTree/main.spec.ts
examples/005-race/supertest/app.spec.ts
examples/005-race/todolist/main.spec.tsx
examples/005-race/todolist/model-based/AddItemCommand.ts
examples/005-race/todolist/model-based/RemoveItemCommand.ts
examples/005-race/todolist/model-based/ToggleItemCommand.ts
examples/005-race/userProfile/main.spec.tsx
examples/babel.config.cjs
examples/jest.config.js
examples/package.json
examples/vitest.config.ts
examples/vitest.setup.ts
yarn.lock

We are moving all our packages to Vitest. As such `examples/` have to be migrated to it too.
**Advanced**

👷 Move to Vitest for `examples/`

---

.changeset/tender-mails-repeat.md
packages/jest/.gitignore
packages/jest/babel.config.cjs
packages/jest/jest.config.js
packages/jest/package.json
packages/jest/test/jest-fast-check.spec.ts
packages/jest/vitest.config.ts
yarn.lock

Change our test runner to Vitest.
Jest is great but it's partial support for ESM is putting us in troubles. As such we passed fast-check to Vitest a while ago and want to unify all others so that we preserve a unique test runner in our CI.
**Advanced**

👷(jest) Move to Vitest

---

website/docs/advanced/model-based-testing.md

This is just a small typo fix in one of the documentation pages.
Thanks for maintaining this library!

 📝 Typo fix in model-based-testing.md

---

packages/fast-check/test/unit/arbitrary/_internals/ConstantArbitrary.spec.ts

These new tests will make sure that we never break things around `-0` and `0` unwantingly if we want to make `canShrinkWithoutContext` more performant.
**Advanced**

✅ Add extra set of tests for `constant*`

---

.all-contributorsrc
packages/fast-check/README.md

Add new contributor jamesbvaughan.
**Advanced**

👥 Add new contributor jamesbvaughan

---

packages/vitest/test/vitest-fast-check.spec.ts

Tests used to be scoped via their configuration file. Starting at this PR, they will be scoped via dedicated directories.
It would avoid having Jest to scan all files of the directory including some not relevant for the test itself. With new scoping the directory being passed will be only for this test, not for others. As such Jest can scan all of it.
**Advanced**

✅(vitest) Better scoping of tests execution

---

website/docs/tutorials/detect-race-conditions/snippets.mjs

Our documentation references live coding code sections. These sections offer users ways to test fast-check from their own browser.
At the moment, the code in these sections was un-properly indented with an extra 2-space-gap at the beginning of each line of code. This PR just drops this extra spacing.
**Advanced**

📝 Properly indent code snippets for the documentation

---

.github/workflows/build-status.yml

Just putting a better DX!
**Advanced**

👷 Connect custom templates to `pkg.pr.new` previews

---

examples/jest.setup.js

Dropping unused file.
**Advanced**

🔥 Drop unused `examples/jest.setup.js`

---

.github/workflows/scripts/generate-changelog.cjs

Fixing our generator for changelogs.
**Advanced**

👷 Install dependencies before building changesets

---

website/blog/2024-08-29-whats-new-in-fast-check-3-22-0/index.md
website/blog/2024-11-05-whats-new-in-fast-check-3-23-0/index.md

📝 Release note for 3.23.0

---

.changeset/long-goats-kiss.md
packages/fast-check/src/arbitrary/_internals/helpers/IsSubarrayOf.ts
packages/fast-check/src/utils/globals.ts

While we may still miss lots of poisoning cases, we try to be closer to a fully poisoning free implementation for `subarray`. In theory it should make tests easier to troubleshoot in case the test failed because of a poisoning it introduced itself.
**Advanced**

🐛 Make `subarray` a bit more resilient to poisoning

---

.changeset/chilled-items-grab.md
packages/fast-check/src/arbitrary/_internals/mappers/IndexToMappedConstant.ts

🐛 Make `mapToConstant` a bit more resilient to poisoning

---

.changeset/quick-pillows-shake.md
packages/fast-check/src/check/runner/utils/RunDetailsFormatter.ts

🐛 Make run details printer a bit more resilient to poisoning

---

.changeset/eight-elephants-change.md
packages/fast-check/src/arbitrary/_internals/GeneratorArbitrary.ts
packages/fast-check/src/arbitrary/_internals/builders/GeneratorValueBuilder.ts
packages/fast-check/src/arbitrary/_internals/builders/StableArbitraryGeneratorCache.ts
packages/fast-check/test/e2e/Poisoning.spec.ts

While we may still miss lots of poisoning cases, we try to be closer to a fully poisoning free implementation for `gen`.
**Advanced**

🐛 Make `gen` a bit more resilient to poisoning

---

.changeset/wise-pears-lay.md
.yarn/versions/56a0e276.yml
packages/fast-check/src/check/property/AsyncProperty.generic.ts
packages/fast-check/src/check/property/IRawProperty.ts
packages/fast-check/src/check/property/IgnoreEqualValuesProperty.ts
packages/fast-check/src/check/property/Property.generic.ts
packages/fast-check/src/check/property/SkipAfterProperty.ts
packages/fast-check/src/check/property/TimeoutProperty.ts
packages/fast-check/src/check/property/UnbiasedProperty.ts
packages/fast-check/src/check/runner/Runner.ts
packages/fast-check/test/unit/check/property/AsyncProperty.spec.ts
packages/fast-check/test/unit/check/property/IgnoreEqualValuesProperty.spec.ts
packages/fast-check/test/unit/check/property/Property.spec.ts
packages/fast-check/test/unit/check/property/SkipAfterProperty.spec.ts
packages/fast-check/test/unit/check/property/TimeoutProperty.spec.ts
packages/fast-check/test/unit/check/property/__test-helpers__/PropertyHelpers.ts
packages/fast-check/test/unit/check/runner/DecorateProperty.spec.ts
packages/fast-check/test/unit/check/runner/Runner.spec.ts
packages/fast-check/test/unit/check/runner/Tosser.spec.ts
packages/worker/src/internals/worker-property/WorkerPropertyFromWorker.ts
packages/worker/test/internals/worker-property/WorkerPropertyFromWorker.spec.ts
website/docs/migration/from-3.x-to-4.x.md

The API of property has been updated in a non-breaking manner during v3. Now, let's seal that move to drop unneeded code complexity, drop useless tests... but also make the API clearer and way simpler to use and manage.
The implementations of `IRawProperty` now have to implement `runBeforeEach` and `runAfterEach`. If they themselves wrap another `IRawProperty`, they probably should at least call these methods when called on their side of them. The migration from v3, consists into implementing the two methods.
**Advanced**
**:boom: Breaking change**: Change the execution flow of properties. Only impacts on advanced users building their own custom runners or their own …

🔥 Enforce `run{Before/After}Each` on property

---

.changeset/shaggy-rice-tell.md
packages/fast-check/src/arbitrary/_internals/implementations/SchedulerImplem.ts

Our initial implementation of `scheduleSequence` used to be reduce-based. It makes it hard to understand at first glance. As such and in attempt to ease our aim to make scheduling faster (see #3891), we are doing a _simple_ rewrite of it.
**Advanced**
**👀 Potentially risky**: While it should be without any impact, playing with Promises is always risky and can easily drop some extra waiting times or add some. As such this PR will probably wait for a dedicated minor or major to be rollout.

♻️ Rewrite of `scheduleSequence`

---

.changeset/shy-bottles-smile.md
packages/fast-check/src/arbitrary/constant.ts
packages/fast-check/test-types/main.ts
packages/fast-check/test/e2e/RecursiveStructures.spec.ts
packages/fast-check/test/unit/arbitrary/webUrl.spec.ts
website/docs/migration/from-3.x-to-4.x.md

As recommended by https://github.com/dubzzz/fast-check/issues/4047, let's leverage const generics to make usage of `constant` even simpler for TS users.
Not really a breaking change on its own but given we play with types and change the way we declare some, let's be safe and pack this change with other "next major" devs.
Requires at least TypeScript 5.0: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-0.html#const-type-parameters.
**Advanced**

🏷️ Better typings for `constant`

---

packages/fast-check/test/unit/arbitrary/_internals/implementations/SchedulerImplem.spec.ts

Making tests around scheduler safer.
**Advanced**

💚 Clean unhandled rejections in tests for scheduler

---

.changeset/odd-gifts-end.md
packages/vitest/package.json
yarn.lock

Just marking v3 of Vitest as officially supported!
**Advanced**

🔧(vitest) Flag vitest v3 as supported

---

.github/workflows/build-status.yml
website/prebuild/optimize-images.mjs

🔧 Move CI jobs to Node 22

---

pnpm-lock.yaml
website/docusaurus.config.ts
website/package.json

Since Docusaurus 3.6.0, it is doable to toggle ON faster builds (more details: [here](https://docusaurus.io/blog/releases/3.6#docusaurus-faster)). We just toggle on the faster builds capabilities.
**Advanced**

👷 Toggle ON faster documentation build

---

pnpm-lock.yaml
website/vitest.config.ts

Our initial setup of tests on website/ was not filtering out common useless directories. It drove Vitest into excessive scan of files.
**Advanced**

✅ Do not scan useless directories for tests on website

---

pnpm-lock.yaml

💚 Fix lock file breakeage

---

.changeset/some-terms-film.md
packages/fast-check/test/unit/arbitrary/double.spec.ts

✅ Fix test in double.spec

---

.changeset/shiny-panthers-nail.md
eslint.config.mjs
packages/fast-check/src/arbitrary/_internals/helpers/JsonConstraintsBuilder.ts
packages/fast-check/src/arbitrary/falsy.ts
packages/fast-check/src/arbitrary/record.ts
packages/fast-check/src/check/model/command/AsyncCommand.ts
packages/fast-check/src/check/model/command/Command.ts
packages/fast-check/src/check/property/AsyncProperty.generic.ts
packages/fast-check/src/check/property/Property.generic.ts

It's all about the rule: https://typescript-eslint.io/rules/no-empty-object-type/.
Related to #5282
**Advanced**

🚨 Abide by lint rule `no-empty-object-type`

---

.changeset/large-shoes-divide.md
packages/vitest/src/internals/TestBuilder.ts

We used to rely on the typing of an intermediate variable to declare the typings of `FastCheckItBuilder`. We dropped it to drop some unwanted usages of the directive: `eslint-disable-next-line @typescript-eslint/no-unused-vars`.
Related to #5282.
**Advanced**

🏷️(vitest) No intermediate var to declare our types

---

.changeset/chatty-panthers-brake.md
packages/fast-check/src/arbitrary/string.ts
website/docs/core-blocks/arbitraries/primitives/string.md

📝 Document the Unicode version

---

.github/workflows/build-status.yml

Fixes #5152
The only few remaining occurrences would requires us to wait as we still want to run the CI against older versions of node on these remaining cases
**Advanced**

👷 Switch CI commands to `node --run`

---

.github/workflows/build-status.yml

✅ Check TypeScript 5.7 to assess it never breaks

---

.changeset/bitter-grapes-pull.md
packages/fast-check/src/arbitrary/_internals/ConstantArbitrary.ts
packages/fast-check/src/arbitrary/_internals/helpers/BiasNumericRange.ts
packages/fast-check/src/check/model/commands/ScheduledCommand.ts
packages/worker/src/internals/MainThreadRunner.ts

This PR fixes the linting error that was backed out of #5783

🚨 Fix lint error in `ConstantArbitrary` class

---

.changeset/healthy-moose-work.md
packages/expect-type/tsconfig.json

🔧(expect-type) Update tsconfig to ES2020

---

.changeset/wicked-goats-bake.md
packages/packaged/tsconfig.json
packages/packaged/tsconfig.publish.json
packages/packaged/tsconfig.publish.types.json

No visible impact expected given we officially only support node ≥16.14.0. The main noticeable impact if any would be performance wise.
Confirmed by checking manually the build artifacts: no change in the produced bundle!
**Advanced**

🔧(packaged) Update tsconfig to ES2020

---

.changeset/brave-llamas-crash.md
packages/poisoning/tsconfig.json
packages/poisoning/tsconfig.publish.json
packages/poisoning/tsconfig.publish.types.json

No visible impact expected given we officially only support node ≥12.17.0. The main noticeable impact if any would be performance wise.
Confirmed by checking manually the build artifacts: no change in the produced bundle!
**Advanced**

🔧(poisoning) Update tsconfig to ES2020

---

.changeset/thirty-garlics-press.md
packages/worker/tsconfig.json
packages/worker/tsconfig.publish.json
packages/worker/tsconfig.publish.types.json

No impact as the main difference between our legacy common configuration (used by worker before that PR) and the one we leverage now is the target being ES2020. This target was already enforced in the worker package.
**Advanced**

🔧(worker) Update tsconfig to common config

---

.changeset/silver-penguins-behave.md
packages/jest/tsconfig.json
packages/jest/tsconfig.publish.json
packages/jest/tsconfig.publish.types.json
tsconfig.common.legacy.json
tsconfig.publish.legacy.json
tsconfig.publish.types.legacy.json

No breakage expected, users of `@fast-check/jest` should already have Node above 14.15 just because of jest itself.
**Advanced**

🔧(jest) Update tsconfig to common config

---

.github/workflows/generate-changelog.yml

Generate Changelog is our publication script. It is responsible to generate the changelog for the next release. In order to build it, it backs itself with our package manager tools to get which part of the monorepo is supposed to be published.
Following the move to pnpm we have not really adapted it. As such it was failing to run.
This PR attempts to fix the script.
**Advanced**

🔨 Add support for pnpm scripts in generate-changelog

---

.github/workflows/build-status.yml
packages/ava/README.md
packages/fast-check/README.md
packages/jest/README.md
packages/poisoning/README.md
packages/vitest/README.md
packages/worker/README.md

We decided to copy what we have in LFS to the website we publish. So instead of referencing an asset directly provided by LFS we link to one on our website. It gives us better caching, less costly option...
**Advanced**

👷 Do not pull logo of README from LFS

---

packages/fast-check/test/unit/arbitrary/_internals/implementations/SchedulerImplem.spec.ts

At the moment, `waitFor` is supposed to queue things quickly without losing any micro-tasks. But first it misses some, second the more we think of that the more we believe that this is probably not what our end-users would want to be the default.
By default when relying on schedulers they certainly want us to schedule things even if they got triggered 2 ticks after another scheduled function. As we want to capture any structural behavior change around this part we first start by adding tests around it.
**Advanced**

✅ Closely test `waitFor` on interactions with micro-tasks

---

.changeset/quick-islands-bow.md
packages/fast-check/src/arbitrary/_internals/implementations/SchedulerImplem.ts
packages/fast-check/test/unit/arbitrary/_internals/implementations/SchedulerImplem.spec.ts

🐛 Avoid overlapping tasks during `scheduler` execution

---

.changeset/tame-dragons-rest.md
packages/fast-check/src/arbitrary/_internals/implementations/SchedulerImplem.ts

Honestly impact might be close to zero.
**Advanced**

⚡️ Slightly faster `scheduler` with explicit `undefined` check

---

.github/workflows/build-status.yml

👷 Only run coverage for ubuntu on node 22

---

.github/workflows/build-status.yml

👷 Shard Vitest execution on Windows runners

---

.github/workflows/build-status.yml
website/docs/introduction/getting-started.md

👷 Always publish on pkg-pr-new

---

.changeset/curvy-donuts-refuse.md
packages/vitest/src/internals/TestAlongGenerator.ts

The latest version of `@fast-check/vitest` included a bug making it not properly working against fast-check v3.
Fixes #5911
**Advanced**

🐛(vitest) Forward errors with fast-check@3

---

packages/fast-check/test/e2e/Poisoning.spec.ts

CI was broken due to Node 24.
**Advanced**

💚 Make poisoning test compatible with Node 24

---

examples/package.json
package.json
packages/ava/package.json
packages/fast-check/package.json
packages/fast-check/test/e2e/documentation/Docs.md.spec.ts
packages/jest/package.json
packages/packaged/package.json
packages/poisoning/package.json
packages/vitest/package.json
packages/worker/package.json
pnpm-lock.yaml
website/package.json

This reverts commit 6d40536f3239cdc1405c4081e64d791d94d919a8.

⬆️ Revert update vitest monorepo to ^3.1.1

---

.changeset/solid-knives-fetch.md
website/docs/core-blocks/arbitraries/combiners/string.md

:memo: update stringMatching docs

---

.github/workflows/build-status.yml

Testing against Node 18 was causing issues with the bump of Jest to version 30. As such and because Node 18 is no longer an LTS version, we are removing it from our testing matrix.
**Advanced**

✅ Stop testing against Node 18

---

.changeset/smart-needles-brush.md
packages/vitest/src/internals/TestBuilder.ts

When running our Vitest plugin against v3 of fast-check some users might suffer from the fact that the diff is shallow by default. This is not be the case of the dafult setup when relying on our plugin.
As such this PR makes sure that the default will avoid it.
Fixes #5995
**Advanced**

🐛(vitest) No shallow diff in Vitest, full diff by default

---

pnpm-workspace.yaml

I was following `CONTRIBUTING.md` and when I ran `pnpm install`, I was asked to run `pnpm approve-builds`. After I approved the builds it updated the workspace file.
**Advanced**

🔨 Update `ignoredBuiltDependencies`

---

.github/workflows/build-status.yml

It seems that Node 24.6.0 somehow broke the way we trigger Jest in some of our tests.
Part of our tests defined in `docs/tutorials/detect-race-conditions/snippets.spec.mjs` started to explode with the error:
> ReferenceError: You are trying to `import` a file after the Jest environment has been torn down. From queue.spec.mjs.
**Advanced**

💚 Avoid specs to run against Node >=24.6.0

---

.github/workflows/build-status.yml

Rather than manually applying the provenance in our workflow, we let GitHub and NPM handle everything for us by relying on the notion of [Trusted Publishing](https://docs.npmjs.com/trusted-publishers).
**Advanced**

👷 Move to trusted publishing to NPM

---

.github/workflows/build-status.yml

Tests are totally broken when running under Windows. We are waiting fro version 4.x of Vitest to check if we can enable them back. But for now the issue that we face is unresolved on Vitest 3.x: https://github.com/vitest-dev/vitest/discussions/6511#discussioncomment-13854168.
**Advanced**

💚 Stop running tests against Windows

---

website/src/components/HomepageSponsors/index.js

Applying recommendation from https://dequeuniversity.com/rules/axe/4.10/object-alt

📝 Better accessibility on website
